Makefile
panther_cli/main.py
tests/fixtures/example_policy.yml

Allow a `Suppressions` field in the analysis configurations file in order to support managing suppressions in code.
* Modified `SPEC_SCHEMA` schema definition
* Unit tests
* Used on internal policies/rules to verify correctness

Support Suppressions in Analysis Specification File

---

analysis/rules/cis/aws_cloudtrail_modified.yml
analysis/rules/cis/aws_config_service_modified.yml
analysis/rules/cis/aws_console_login_failed.yml
analysis/rules/cis/aws_console_login_without_mfa.yml
analysis/rules/cis/aws_ec2_gateway_modified.yml
analysis/rules/cis/aws_ec2_network_acl_modified.yml
analysis/rules/cis/aws_ec2_route_table_modified.yml
analysis/rules/cis/aws_ec2_security_group_modified.yml
analysis/rules/cis/aws_ec2_vpc_modified.yml
analysis/rules/cis/aws_iam_policy_modified.yml
analysis/rules/cis/aws_kms_cmk_loss.yml
analysis/rules/cis/aws_root_activity.yml
analysis/rules/cis/aws_s3_bucket_policy_modified.yml
analysis/rules/cis/aws_unauthorized_api_call.yml
analysis/rules/s3_access_logs/aws_s3_access_error.yml
analysis/rules/s3_access_logs/aws_s3_access_ip_whitelist.yml
analysis/rules/s3_access_logs/aws_s3_insecure_access.yml
analysis/rules/s3_access_logs/aws_s3_unauthenticated_access.yml
analysis/rules/vpc_flow_logs/aws_vpc_healthy_log_status.yml
analysis/rules/vpc_flow_logs/aws_vpc_inbound_traffic_port_blacklist.yml
analysis/rules/vpc_flow_logs/aws_vpc_inbound_traffic_port_whitelist.yml
analysis/rules/vpc_flow_logs/aws_vpc_unapproved_outbound_dns.yml
tests/fixtures/valid_policies/example_rule.yml

The `.Log` suffix has been removed from log types (it was redundant)
Updating the default rules so that they don't include the `.Log` suffix
Find & Remove `.Log`occurences
@nhakmiller  Not sure how to create a new release of the rules. I'll need your help for it once this is merged.

Removed  suffix from Log types

---

Makefile
README.md
analysis/policies/s3/aws_s3_lifecycle_configuration_expires_data.py
analysis/policies/s3/aws_s3_lifecycle_configuration_expires_data.yml
analysis/policies/s3/aws_s3_logging_enabled.yml
panther_cli/__init__.py
panther_cli/main.py
requirements-top-level.txt
requirements.txt
setup.py

I found a bug in one of our policies, which spawned the remainder changes
* README edit
* Fix a bug in the s3 lifecycle policy
* Add Apache 2 headers
* Locally with the CLI

S3 Lifecycle Policy Fix, Licensing, and More

---

analysis/aws_rules_cis/aws_cloudtrail_modified.py
analysis/aws_rules_cis/aws_config_service_modified.py
analysis/aws_rules_cis/aws_console_login_failed.py
analysis/aws_rules_cis/aws_console_login_without_mfa.py
analysis/aws_rules_cis/aws_ec2_gateway_modified.py
analysis/aws_rules_cis/aws_ec2_network_acl_modified.py
analysis/aws_rules_cis/aws_ec2_route_table_modified.py
analysis/aws_rules_cis/aws_ec2_security_group_modified.py
analysis/aws_rules_cis/aws_ec2_vpc_modified.py
analysis/aws_rules_cis/aws_iam_policy_modified.py
analysis/aws_rules_cis/aws_kms_cmk_loss.py
analysis/aws_rules_cis/aws_root_activity.py
analysis/aws_rules_cis/aws_s3_bucket_policy_modified.py
analysis/aws_rules_s3_access_logs/aws_s3_access_error.py
analysis/aws_rules_s3_access_logs/aws_s3_access_error.yml
analysis/aws_rules_s3_access_logs/aws_s3_access_ip_whitelist.py
analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.py
analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.yml
analysis/aws_rules_s3_access_logs/aws_s3_unauthenticated_access.py
analysis/aws_rules_s3_access_logs/aws_s3_unauthenticated_access.yml
analysis/aws_rules_vpc_flow_logs/aws_vpc_healthy_log_status.py
analysis/aws_rules_vpc_flow_logs/aws_vpc_inbound_traffic_port_blacklist.py
analysis/aws_rules_vpc_flow_logs/aws_vpc_inbound_traffic_port_whitelist.py
analysis/aws_rules_vpc_flow_logs/aws_vpc_unapproved_outbound_dns.py

The way that the Panther backend handles log processing has changed, and as a result not all top level keys are always present in a given log now. This means that even for top level keys we must perform lookups that do not assume the key is present, otherwise we risk keys errors. Additionally, we no longer maintain the S3 access log standard of the string `-` meaning a null value, and instead replace it with an actual null value (and so omit the key entirely). This change updates all the default rules to reflect this change.
Closes #17.
* Updated all rules to perform safe lookups when accessing top level keys
* testing with `make ci`

Rules perform safe lookups

---

analysis/aws_rules_guardduty/aws_guardduty_high_sev_findings.py
analysis/aws_rules_guardduty/aws_guardduty_high_sev_findings.yml
analysis/aws_rules_guardduty/aws_guardduty_low_sev_findings.py
analysis/aws_rules_guardduty/aws_guardduty_low_sev_findings.yml
analysis/aws_rules_guardduty/aws_guardduty_med_sev_findings.py
analysis/aws_rules_guardduty/aws_guardduty_med_sev_findings.yml

Basic GuardDuty rules for flagging high/medium/low severity findings
* ^ 
```
$ panther-cli test --policies analysis/aws_rules_guardduty/
[INFO]: Testing Policies in analysis/aws_rules_guardduty/
AWS.GuardDuty.HighSeverityFinding
[PASS] High Sev Finding
AWS.GuardDuty.LowSeverityFinding
[PASS] Low Sev Finding
AWS.GuardDuty.MediumSeverityFinding
[PASS] Medium Sev Finding
```

[guardduty] init rules for high/med/low sev findings

---

README.md
analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.py
analysis/aws_rules_cloudtrail/aws_update_credentials.py
analysis/aws_rules_cloudtrail/aws_update_credentials.yml

Add a new rule for monitoring IAM credential changes
* New rule for `aws_update_credentials.yml`
* Update the dedup key on the `aws_s3_bucket_deleted.py` to group by the ARN deleting the bucket
```
$ panther-cli test --policies analysis/aws_rules_cloudtrail/
[INFO]: Testing Policies in analysis/aws_rules_cloudtrail/
AWS.S3.BucketDeleted
[PASS] An S3 Bucket was deleted
[PASS] An S3 Object Deleted
AWS.IAM.CredentialsUpdated
[PASS] User Password Was Changed
[PASS] MFA Device Was Created
```

Rule for Updated Credentials

---

Makefile
README.md

Previously the `make test` command did not work if any policies or rules actually made use of the `aws_globals` file. This is because of the way the `panther_analysis_tool` was being used, it expects to find all files under one root directory and we were not testing it in that way. I've update the Makefile to work first copy all policies/rules into a temporary directory, then run the `panther_analysis_tool` against that directory.
* Updated `make test` target
* Updated incorrect line in README (was pointing to a git link when it needed to be an https link)
* `make test`

Update test procedures and README

---

aws_policies_managed/aws_resource_required_tags.py

A few months ago we changed how resources are stored internally,  but I just realized this particular policy was never updated. Updating it now to use the correct syntax.
* Updated policy that referred to certain resource meta data
* None

Update policies that refer to schema

---

aws_rules_cis/aws_kms_cmk_loss.py
aws_rules_cis/aws_s3_bucket_policy_modified.py
aws_rules_cis/aws_s3_bucket_policy_modified.yml
aws_rules_cis/aws_unauthorized_api_call.py
aws_rules_cis/aws_unauthorized_api_call.yml
aws_rules_cloudtrail/aws_s3_bucket_deleted.py

There are a couple of emerging themes starting to show:
1. Let's only alert on successful API calls
2. A way to strip the session out of an AssumedRole ARN
3. Formal rule helper support it needed
* Tune more AWS rules (see changes for context)
* Locally with `panther_analysis_tool`

[aws_rules] deduping, helper func, titles

---

aws_policies_s3/aws_s3_bucket_policy_allow_with_not_principal.yml
aws_policies_s3/aws_s3_bucket_principal_restrictions.yml
aws_policies_s3/aws_s3_bucket_public_access_block.yml
aws_policies_s3/aws_s3_bucket_public_read.yml

I found an issue where tags were accidentally listed as ResourceTypes. @nhakmiller can you see if any other policies/rules have this issue?
* Fix typo in ResourceTypes
* CI

[aws_policies_s3] fix accidental tag in resource type

---

aws_rules_guardduty/aws_guardduty_high_sev_findings.py
aws_rules_guardduty/aws_guardduty_high_sev_findings.yml
aws_rules_guardduty/aws_guardduty_low_sev_findings.py
aws_rules_guardduty/aws_guardduty_low_sev_findings.yml
aws_rules_guardduty/aws_guardduty_med_sev_findings.py
aws_rules_guardduty/aws_guardduty_med_sev_findings.yml

Add deduplication and title to GuardDuty rules
* Set `dedup` to the GuardDuty finding ID
* Set the `title` to the GuardDuty generated title
* Set the `DedupPeriodMinutes` per the severity (8 hours for low, 1 hour for med/high)
* CI

[guardduty] set dedup, title, and dedup period

---

osquery_rules/mac/osquery_mac_osx_attacks_keyboard_events.py

Tune the osquery keyboard taps rule
* Whitelist photoshop
```
Osquery.Mac.ApplicationFirewallSettings
[PASS] ALF Disabled
[PASS] ALF Enabled
Osquery.Mac.AutoUpdateEnabled
[PASS] Auto Updates Disabled
[PASS] Auto Updates Enabled
[PASS] Wrong Key
Osquery.Mac.OSXAttacks
[PASS] Valid malware discovered
[PASS] Keyboard event taps query is ignored
Osquery.Mac.OSXAttacksKeyboardEvents
[PASS] App running on Desktop that is watching keyboard events
[PASS] App is running from approved path
[PASS] Unrelated query does not alert
Osquery.Mac.UnwantedChromeExtensions
[PASS] Unwanted Extension Detected
[PASS] No Unwanted Chrome Extension Detected
```

[osquery] whitelist photoshop

---

osquery_rules/common/osquery_ossec.py
osquery_rules/common/osquery_suspicious_cron.py
osquery_rules/linux/osquery_linux_logins_non_office.py
osquery_rules/linux/osquery_linux_logins_non_office.yml
osquery_rules/mac/osquery_mac_application_firewall.py
osquery_rules/mac/osquery_mac_enable_auto_update.py
osquery_rules/mac/osquery_mac_osx_attacks.py
osquery_rules/mac/osquery_mac_osx_attacks_keyboard_events.py
osquery_rules/mac/osquery_mac_unwanted_chrome_extensions.py

Just doing some tuning
* Support multiple office networks from non-office-logins
* Support /32 networks
* Tune the alert titles
* Panther Analysis Tool

support OFFICE_NETWORKS and format title with []

---

aws_s3_policies/aws_s3_bucket_mfa_delete.yml
aws_s3_rules/aws_s3_access_error.py
aws_s3_rules/aws_s3_access_error.yml
aws_s3_rules/aws_s3_access_ip_whitelist.py
aws_s3_rules/aws_s3_access_ip_whitelist.yml
aws_s3_rules/aws_s3_insecure_access.py
aws_s3_rules/aws_s3_insecure_access.yml
aws_s3_rules/aws_s3_unauthenticated_access.py
aws_s3_rules/aws_s3_unknown_requester_get_object.py
aws_s3_rules/aws_s3_unknown_requester_get_object.yml

A general audit and refresh of our S3 access log rules
* Disable MFA delete policy by default
* Tune S3 access log rules, disable some by default, update severities and test cases
Locally:
```
[INFO]: Testing analysis packs in aws_s3_rules/
AWS.S3.ServerAccess.Error
[PASS] Access Error
[PASS] Internal Server Error
AWS.S3.ServerAccess.IPWhitelist
[PASS] Access From Approved IP
[PASS] Access From Unapproved IP
AWS.S3.ServerAccess.Insecure
[PASS] Secure Access to S3 Bucket
[PASS] Insecure Access to S3 Bucket
AWS.S3.ServerAccess.Unauthenticated
[PASS] Authenticated Access
[PASS] Unauthenticated Access
AWS.S3.ServerAccess.UnknownRequester
[PASS] Expected Access
[PASS] Unexpected Access
```

May Update: S3 Rules

---

global_helpers/panther_default.py
global_helpers/panther_default.yml

By default, the only global accessible via the web UI is the one with the ID `panther`. This change adds this global to the default analysis pack so that users who want a CLI first workflow can still manage this out of the box global.
* Added the default global
* `make ci`

Add default global

---

aws_account_policies/aws_password_policy_complexity_guidelines.yml

Spelling mistake `Policyu` -> `Policy`
* Fixed spelling
* n/a

fix: typo in the one of the rules

---

aws_cloudtrail_rules/aws_unauthorized_api_call.yml
aws_s3_rules/aws_s3_access_error.py
aws_s3_rules/aws_s3_access_error.yml

Ignore errors when sending from Amazon
* Move the AccessDenied rule to INFO (it's required for CIS still)
* Adjust the s3 error rule to ignore Amazon incomplete body errors
* CLI

tune s3 error rule

---

aws_cloudtrail_rules/aws_root_activity.py
aws_cloudtrail_rules/aws_root_activity.yml
requirements.txt

It appears that the action of creating a ServiceLinkedRole is coming from Amazon upon account creation - adding it to the allow list for now.
* Update CloudTrail Root rule
* Upgrade dev requirements
* Add test case
Tested locally with the PAT

ignore service linked role creation

---

aws_s3_rules/aws_s3_unknown_requester_get_object.py
aws_s3_rules/aws_s3_unknown_requester_get_object.yml

We've been observing the following error raised by this rule:
```
failed to run rule AWS.S3.ServerAccess.UnknownRequester RuleResult TypeError('expected str, bytes or os.PathLike object, not NoneType')
```
The cause of this error is that `fnmatch` expects a str, bytes or os.PathLike object for the first argument but the default behavior of `.get()` on a missing key is to return a `NoneType`, which `fnmatch` cannot handle.
* Added an appropriate default value to `.get()`
* Explicitly handled requests with errors so they do not alarm. The only cases I observed where the requester was not present were cases where there was an error, we already have a rule looking for those so presumably we don't want this alerting as well
* Added a new unit test for this situation

Fix null requester errors

---

osquery_rules/osquery_linux_aws_commands.py
osquery_rules/osquery_linux_aws_commands.yml
osquery_rules/osquery_suspicious_cron.py
osquery_rules/osquery_suspicious_cron.yml

Got a pager alert on a failed rule. Issue was not handing quoted strings in shlex.split()
* escape input to shlex.split()
* make test

Escape quotes when using shlex.split()

---

aws_cloudtrail_rules/aws_iam_user_recon_denied.yml
aws_cloudtrail_rules/aws_unauthorized_api_call.yml

There was a bug in a rule causing the frontend to prevent the user from updating a rule because it has two tests with the same name.
* Renamed the tests to have the suffix `(IP)` and `(FQDN)` respectively
* Cleaned up duplicate object attributes, added an extra test to match internal.
* Locally and in the frontend.

fix: renamed the tests to have different names, cleaned up object

---

aws_cloudtrail_policies/aws_cloudtrail_s3_bucket_public.yml
aws_cloudtrail_rules/aws_iam_user_recon_denied.py
aws_config_policies/aws_config_global_resources.yml
aws_iam_policies/aws_password_unused.yml
aws_iam_policies/aws_root_account_access_keys.yml
aws_iam_policies/aws_root_account_hardware_mfa.yml
aws_vpc_policies/aws_security_group_administrative_ingress.yml
aws_vpc_policies/aws_vpc_flow_logs.yml

While developing the latest GSuite rules, I think I noticed a bug in the IAM User recon rule. Let me know if you think this change is correct.
Additionally, `make test` found a handful of misformatted config files. I'm assuming the recent(ish) `panther_analysis_tool`  updates caught a previously missed formatting issue.
* Changed IAM recon rule logic
* Fixed `Reports` field on several policies and rules
* Unit testing

Fix recon rule

---

osquery_rules/osquery_linux_aws_commands.py
osquery_rules/osquery_linux_aws_commands.yml

We were paged over the weekend for 2 different errors:
* failed to run rule Osquery.Linux.AWSCommandExecuted RuleResult ValueError('No closing quotation')
* failed to run rule Osquery.Linux.AWSCommandExecuted RuleResult ValueError('No escaped character')
These are caused by `shlex.split(command)` if the input command is invalid. Since osquery is just reading the shell history, I assume it's possible for invalid commands to be entered by developers - these should be safely ignored and not trigger errors.
This also reverts #72 - `shlex` is designed to handle single quotes, I'm not sure why we had to escape them:
```python
import shlex
shlex.split("git commit -m 'multi word msg'")
```
All of the tests pass without the escaping; I assume it was an (incorrect) attempt to fix the same issue I …

Osquery: Ignore ValueErrors when parsing command

---

gravitational_teleport_rules/teleport_network_scanning.py
gravitational_teleport_rules/teleport_network_scanning.yml
gravitational_teleport_rules/teleport_scheduled_jobs.py
gravitational_teleport_rules/teleport_scheduled_jobs.yml

Detect network scanning kicked off from a scheduled job
* Expand the scope of the network scanning rule
* Tweak the title on the scheduled jobs rule
Locally with the PAT

[teleport] Tuning

---

okta_rules/okta_geo_improbable_access.py

The Okta rule for geographically improbable access was sometimes having an exception computing the haversine distance between two points
```ValueError: math domain error```
This was caused by the formula mixing radians and degrees when calculating `distance_c`
* Made the function convert all coordinates represented in degrees to radians
* Swapped part of the algorithm to use the simpler  `asin...` inverse calculation
* Tested locally using coordinates in degrees which were previously failing

fix: haversine calculation to always use radians

---

aws_acm_policies/aws_acm_certificate_valid.yml
aws_cloudformation_policies/aws_cloudformation_stack_drifted.py
aws_cloudformation_policies/aws_cloudformation_stack_drifted.yml
aws_cloudformation_policies/aws_cloudformation_stack_uses_iam_role.yml
aws_cloudformation_policies/aws_cloudformation_termination_protection.yml
aws_cloudwatch_policies/aws_cloudwatch_loggroup_data_retention.yml
aws_cloudwatch_policies/aws_cloudwatch_loggroup_encrypted.yml
aws_config_policies/aws_config_all_resource_types.yml
aws_config_policies/aws_config_recording_enabled.yml
aws_config_policies/aws_config_recording_no_error.yml
aws_ec2_policies/aws_ami_private.yml
aws_ec2_policies/aws_ec2_volume_encryption.yml
aws_ec2_policies/aws_ec2_volume_snapshot_encrypted.yml
aws_iam_policies/aws_cloudtrail_least_privilege.yml
aws_rds_policies/aws_rds_instance_auto_minor_version_upgrade_enabled.yml
aws_s3_rules/aws_s3_unauthenticated_access.yml
aws_vpc_policies/aws_network_acl_restricted_ssh.yml

Both customers and developers have reported broken policy runbook links. Specifically:
* AWS CloudFormation Stack Drift: https://docs.runpanther.io/amazon-web-services/policies/aws-cloudformation-stack-has-not-drifted
* AWS CloudWatch Log Encryption: https://docs.runpanther.io/amazon-web-services/policies/aws-cloudwatch-logs-are-encrypted
I audited all runbook links - we had 14 broken links. With only one exception, these pages actually don't exist and never have, as far as I can tell. I looked at our documentation history to make sure I didn't accidentally remove them when moving the docs around, but it doesn't look like they were ever there.
Our runbooks are scattered and in the future will need some kind of standardization. Only half have doc pages, and a substantial part of the …

Remove broken runbook links, ignore Panther stacks in stack drift policy

---

aws_cloudformation_policies/aws_cloudformation_stack_drifted.yml

Based on the python logic and the name of this test, I believe this test should return True. I actually caught this when the test  failed while trying to package the release. I don't know why it wasn't caught sooner but CI, need to look into that still.
* Change expected result of test
* Ran the `panther_analysis_tool test` command

This test should return true

---

aws_iam_policies/aws_iam_resource_does_not_have_inline_policy.yml

Remove AWS.IAM.ROLE from ResourceTypes in inline policy check because IAM Roles commonly have inline policies.  This is not a bad pattern for IAMS roles, whereas for users/groups it is discouraged.   
* removed AWS.IAM.ROLE from ResourceTypes
* `make test` and ran panther_analysis_tool against changed directory.

removing AWS.IAM.ROLE from ResourceTypes from inline policy check

---

gcp_audit_rules/gcp_gcs_public.py
gsuite_reports_rules/gsuite_drive_overly_visible.yml
gsuite_reports_rules/gsuite_drive_visibility_change.yml
osquery_rules/osquery_mac_osx_attacks.yml
osquery_rules/osquery_mac_osx_attacks_keyboard_events.yml
osquery_rules/osquery_outdated.py
osquery_rules/osquery_outdated.yml
osquery_rules/osquery_suspicious_cron.yml

After updating the panther_analysis_tool to check for non-None returns from the dedup and title methods [panther_analysis_tool issue](https://github.com/panther-labs/panther_analysis_tool/issues/18) I found a few new failing cases.  This addresses those cases.
* Added missing fields needed for dedup
* Added missing return statement
* `make test` and running new version of panther_analysis_tool with title/dedup checks against this repo.

addressing new dedup|title checks

---

.github/CODEOWNERS
aws_cloudtrail_rules/aws_console_login_without_mfa.py
aws_cloudtrail_rules/aws_console_login_without_mfa.yml

The AWS console login without MFA rule did not account for cases where a session that was authenticated with MFA created a pre-authenticated sign in url that allowed someone to login directly without MFA. This case should generally be allowed, as it still requires the user to be MFA authenticated initially.
Additionally, taking this opportunity to add @lindsey-w as a codeowner on this repo.
* Added a case for sessions that were created by another session that was MFA authenticated
* Added @lindsey-w to `CODEOWNERS`
* Created new unit test

Added case for session authentication

---

gsuite_reports_rules/gsuite_mobile_device_screen_unlock_fail.py
gsuite_reports_rules/gsuite_mobile_device_screen_unlock_fail.yml

This addresses the type error identified in the gsuite rule.  It can now handle both int and String type for the `FAILED_PASSWD_ATTEMPTS` param lookup.  All other instances of param_lookup were already String comparisons/no other int type casting requirements found. Closes #103 
* casting string to int in an compare statement.
* added new test case for String type `FAILED_PASSWD_ATTEMPTS` 
* `make test` and running `panther_analysis_tool` against the updated dir

udpate to type cast to int for int comparison

---

onelogin_rules/onelogin_active_login_activity.py

This is a fix to the TypeError being thrown in OneLogin rule: ActiveLoginActivity.  Convert unique id to str before adding/editing the str set.  Error: `failed to run rule OneLogin.ActiveLoginActivity RuleResult TypeError("'int' object is not iterable")"`
* proper handling of input that is explicitly defined as str
* `make test`
* reproduced issue by modifying some of the integration tests to purposefully fail by using an int in the `add_to_string_set` call, and then running `python panther_oss_helpers.py`

fixing type error for put/add to string set

---

aws_vpc_policies/aws_network_acl_restricted_ssh.py

The rule for restricting SSH checks for inbound ACL rules, but was also triggering if you set a 'deny' policy. The rule should only look for 'allow' policies.
* Modify the rule to check if the inbound ACL rule is an 'allow' policy
* mage test:ci
* test inside panther by modifying the rule and setting a previously failing payload

fix: rule checks for allowed inbound only

---

aws_acm_policies/aws_acm_certificate_expiration.py
aws_acm_policies/aws_acm_certificate_expiration.yml

Encountering an error when we come across a null value for the acm certificate's `NotAfter` field. This address this problem by returning `False` when the field is None. Closes #29 
* Added check for null `NotAfter` field
* Added new test with null `NotAfter` field
* `make test`

Handle null `NotAfter` values

---

aws_s3_rules/aws_s3_access_error.yml

This rule had a duplicate summary attribute value, which was causing it to fail to upload because dynamo (correctly) determined this was not actually a set.
Resolves https://github.com/panther-labs/panther/issues/1685.
Opened https://github.com/panther-labs/panther_analysis_tool/issues/54 to address the inadequate specification file validation in Pat.
* Removed duplicate value
* Uploaded entire repo to Panther to verify no other rules have this issue

Removed duplicate summary attribute

---

aws_s3_policies/aws_s3_bucket_action_restrictions.yml

This test case breaks every time AWS adds a new s3 permission, which is usually once every few months. Now that we're enforcing passing test cases in both the CLI tool and the web UI, we should be more cognizant of potentially failing unit tests outside of our control. I'm just going to remove this test.
* Removed test that fails when dependency is updated
* `panther_analysis_tool test`

Remove problematic test case

---

aws_vpc_policies/aws_security_group_administrative_ingress.py
aws_vpc_policies/aws_security_group_administrative_ingress.yml
aws_vpc_policies/aws_vpc_default_network_acl_restricts_all_traffic.py
aws_vpc_policies/aws_vpc_default_network_acl_restricts_all_traffic.yml
aws_vpc_policies/aws_vpc_default_security_restrictions.py
aws_vpc_policies/aws_vpc_default_security_restrictions.yml
requirements.txt

v1.11 of Panther will no longer embed EC2  Security Group or EC2 Network ACL resources into the EC2 VPC resource. For this reason, for policies that rely on evaluating the EC2 security group or EC2 network ACL in the context of an  EC2 VPC we need to use the `resource_lookup` functionality, which was created for this use case.
* Updated `aws_vpc_default_network_acl_restricts_all_traffic` and `aws_vpc_default_security_restrictions` to use `resource_lookup`
* Updated `aws_security_group_administrative_ingress` to  apply to EC2  Security Groups directly, as opposed to EC2 VPCs.
* Unfortunately unit testing is not supported for policies that  make network calls (such as `resource_lookup`), so I had to deploy  into a dev environment and rely on that instead

Update VPC policies

---

osquery_rules/osquery_linux_aws_commands.py
osquery_rules/osquery_linux_aws_commands.yml

Add a quick condition to ignore `aws` commands coming from laptops, which is expected. Decorations can be added to osquery to provide additional context in events. 
* Check if a platform decoration is added, and ignore if the platform is MacOS
* CLI tool

[osquery] ignore darwin systems issuing AWS commands

---

aws_cloudtrail_rules/aws_console_login_failed.yml

The failed AWS logins was written before we had either the dynamo key/value store or thresholding supported, so it just alerted on every single failed login, deduped by account ID on a 4 hour period.
I changed the threshold to 5, and the dedup period to 1 hour. I think shortening the dedup period is appropriate because we're increasing the threshold. The dedup period was high before to reduce alert fatigue, but that should be less relevant if the alert is higher fidelity.
* Tuned threshold and dedup period settings
* Unit tests

Tune threshold setting for failed AWS logins

---

aws_cloudtrail_rules/aws_unauthorized_api_call.py

The `userIdentity.arn` field may be missing in some CloudTrail events.
Returning `None` by `dedup()` raises exception (we assert title/dedup
return `str`), which is logged, resulting in spamming the logs (which may trigger CloudWatch alarms)
with no real benefit. 
However, the system behavior is the same (a default value is used for title/dedup when they are missing or
return an empty string).
Update the dedup() function of the rule to return empty string if the field is missing.
Added 1.12 for milestone but feel free to update it as necessary (same for the labels, not sure which to pick).

Fix rule dedup() returning None

---

aws_cloudtrail_rules/aws_root_activity.py
aws_cloudtrail_rules/aws_root_activity.yml
okta_rules/okta_geo_improbable_access.py
okta_rules/okta_geo_improbable_access.yml

Filter out failing events. Failed activity is probably indicative of a low effort bot trying to brute force logins more so than a serious threat.  Failed logins can be tracked with other lower severity rules related specifically to brute forcing. These rules should be high fidelity alerts that something actually did happen.
Closes #131.
* Changed the root activity rule to ignore events with error messages
* Changed the okta geographically improbable login rule to ignore failed logins
* Added two new test cases based on user reports

Filter out failed events when looking for bad activity

---

aws_s3_policies/aws_s3_bucket_public_read.py
aws_s3_policies/aws_s3_bucket_public_read.yml
aws_s3_policies/aws_s3_bucket_public_write.py
aws_s3_policies/aws_s3_bucket_public_write.yml

Python function assumes that the key "Grants" is not Null, new resource example proves otherwise, handling the NoneType prevents an error from being thrown in panther UI under Cloud Security.
* Add Key and NoneType check for both S3 read and write
* make test-single pack=aws_s3_policies

Input validation for the S3 Bucket Read and Write

---

aws_cloudtrail_rules/aws_console_root_login.py
aws_cloudtrail_rules/aws_root_activity.py
global_helpers/panther_base_helpers.py
okta_rules/okta_admin_role_assigned.py
okta_rules/okta_admin_role_assigned.yml
okta_rules/okta_brute_force_logins.py
okta_rules/okta_brute_force_logins.yml
okta_rules/okta_geo_improbable_access.py
okta_rules/okta_geo_improbable_access.yml
test_scenarios/enrichment-example/README.md
test_scenarios/enrichment-example/attacker_cloudtrail.yml
test_scenarios/okta-add-administrator/README.md
test_scenarios/okta-add-administrator/admin_privs_assigned.yml
test_scenarios/okta-add-administrator/brute_force_logins.yml
test_scenarios/okta-add-administrator/legit_login.yml

Two sets of scenarios and rules for the upcoming Panther+Tines webinar!
* Basic Okta rules
* Update CloudTrail dedup and alert contexts
* Unit tests + full end-to-end testing with the `send_data` script (we should fold this functionality into the PAT at some point)

Tines Webinar Prep: Okta and CloudTrail Rules/Scenario

---

aws_cloudtrail_rules/aws_resource_made_public.py
aws_cloudtrail_rules/aws_resource_made_public.yml

If there is a failed attempt to make an S3 bucket public (due to access denied) the rule still fires today creating a lot of noise.
* Added check for PutBucket if the access was denied
* Added new test for the access denied log entry
* Ran test with  make test-single pack=aws_cloudtrail_rules and all passed

Don't alert if access is denied to S3 putbucket.

---

global_helpers/panther_iocs.py
global_helpers/panther_iocs.yml
okta_rules/okta_admin_role_assigned.py
panther_ioc_rules/sunburst_fqdn_iocs.py
panther_ioc_rules/sunburst_fqdn_iocs.yml
panther_ioc_rules/sunburst_ip_iocs.py
panther_ioc_rules/sunburst_ip_iocs.yml
panther_ioc_rules/sunburst_sha256_iocs.py
panther_ioc_rules/sunburst_sha256_iocs.yml

A few simple rules to look for activity from known IOCs related to the sunburst compromise.
* Created a new global helper: `panther_iocs` : `panther_iocs.py` 
* Created a new folder for IOC rules: `panther_ioc_rules`
* Added Sunburst IP/FQDN/SHA-256 IOC rules
* `make test`

Global IOC Helpers

---

aws_cloudtrail_rules/aws_resource_made_public.py
aws_cloudtrail_rules/aws_resource_made_public.yml

Passing an empty string to json.loads, i.e. `json.loads('')`, will raise a `JSONDecodeError`
We want to be able to handle edge cases where the policy we are expecting to be populated is empty.
Specifying the default value for `dict.get` is a good practice, but does not handle cases where that policy is an empty string.
* Generalized the return statement for `aws_resource_made_public.py` 
* Added in a check to ensure we don't attempt to call `json.loads` on an empty string
* `make test`

AWS CloudTrail Rule Fix - Resource Made Public

---

.circleci/config.yml
Makefile

To better accommodate external contributions, I think we should split the jobs so people better understand why a CI job failed. Note, I'm not too familiar with how to go about caching (looking for advice from @austinbyers).
We'll also have to update the required checks (which should just be unit tests IMO)
* Split Test and Lint
* This PR

[ci] split test and lint jobs

---

okta_rules/okta_geo_improbable_access.py

Backwards compatibility issues with the Okta Geographically Improbably Fix
*  replaces direct dictionary access  (using ['']) with .get

Okta Geographically Improbable Fix - Backwards Compatibility

---

aws_cloudtrail_rules/aws_iam_user_recon_denied.py
data_models/gcp_data_model.py
gcp_audit_rules/gcp_iam_admin_role_assigned.py
osquery_rules/osquery_mac_osx_attacks_keyboard_events.py

The rule `Account Security Configuration Changed` raised a `TypeError('expected str, bytes or os.PathLike object, not NoneType')`
This appears to be related the `fnmatch` function calling `os.path.normcase` which throws an exception when it gets a `None` 
* Added default values to files using fnmatch so we return a default empty string instead of a None type to avoid an exception by fnmatch.

BUG: TypeError thrown by fnmatch.fnmatch

---

Makefile

There was a mistake in the Makefile that zips the managed schemas, regarding the comment put into the archive to mark the release version. It was only possible to catch with a properly-formatted release tag (i.e. `vX.Y.X`) and was not caught during testing with the `vX.Y.Z-test` tags used during development.
* Fix Makefile to put the correct release version in the archive comment
* built with `make managed-schemas.zip`, added asset to `v1.15.0` release and updated managed schemas on panther through PAT

Fix make managed-schemas.zip to have correct archive comment

---

.github/CODEOWNERS

PRs need to be approved to be merged.
We now have a new stream of PRs regarding managed schema definitions and we need people from the data-processing team to review them. 
* Adds  @kostaspap and @alxarch as codeowners to help with reviews for managed schemas.

Add @kostaspap and @alxarch as codeowners to help with reviews for managed schemas.

---

Makefile

With some recent changes to our linter, we can update what things we ignore in the linting step.
* Stop ignoring `bad-continuation` errors
* Use human readable name for skipping `fixme` errors
* Ran `make lint` locally

Tweak makefile

---

aws_config_policies/aws_config_global_resources.py
aws_config_policies/aws_config_global_resources.yml
aws_iam_policies/aws_access_keys_at_account_creation.py
aws_iam_policies/aws_access_keys_at_account_creation.yml
aws_load_balancer_policies/aws_alb_ssl_policy.py
aws_load_balancer_policies/aws_alb_ssl_policy.yml

@s0l0ist found 3 policies that were erroring out:
1. AWS.AccessKeys.AccountCreation
2. AWS.Config.GlobalResources
3. AWS.ELBv2.SSLPolicy
- AWS.AccessKeys.AccountCreation
- Wrapped the `datetime.strptime` in a try/except that attempts to use both the `PANTHER_TIME_FORMAT` and `AWS_TIME_FORMAT`
- AWS.Config.GlobalResources
- Reworked the policy. Now checks if any of the recorders are configured for global resources on a per-account basis.
- AWS.ELBv2.SSLPolicy
- Added conditionals for safe evaluation
- Renamed iterator because of outer-scope shadow issue
* `panther_analysis_tool test`
* Tested in live deployments with the resources causing issues created as unit tests

Policy Error Fixes

---

.github/workflows/main.yml

The Organization Token for synchronizing pull requests to the dogfood repo was created under a different name.

Fixed token name for GitHub workflow automation

---

aws_account_policies/aws_password_policy_complexity_guidelines.py
packs/aws.yml

Asana URL: Closes https://app.asana.com/0/1199940726973121/1199936510096869/f
Interest in creating a panther-managed "aws" pack that consists of the most critical, high value detections that can be used out of the box.
* created core panther aws pack
* `make ci`
- Included _all_ High & Critical Sev Policies & Rules
- **_Except_**: those with "Configuration Required" Tags
- Included the following Medium Severity Rules:
- AWS.Password.Unused
- AWS.PasswordPolicy.PasswordAgeLimit
- AWS.CloudTrail.AMIModifiedForPublicAccess
- AWS.Config.RecordingNoErrors
- nice to combine with High Sev `AWS.Config.RecordingEnabled` detection
- Standard.BruteForceByIP
- Excluded:
- Anything already auto-disabled out of the box
- All INFO level severities
- **_Note_**: in the future, it would be cool to define …

panther aws pack

---

schemas/logs/lacework/events.yml
schemas/logs/lacework/tests/lacework_tests.yml

Closes https://app.asana.com/0/0/1200129853533114/f
* Remove Lacework schema `native` parser
* Migrate tests from Go
* Fix time format to use strftime
* Add missing indicators
* pantherlog test ./schemas

Migrate Lacework schema and tests

---

.circleci/config.yml

Closes https://app.asana.com/0/1199959010247953/1199936510096989/f
Adds a circleci action to run `pantherlog test ./schemas` on commit.
The tool will verify all schemas under ./schemas are valid and run any `*_tests.yml` files against them.
Now you cannot merge an invalid schema
Uses the binary from the public release URL for v1.17.0-RC
* Adds circleci action for testing managed schemas
* CircleCi green

Add pantherlog test to CircleCI

---

aws_acm_policies/aws_acm_certificate_expiration.py
aws_cloudtrail_policies/aws_cloudtrail_cloudwatch_logs.py
aws_iam_policies/aws_access_key_rotation.py
aws_iam_policies/aws_access_key_unused.py
aws_iam_policies/aws_access_keys_at_account_creation.py
aws_iam_policies/aws_password_unused.py
aws_s3_policies/aws_s3_bucket_lifecycle_configuration.py
aws_s3_policies/aws_s3_bucket_lifecycle_configuration.yml
global_helpers/panther_oss_helpers.py

Closes https://app.asana.com/0/1200175800812961/1200142437417326/f
Concern around S3 Bucket Lifecycle Rule Configurations (Days to Expiration) not being parsed correctly by Panther.
This PR is meant to bring this policy up-to-date with best practice with an added check to avoid a policy error.
* Changed policy to use deep_get and dictionary `.get` method
* Added check to avoid `int-None` comparison
* `make test`

Revamped S3 Bucket Lifecycle Config Policy to use deep_get, dictionary

---

standard_rules/unusual_login.py

Rule has TypeError('Object of type datetime is not JSON serializable'). You can not dump a datetime object, casting to string to make things work.
* ```datetime.datetime.now()``` -> ```str(datetime.datetime.now())```
* panther_analysis_tool test --path ./standard_rules
* local python testing

Fix RuleTypeError

---

.github/CODEOWNERS

This is a request to add Patrick @glerb as codeowner so he is automatically tagged as a PR reviewer.
* add glerb
* n/a

add glerb as codeowner

---

aws_cloudtrail_rules/aws_resource_made_public.py

Due to a bug in 1.15, the Cloudtrail rule had to include custom logic to transparently work around the issue with `policyuniverse` type checking. This PR reverts https://github.com/panther-labs/panther-analysis/pull/191.
* Remove conversion to native object via JSON serialization/deserialization for S3 bucket policy. 
* `panther_analysis_tool test --path ./`

Remove Cloudtrail rule patch for Panther 1.15.x

---

schemas/logs/salesforce/login.yml
schemas/logs/salesforce/login_as.yml
schemas/logs/salesforce/logout.yml
schemas/logs/salesforce/uri.yml

`USER_TYPE` and `AUTHENTICATION_METHOD_REFERENCE` were added in v52.0.
* Add `USER_TYPE` and `AUTHENTICATION_METHOD_REFERENCE` fields in `Login` event type.
* Add `USER_TYPE` in `URI` event type.
Tested in https://github.com/panther-labs/panther-enterprise/pull/3540.

Add new fields for Salesforce schemas

---

.circleci/config.yml

The schema tests CI check was not required, but still the commit was marked as failed.
Temporarily run the schema tests as advisory-only. 
Pending fixes to the pantherlog test runner will allow restoring the check soon.

Do not mark commit as failed on schema test failures

---

standard_rules/unusual_login.py
standard_rules/unusual_login.yml

Did not account for "no-history" case
* Added logic and a unit test
* `panther_analysis_tool --debug test --path standard_rules`

Add no history case and test

---

aws_cloudtrail_rules/aws_console_login_without_mfa.py

Username was not included in the alert title.
* Added the username to the title
* `make fmt lint`
* `panther_analysis_tool --debug test --path aws_cloudtrail_rules`
* execution in live system

Add username to title of No MFA AWS login

---

onelogin_rules/onelogin_unusual_login.yml

The standard rule, which accomodates multiple log types, was reworked in https://github.com/panther-labs/panther-analysis/pull/283. This older version of the rule does something completely different, and doesn't use the new geolocation helper, and doesn't have mocks.
* Deprecation message in display message and description
* n/a

Deprecation message for OneLogin-specific version of this rule

---

box_rules/box_event_triggered_externally.py
box_rules/box_event_triggered_externally.yml

This rule would sometimes return `NoneType`, the default response from `.get()`,  instead of a `bool` due to python `and` short circuit evaluation.  This wraps the return in a cast to bool to ensure that doesn't happen.
* Ensure bool  is always returned by wrapping return
* new test case

Return bool type

---

github_rules/github_branch_policy_override.yml
github_rules/github_branch_protection_disabled.yml
github_rules/github_org_modified.yml
github_rules/github_repo_collaborator_change.yml
github_rules/github_repo_created.yml
github_rules/github_repo_hook_modified.yml
github_rules/github_repo_initial_access.yml
github_rules/github_repo_visibility_change.yml
github_rules/github_team_modified.yml
github_rules/github_user_access_key_created.yml
github_rules/github_user_role_updated.yml

GitHub findings are set to disabled as default, that doesn't appear to be the case with other findings
Sets the GitHub alerts to be enabled by default
N/A

chore: default github finidngs to enabled

---

gsuite_reports_rules/gsuite_drive_visibility_change.py
gsuite_reports_rules/gsuite_drive_visibility_change.yml

Drive will create an alert for every document contained within a folder as they inherit permissions from a change to the parent folder permissions. We do not want to alert on every document in that folder as that is only noise.
In visibility change rule added tuple containing log event titles that indicate the inherited permissions update, then returned False for any event matching those types
Created two new unit tests based on events from security.panther.tools, test suite passes with old and new tests 
Closes https://app.asana.com/0/1200819885715474/1200720820393300/f

Do Not Alert on Child Documents When Parent Folder Permissions Update

---

aws_cloudtrail_rules/aws_console_login_failed.yml
box_rules/box_brute_force_login.yml
gcp_audit_rules/gcp_iam_admin_role_assigned.yml
gsuite_reports_rules/gsuite_brute_force_login.yml
okta_rules/okta_brute_force_logins.yml
onelogin_rules/onelogin_admin_role_assigned.yml
onelogin_rules/onelogin_brute_force_by_ip.yml
onelogin_rules/onelogin_brute_force_by_username.yml

Deprecation syntax wasn't standardized. Also, one rule ID was altered by a previous commit, which resulted in the original rule not being disabled.
* Reverted Rule ID of `AWS.Console.LoginFailed` and moved deprecation warning to `DisplayName`
* Standardized deprecation message in `DisplayName` of other rules
* n/a

Standardize deprecations

---

gsuite_reports_rules/gsuite_permissions_delegated.yml

Superceded by [`Standard.AdminRoleAssigned`](https://github.com/panther-labs/panther-analysis/blob/master/standard_rules/admin_assigned.py)
* Disabled and added deprecation message to display name
* n/a

Deprecate Gsuite admin perms detection

---

aws_iam_policies/aws_iam_policy_administrative_privileges.py
aws_rds_policies/aws_rds_instance_snapshot_public_access.py
global_helpers/panther_oss_helpers.py

With conversion of resources to immutable-types, the `listify()` check will fail (list is not an immutablelist).  This updates this check to compare for both list and ImmutableList types
* extract listify as global
* update listify to check for additional list type
* `make test`

update isinstance check

---

packs/standard_ruleset.yml

Add Panther OSS helpers to standard ruleset pack. This is to unblock https://app.asana.com/0/1200821831799747/1201079363635197/f
Added OSS helpers to standard_ruleset.yml
* CI + Unit tests

Add OSS helpers to standard ruleset

---

global_helpers/panther_iocs.py
panther_ioc_rules/sunburst_ip_iocs.yml

The [SUNBURST breach](https://www.mandiant.com/solarwinds-break-resource-center) in 2020 was initially associated with certain Amazon-managed IP addresses. These IP addresses were quickly recycled and now no longer indicate association with SUNBURST.
* Outdated source IP addresses removed from global helper
* IP check rule disabled by default
* Updated hashes of malicious files
* n/a

Remove outdated IPs and disable IP check

---

panther_ioc_rules/log4j_exploit_iocs.py
panther_ioc_rules/log4j_exploit_iocs.yml

This rule will search ALL FIELDS in the log sources defined in the yaml. This is needed because the exploit can be injected into a ton of fields, headers, etc. Casting a wide net but the strings are oddball enough that I think the False positive rate should be low
* Create log4j exploit rule and tests
CI/CD and Unit tests

Create Detection for log4j exploit

---

.github/CODEOWNERS

Trying to limit the amount of email I am getting
* use `schemas/*` prefix for myself in `CODEOWNERS` so that I am only notified for PRs that modify schemas

Set CODEOWNERS path to schemas/* for alxarch

---

global_helpers/panther_iocs.py

Per https://www.fastly.com/blog/new-data-and-insights-into-log4shell-attacks-cve-2021-44228
```
Through our telemetry, we saw that 35% of all unique URIs contain at least one template focused on data extraction, with the following templates being the most popular among attackers:
${env:PATH}
${env:AWS_SECRET_ACCESS_KEY}
${env:AWS_SESSION_TOKEN}
${env:AWS_ACCESS_KEY_ID}
${sys:user.name}
${sys:java.version}
${sys:os.version}
${env:USER}
${java:os}
${date:MM-dd-yyyy}
${date:dd:MM:yyyy}
```
* Updated the array of IOCs with new findings
* None. Hoping someone will do that for me :)

New log4j IOCs

---

global_helpers/panther_iocs.py

- `${jn${lower:d}i:l${lower:d}ap://example.${lower:c}om:1234/callback}` wouldn't have matched. Removed unnecessary colon
- Additional breadth

Log4j: Remove unnecessary colon, extra breadth

---

.github/CODEOWNERS
panther_ioc_rules/log4j_exploit_iocs.py
panther_ioc_rules/log4j_exploit_iocs.yml

Updated, more efficient version of this rule
- compile IOC search with re
- search event converted to string for compiled re
Unit tests

Update Exploit detection to use flattened event string

---

.github/CODEOWNERS

Add the team to Codeowners
Add @panther-labs/detections to CODEOWNERS
Testing isnt really a thing here, but I'm explicity not removing individual names until we know this works as expected.
TRUST NOTHING!

Add Team Detections as codeowners

---

Pipfile
Pipfile.lock

A new version of policyuniverse creates some important fixes with regard to warning logging behavior.
This PR aligns the backend dependencies with testing and development.
* Update dependency version and run `pipenv update policyuniverse`.
* CI

Upgrade policyuniverse to latest version

---

aws_kms_policies/aws_cmk_key_rotation.py

Every instance of this policy in King of Spades is returning a value error for its dedup string
This should make the dict searches safer, and be explicit about the dedup
`Explicit is better than implicit`
Unit tests / CI checks

Update Policy to have safer dict searches and a dedup string

---

aws_kms_policies/aws_cmk_key_rotation.py
aws_kms_policies/aws_cmk_key_rotation.yml

As mentioned [here](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) any non AWS managed keys are not eligible for automatic rotation, we should not try to enforce a rotation policy on those
Short circut if the Origin is not `AWS_KMS`
Unit and CI pipeline

Only enforce policy on AWS managed keys

---

aws_s3_rules/aws_s3_access_error.yml

This rule has proven to be pretty noisey in situations like automated deployments where bucket policies might not be in place before the first atttempt to access that bucket.
The goal of this change is to only alert on likely broken processes or malicious attacks
Take the dedup hours down to 3, but up the threshold to 5
unit testing, and this rule triggers a lot in our internal environments

Change S3 Detection Threshold

---

okta_rules/okta_geo_improbable_access.py
okta_rules/okta_geo_improbable_access.yml

At times the geolocation info on these events is incomplete, resulting in false positives, i.e. Distance calculation between None and None. Commonly a problem with mobile carriers. This prevents incomplete data from being stored
Move the creation of the login information dict higher, return False if it has a None value
New Unit Test

Tune False Postives by eliminating incomplete Geolocation info

---

aws_cloudtrail_rules/aws_console_login_without_mfa.py
aws_cloudtrail_rules/aws_console_login_without_mfa.yml

AWS SSOv2 causes false positives in this rule, need to adjust logic accordingly
Add filter for SS0v2 in logic. Move some stuff around to reduce dynamo queries that arent needed
Code changes to exclude SS0v2 contributed by @derricksong
New Unit Tests

Tune Amazon SSOv2 False Postives)

---

.github/CODEOWNERS
data_models/okta_data_model.py
global_helpers/panther_event_type_helpers.py
okta_queries/okta_activity_audit.yml
okta_queries/okta_admin_access_granted.yml
okta_queries/okta_mfa_password_reset_audit.yml
okta_queries/okta_session_id_audit.yml
okta_queries/okta_support_access.yml
okta_rules/okta_account_support_access.py
okta_rules/okta_account_support_access.yml
okta_rules/okta_admin_disabled_mfa.py
okta_rules/okta_admin_disabled_mfa.yml
okta_rules/okta_admin_role_assigned.py
okta_rules/okta_mfa_password_reset_audit.yml
packs/okta.yml
standard_rules/mfa_disabled.yml

Responding to some activity with Okta, improve our detection and investigative posture with Okta
- Add  several Saved queries for investigation of Okta Activity
- Update Okta DataModel to support MFA disabled standard rule
- Add Okta Detection for access being granted to Okta Support 
- Add dynamic severity to Okta Admin Access rule
- Updated Okta Pack with new rules
- Add MFA enabled event type to event type helpers
- Add Admin MFA disable to event type helpers
- Add Okta rule for an admin disabling MFA globally
* Unit Tests / CICD

Okta Rule updates and investigative queries

---

aws_cloudtrail_rules/aws_console_login_without_mfa.py

This was returning None in some cases which throws an error on a check for the string. Adding a default to avoid this
Add default to Deep get Function
Unit Testing

Add a default to deep_get to avoid NoneType

---

okta_queries/okta_activity_audit.yml
okta_queries/okta_admin_access_granted.yml
okta_queries/okta_mfa_password_reset_audit.yml
okta_queries/okta_session_id_audit.yml
okta_queries/okta_support_access.yml

Queries enabled by default break upload if the table does not exist 
Disabled the queries
Unit Tests

Disable queries by default

---

lookup_tables/greynoise/advanced/noise_advanced.yml
lookup_tables/greynoise/advanced/riot_advanced.yml
lookup_tables/greynoise/basic/noise_basic.yml
lookup_tables/greynoise/basic/riot_basic.yml

We need to reference the Conduit Production resources in the GreyNoise Pack files by default.
* Updated from the staging to the prod resources
* Manual deployment to `gremlins`

Default to the Conduit Prod resources

---

packs/box.yml
packs/gcp_audit.yml
packs/gsuite_reports.yml
packs/log4j.yml
packs/okta.yml
packs/onelogin.yml

Rules were deprecated at some point, but not removed from Packs
All deprecated rules are disabled
Going to consider the best way to boneyard old rules rather than letting them stay in the main folder
Remove from Packs
Unit

Remove deprecated rules from packs

---

okta_rules/okta_support_reset.py
okta_rules/okta_support_reset.yml

Per [Okta's docs,](https://support.okta.com/help/s/article/Auditing-customer-support-actions-in-your-Okta-tenant-using-System-Log?language=en_US#:~:text=To%20search%20for%20events%20initiated%20by%20a%20Support%20Engineer%20in%20Super%20User%20(SU)%2C%20use%20the%20following%20query%3A%0AeventType%20eq%20%22user.account.reset_password%22%20AND%20actor.alternateId%20eq%20%22system%40okta.com%22%20AND%20transaction.id%20eq%20%22unknown%22) it appears the field we want here is transaction.id.  Both transaction.id and uuid are unique identifiers for an event, but they are not the SAME unique identifiers for an event
Update logic to look at correct field
Unit Testing

Update event ID field

---

aws_load_balancer_policies/aws_alb_ssl_policy.py

`ELBSecurityPolicy-FS-1-2-Res-2020-10` is missing from the list.
* Added `ELBSecurityPolicy-FS-1-2-Res-2020-10` to the list.
WIth `ELBSecurityPolicy-FS-1-2-Res-2020-10` added, the list now matches present-day output of the commented AWS CLI command to generate the list.
* ELBs that were failing because `ELBSecurityPolicy-FS-1-2-Res-2020-10` was the utilize SecurityPolicy now no longer fail.

Add Res-2020-10 to the TLSv1.2 list

---

global_helpers/z_gcp_base_helpers.py
global_helpers/z_gcp_base_helpers.yml

These functions will be useful for many gcp detections.
adds get_info, get_k8s_info and get_flow_log_info
We have several detections that rely on these helpers. Will follow up with other PRs once this is merged.
The gcp_base_helpers.py relies on the deep_get base helper and there is a load order issue on local development that required us to prefix with z_.  This can be removed once the load order bug is fixed.
global_helpers/z_gcp_base_helpers.py
global_helpers/z_gcp_base_helpers.yml
Tested in our deployment in gcp_k8s_rules detections.

gcp_base_helpers

---

global_helpers/panther_oss_helpers.py

The timestamp format for `p_event_time` is not in the `TIME_FORMATS` list. This timestamp format eventually gets resolved with the `dateutil.parser` method, but only after attempting to resolve each format in the `TIME_FORMATS` list. Since `p_event_time` is a rather common timestamp format, this PR adds that format to be the best case.
* Added Panther `p_event_timestamp` format to `TIME_FORMATS`
* Manual performance testing for `resolve_timestamp_string`

Optimize resolve_timestamp_resolver

---

Pipfile
data_models/gcp_data_model.py
global_helpers/panther_oss_helpers.py

After consideration, we do not want panther-analysis depending on panther_core. This is the invert of https://github.com/panther-labs/panther-analysis/pull/430/files

remove panther_core, update imports

---

global_helpers/panther_iocs.py
panther_ioc_rules/atlassian_confluence_ip_iocs.py
panther_ioc_rules/atlassian_confluence_ip_iocs.yml

Adds IP IOCs for the recent Atlassian Confluence on-prem 0-Day
* Added IOCs published by Volexity
* Added a new rule that checks for these IOCs
* `make test`

Confluence 0-Day IOCs

---

aws_cloudtrail_rules/aws_console_login_without_mfa.py
aws_cloudtrail_rules/aws_console_login_without_mfa.yml

When using an external IdP that gives users direct role assumption on ConsoleLogin, the MFA bits are not set in the cloudtrail logs ( even when the external IdP requires MFA ). 
This changeset creates a user configurable flag to inform the ConsoleLogin without MFA detection that an external IdP is in use. When set, this detection will not fire an alert for ConsoleLogin cloudtrail events when the  `userIdentity.type: AssumedRole` is set. 
* User configurable flag for external IdP that does direct role assumption
* New test condition added to validate that this detection works as intended
* Existing test conditions confirm that historical behavior is unchanged

feat: allow users to define that they have an External IdP which enforces MFA for AWS RoleAssumption on ConsoleLogin events

---

aws_cloudtrail_rules/aws_s3_activity_greynoise.py
aws_cloudtrail_rules/aws_s3_activity_greynoise.yml

Greynoise data may be stale, specifically for AWS IP space. There are occurrences where Panther accesses a S3 bucket from an IP that has been labeled as previously malicious. This change addresses that case.
* Create an allow list that include Panther roles known to trigger this alert
* add logic that excludes that access from generating an alert
* Add a test
* make test/lint

fix: S3 malicious access allow panther roles from AWS

---

aws_cloudtrail_rules/aws_s3_activity_greynoise.py

The greynoise object contains a function organization() not an attribute.
* NOISE.organization --> NOISE.organization()
* make lint/test

fix: greynoise object function call not attribute

---

data_models/gcp_data_model.py

Previously the GCP Data Model has an incorrect mapping for users and roles, which makes detection rules like [Standard.AdminRoleAssigned](https://github.com/panther-labs/panther-analysis/blob/master/standard_rules/admin_assigned.py) to throw an incorrect title when it comes to GCP Admin Assigned alerts.
For example, the tests in the Standard.AdminRoleAssigned rule will throw the following alert title:
```
GCP.AuditLog: [bob@example.com] assigned admin privileges [["cat@example.com"]] to [["roles/resourcemanager.organizationAdmin"]]
GCP.AuditLog: [bob@example.com] assigned admin privileges [["cat@example.com", "dog@example.com"]] to [["roles/resourcemanager.organizationAdmin", "roles/owner"]]
```
The query in gcp_data_model.py for `get_modified_users` and `get_iam_roles` are reversed, …

fix: user and roles query in GCP data model

---

.github/workflows/main.yml

There is a internal-to-panther github action which wasn't functioning correctly when forks were merged to master. 
A slight tweak on the `on.` settings on this workflow should enable this action to work in all scenarios. [This github actions document](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) describes the scenario, and we already had the additional checks recommended there to ensure that the pull_request had been closed-via-merge.

chore: workflow tweak to allow sync to dogfood for both forks and branches

---

global_helpers/panther_greynoise_helpers.py

This field should just be `last_seen` instead of `last_seen_timestamp` according to the [docs](https://docs.panther.com/enrichment/greynoise/basic-vs.-advanced#noise-dataset-1)
As it is currently written, this function will always return None.
* Changed L105 `last_seen_timestamp` -> `last_seen`

Remove _timestamp from last_seen Advanced Greynoise Object function

---

Pipfile
data_models/gcp_data_model.py
global_helpers/panther_oss_helpers.py

We want to remove all imports to panther_anlaysis_tool in detections.  This removes them with alternative solutions.
* alternative option for listify 
* convert PantherEvent to dict before using it in the gcp data model helpers
* `make test`
* upload

Remove pat imports

---

policies/aws_ec2_policies/aws_ec2_instance_detailed_monitoring.py
policies/aws_ec2_policies/aws_ec2_instance_detailed_monitoring.yml

A customer reported that EC2 Instance Detailed Monitoring detection had alerted for them on terminated instances. 
I added tests to cover the conditions, then modified the detection to accommodate.
* `make test`
**Before**
**After**

fix: detailed ec2 instance monitoring should only alert if an instance is Pending or Running

---

global_helpers/panther_greynoise_helpers.py

This reverts commit f86b06b429a8ca0c88fb5422cffa0f3081c8730c.
After deploying, we found evidence that this field is named with the underbar timestamp suffix. Reverting while we try to align documentation + reality. 
* 
*

Revert "bug: GreyNoise last_seen attribute had been referenced by a non-extant field name. update to an extant field (#486)

---

queries/snowflake_queries/snowflake_brute_force_ip_query.yml
queries/snowflake_queries/snowflake_brute_force_username_query.yml
queries/snowflake_queries/snowflake_key_user_password_login_query.yml
queries/snowflake_queries/snowflake_login_without_mfa_query.yml
queries/snowflake_queries/snowflake_network_policy_modified_query.yml
queries/snowflake_queries/snowflake_privileged_object_changes_query.yml
queries/snowflake_queries/snowflake_public_role_grant_query.yml
queries/snowflake_queries/snowflake_scim_token_created_query.yml
queries/snowflake_queries/snowflake_unusual_login_volume_query.yml
queries/snowflake_queries/snowflake_user_created_query.yml
queries/snowflake_queries/snowflake_user_enabled_query.yml

The double comma seems to be invalid syntax for our macro and keeps it from properly expanding. This causes issues when these queries are uploaded and the snowflake-admin api attempts to set things up

fix: remove double comma 😱

---

rules/gcp_audit_rules/gcp_gcs_iam_changes.yml
rules/gcp_audit_rules/gcp_gcs_public.yml
rules/gcp_audit_rules/gcp_iam_admin_role_assigned.yml
rules/gcp_audit_rules/gcp_iam_corp_email.yml
rules/gcp_audit_rules/gcp_iam_custom_role_changes.yml
rules/gcp_audit_rules/gcp_sql_config_changes.yml
rules/gcp_audit_rules/gcp_unused_regions.yml

Bug: GCP rules used p_any_ip_address instead of p_any_ip_addresses in summary field
Updated incorrect names

bugfix p_any_ip_address -> p_any_ip_addresses

---

README.md
rules/aws_cloudtrail_rules/aws_macie_evasion.py
rules/aws_cloudtrail_rules/aws_macie_evasion.yml
templates/example_rule.yml

Inspired by the [Sigma rule](https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws/aws_macic_evasion.yml) to detect if AWS Macie has been disabled or updated in a way to mask findings.
* AWS Macie Rule and Tests
* Locally and Unit Tests

[cloudtrail rules] AWS Macie Evasion

---

rules/aws_cloudtrail_rules/aws_waf_disassociation.yml

I was looking at the MITRE coverage and noticed that network DoS was uncovered, though this detection provides some coverage for T1498 
* 
*

fix: aws waf disassociation detects mitre technique T1498

---

Makefile
Pipfile.lock

CI runs and other workflows could install versions beyond what is specified in Pipfile.lock, because of the default behavior of `pipenv install` 
This change makes the default behavior of the tooling to be **install based on lockfile versions**
In order to bring upstream version updates, one will need to run `make deps-update` or `make pat-update` 
* The default installation behavior for python dependencies could potentially lead to version differences between the content used to validate the primary branch and subsequent actions taken when the source material is the primary branch. 
* make test

fix: Default behavior of our python environment should be to use the Pipfile.lock specified versions

---

Dockerfile
Makefile
Pipfile.lock
README.md

The basic make commands we provide don't easily work on Windows. And the `panther_analysis_tool` has trouble being installed on Windows too. By adding a docker file, Windows users that use docker can easily manage their workflows. 
The following is the intended usage
```
make docker-build
make docker-test # or lint or other commands we decide to support OOTB
```
* Added Dockerfile
* Updated Makefile with docker commands
* Updated pipfile lock
* Updated README with docker and windows instructions
* Tested by running the `make` commands locally on Mac and Windows machines

maxrichmond: docker support

---

global_helpers/global_helpers_test.py
global_helpers/panther_base_helpers.py

#546 demonstrates that `get_val_from_list()` global helper was not robust to the condition where the key whose value is being compared was absent from the item being iterated. 
* moves `get_val_from_list()` away from direct attribute assessment.
* `make global-helpers-unit-test`

fix: get_val_from_list would raise an error if the comparison key was not in the input item of the list

---

rules/aws_cloudtrail_rules/aws_console_login_without_mfa.py
rules/standard_rules/unusual_login_deprecated.py
rules/standard_rules/unusual_login_deprecated.yml

This changeset removes the remaining references to `ast.literal_eval` in favor of implementations that are more predictable, were they to receive hostile inputs.
* 
*

fix: remove all references to ast.literal_eval

---

rules/aws_cloudtrail_rules/aws_iam_user_key_created.py

I believe most operators would prefer to see the "this identity created IAM Keys for some other IAM User" grouped by the user doing the acting. 
* adds dedup() function to rules/aws_cloudtrail_rules/aws_iam_user_key_created.py
* make test

fix: dedup aws_iam_user_key_created based on the userIdentity.arn to group by source identity

---

.github/workflows/sync-from-upstream.yml

Updates the Sync upstream GitHub action in the following ways:
1.  Sync GH Action is now **enabled by default**
2. Adds a user-configurable local primary branch name ( i.e. folks that are using `main` ) as an ENV var at top-of-file. **defaults to master**
3. Runs on Tuesdays ( in case of Monday release cutting )
4. Updates outputs to use the new `$GITHUB_OUTPUT` env var instead of using [the to-be-deprecated set-output method](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
5. Error handling for **PR Already Exists For Latest Upstream Release**
6. Error handling for **Local Repo Already in Sync with Latest Upstream**
Errors should raise if other fault modes are encountered in the PR creation process
* test run in personal private …

fix: add some error handling to the sync action

---

packs/aws.yml

added the following already existing and now qa tested rules to prod:
AWS.KMS.CustomerManagedKeyLoss
AWS.Macie.Evasion
AWS.IPSet.Modified
AWS.Modify.Cloud.Compute.Infrastructure
AWS.CloudTrail.NetworkACLPermissiveEntry
AWS.IAM.PolicyModified
AWS.IAM.Backdoor.User.Keys
AWS.IAMUser.ReconAccessDenied
AWS.RDS.MasterPasswordUpdated
AWS.RDS.PublicRestore

adding qa'ed aws cloudtrail rules to prod

---

packs/aws.yml

added the following already existing rules from the aws cloudtrail ruleset to prod:
- AWS.CloudTrail.ResourceMadePublic
- AWS.Snapshot.Backup.Exfiltration
- AWS.CloudTrail.SnapshotMadePublic
- AWS.Suspicious.SAML.Activity
- AWS.IAM.CredentialsUpdated
- AWS.User.Login.Profile.Modified
- AWS.WAF.Disassociation
- AWS.S3.GreyNoiseActivity
- AWS.S3.BucketDeleted
- AWS.S3.BucketPolicyModified
- AWS.CloudTrail.SecurityConfigurationChange
- AWS.SecurityHub.Finding.Evasion
- AWS.CloudTrail.UnauthorizedAPICall

adding the final batch of qa tested already existing aws cloudtrail rules to prod

---

Pipfile
Pipfile.lock
global_helpers/global_helpers_test.py
global_helpers/panther_base_helpers.py
rules/aws_eks_rules/source_ip_multiple_403.py
rules/aws_eks_rules/source_ip_multiple_403.yml
rules/aws_eks_rules/system_namespace_public_ip.py
rules/aws_eks_rules/system_namespace_public_ip.yml

A global helper and two detections for EKS. 
Note: panther_analysis_tool of version 0.17.2 is required, and the Pipfiles have been updated to reflect this need.
Note: the audit logs don't include a cluster name.  So noting, we leverage `p_source_label` to indicate the originating cluster 
The detections:
1. A single, public sourceIP generates at least 10 403s over a 30 minute window. This potentially indicates Discovery is underway for [T1613 - Container and Resource Discovery](https://attack.mitre.org/techniques/T1613/)
2. `system:` or `eks:` users are acting from a public sourceIP. Note: this includes exceptions for `eks:addon-manager` and `eks:node-manager` 
*
* unit tests for global helper
* tests for logical branches in the new detections

feat: Initial Detections for EKS Audit logs

---

packs/github.yml
rules/aws_eks_rules/system_namespace_public_ip.py
rules/github_rules/github_secret_scanning_alert_created.py
rules/github_rules/github_secret_scanning_alert_created.yml

- New rule that detects when GitHub identifies a new secret
- Add this new rule to the pack
- Added existing Github rules that were missing from the pack
```
pipenv run panther_analysis_tool test --path rules/github_rules
...
GitHub.Secret.Scanning.Alert.Created
[PASS] GitHub detected a secret
[PASS] [title] Github detected a secret in acme-co/website (#1792)
[PASS] [dedup] Github detected a secret in acme-co/website (#1792)
[PASS] [alertContext] {"repo": "acme-co/website", "alert #": 1792, "url": "https://github.com/acme-co/website/security/secret-scanning/1792"}
[PASS] Unrelated
...
Path: rules/github_rules
Passed: 15
Failed: 0
Invalid: 0
```

Github: New Secret Scanning Rule & Update Pack

---

packs/aws.yml

added the following already existing rules to pack after qa: 
- AWS.GuardDuty.MediumSeverityFinding
- AWS.GuardDuty.LowSeverityFinding

adding qa tested aws guardduty rules to aws pack

---

rules/duo_rules/duo_user_action_fraudulent.py
rules/duo_rules/duo_user_action_fraudulent.yml

New Rule: DUO: User marked action as fraudulent
- New rule folder
- New rule and associated test
- `make fmt`
```
% pipenv run panther_analysis_tool test --path rules/duo_rules
[INFO]: Testing analysis items in rules/duo_rules
DUO.User.Action.Fraudulent
[PASS] user_marked_fraud
[PASS] [title] A DUO action was marked as fraudulent by example@example.io
[PASS] [dedup] A DUO action was marked as fraudulent by example@example.io
[PASS] [alertContext] {"factor": "duo_push", "reason": "user_marked_fraud", "user": "example@example.io", "os": "Mac OS X", "ip_access": "12.12.112.25", "ip_auth": "12.12.12.12", "application": "Slack"}
Path: rules/duo_rules
Passed: 1
Failed: 0
Invalid: 0
```

New Rule: DUO: User marked action as fraudulent

---

rules/aws_cloudtrail_rules/aws_saml_activity.py
rules/aws_cloudtrail_rules/aws_saml_activity.yml

We expect the service role for AWS SSO to be doing these SAML modification activities.
* Adds a quick escape for AWS.Suspicious.SAML.Activity if the originating role is the service role assumed by AWS SSO
* added additional test case for new logic.

fix: AWS SAML provisioning should be permitted by the service role for AWSSSO

---

rules/gsuite_activityevent_rules/gsuite_workspace_calendar_external_sharing.py
rules/gsuite_activityevent_rules/gsuite_workspace_calendar_external_sharing.yml

Gsuite workspace admins can change the default setting for sharing calendars to be outside of the gsuite domain. 
* make test
```shell
user@computer:panther-analysis $ pipenv run panther_analysis_tool test --filter RuleID=GSuite.Workspace.CalendarExternalSharingSetting
GSuite.Workspace.CalendarExternalSharingSetting
[PASS] Admin Set Default Calendar SHARING_OUTSIDE_DOMAIN Setting to READ_ONLY_ACCESS
[PASS] [title] GSuite workspace setting for default calendar sharing was changed by [example@example.io] from [DEFAULT] to [READ_ONLY_ACCESS]
[PASS] [dedup] GSuite workspace setting for default calendar sharing was changed by [example@example.io] from [DEFAULT] to [READ_ONLY_ACCESS]
[PASS] Admin Set Default Calendar SHARING_OUTSIDE_DOMAIN …
```

feat: Detection for Gsuite admin changing the workspace's calendar sharing setting to share outside of domain

---

packs/github.yml
rules/github_rules/github_organization_app_integration_installed.py
rules/github_rules/github_organization_app_integration_installed.yml

Added newly written rule to monitor activity related to installing a github organization application, fixed key ordering in pack file, referenced the rule ID in the github pack, and added global helper to pack.
* Test Cases Included in Yml file.
* results linked below: (updated to include bracketed interpolated values in results)

New Github Organization Application Installation Rule

---

packs/github.yml
rules/github_rules/github_public_repository_created.py
rules/github_rules/github_public_repository_created.yml

Added newly created rule to monitor and alert when a public github repo gets created inside of an organization
* Results linked below:
*

New Github Public Repo Creation Rule

---

rules/gsuite_activityevent_rules/gsuite_external_forwarding.yml
rules/gsuite_activityevent_rules/gsuite_workspace_gmail_default_routing_rule.py
rules/gsuite_activityevent_rules/gsuite_workspace_gmail_default_routing_rule.yml
rules/gsuite_activityevent_rules/gsuite_workspace_gmail_enhanced_predelivery_scanning.py
rules/gsuite_activityevent_rules/gsuite_workspace_gmail_enhanced_predelivery_scanning.yml
rules/gsuite_activityevent_rules/gsuite_workspace_trusted_domains_allowlist.yml

Some Gsuite detections for Gmail
1. on modification of Default Routing Rules
2. If pre-delivery scanning is disabled 
* 
```shell
user@computer:panther-analysis $ pipenv run panther_analysis_tool test --filter RuleID=GSuite.Workspace.GmailDefaultRoutingRuleModified
GSuite.Workspace.GmailDefaultRoutingRuleModified
[PASS] Workspace Admin Creates Default Routing Rule
[PASS] [title] GSuite Gmail Default Routing Rule Was [created] by [user@example.io]
[PASS] [dedup] GSuite Gmail Default Routing Rule Was [created] by [user@example.io]
[PASS] Workspace Admin Deletes Default Routing Rule
[PASS] [title] GSuite Gmail Default Routing Rule Was [deleted] by [user@example.io]
[PASS] [dedup] GSuite Gmail Default Routing Rule Was …
```

feat: Gsuite Gmail detections for when admins modify  DefaultRoutingRules and Disable Pre-Delivery Scanning

---

packs/github.yml
rules/github_rules/github_repository_transfer.py
rules/github_rules/github_repository_transfer.yml

* adding newly created rule to monitor and alert on github repository transfer events
*

Newly Created Github Rule to Monitor Repository Transfers

---

packs/atlassian.yml
rules/atlassian_rules/user_logged_in_as_user.py
rules/atlassian_rules/user_logged_in_as_user.yml

Detects the `user_logged_in_as_user` event. Atlassian admins can impersonate another non-admin user account on a per-application (Jira, Confluence, etc.) basis. This detection runs at the Atlassian admin level but does not call out which application the admin looking at when impersonating another user.
Created a new Atlassian Pack, `packs/atlassian.yml` to support this new detection. 
[Atlassian docs](https://support.atlassian.com/user-management/docs/log-in-as-another-user/)
* Adds an Atlassian rule to detect `logged_in_as_user.
* Adds a Pack for Atlassian. 
```
[INFO]: Testing analysis items in rules/atlassian_rules
Atlassian.User.LoggedInAsUser
[PASS] Admin impersonated user successfully
[PASS] [title] example.admin@example.com logged in as example.user@example.io. …
```

Atlassian user logged in as user

---

rules/microsoft_rules/microsoft_graph_passthrough.py

We received reports that the INFO severity passthrough was not functional due to a spelling mismatch.  cc/ @hbenac10 
* 
*

fix: msft365 spells INFO severity as informational

---

rules/aws_s3_rules/aws_s3_bucket_defacement_attempt.py
rules/aws_s3_rules/aws_s3_bucket_defacement_attempt.yml

note: this PR is back to the originating branch for this detection 
modifies detection for sensitive S3 operations. 
This detection first compares the `event` to an exclude list. If the event passes the exclude list filter, then the event is compared to an include list. 
*
* 
```shell
(panther-analysis) user@computer:~/Sources/PAN/panther-analysis $ pipenv run panther_analysis_tool test --filter RuleID=AWS.S3.Defacement.Attempt 
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
[INFO]: Testing analysis items …
```

chore: restructure the S3 bucket defacement rule to pass cylcocomplexity checks and restructure tests to logical boundaries

---

rules/github_rules/github_advanced_security_change.py
rules/github_rules/github_advanced_security_change.yml

A user mentioned getting an alert with a title mentioning GitHub Advanced Security, yet they did not subscribe to the Advanced Security feature in GitHub.  
The inclusion of the word `Advanced` in the title of the alert is now conditional on the event falling under the [rules on this page from docs.github.com](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security#about-advanced-security-features). Sadly that page doesn't mention audit log event names, so it's possible we'll miss on the inclusion or exclusion of that text in some cases. 
When investigating this, I also uncovered [this docs page]( https://github.com/github/docs/blob/main/content/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-you …

fix: github_advanced_security detection had some confusing title text

---

rules/aws_cloudtrail_rules/aws_iam_user_recon_denied.yml

We've observed that this is a very chatty alert in several environments. Since this is a risk-ranking signal alert without a strong call to action behind it, it makes sense to have the severity be Info. 
* 
*

fix: tune aws_iam_user_recon_denied down to Info level

---

packs/aws.yml
rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.yml

This detection was observed to be emitting alerts with high frequency in several environments.  To remediate, we are setting this detection to have a default state of `Enabled: false` and we're additionally setting the default severity to `Medium`.
*
*

fix: set default state to disable for aws_modify_cloud_compute_infra. change severity to Medium. remove from AWS pack

---

packs/aws.yml
rules/aws_cloudtrail_rules/aws_snapshot_backup_exfiltration.yml

aws_snapshot_backup_exfiltration was alerting on any `ec2:ModifySnapshotAttribute` change. This detection has been deprecated in favor of the overlapping and more specific snapshot modification details inspected in aws_snapshot_made_public 
* 
*

fix: deprecates aws_snapshot_backup_exfiltration in favor of aws_snapshot_made_public

---

rules/gsuite_reports_rules/gsuite_drive_visibility_change.py
rules/gsuite_reports_rules/gsuite_drive_visibility_change.yml

GSuite.DriveVisibility needs configuration, which was made more clear in #618. 
I believe this detection needed a few more tweaks to make its behavior more clear. I have updated the thing called `EXCLUDED_DOMAINS` to be called `ALLOWED_DOMAINS`.
I have also updated the detection to have the empty set as the default value for the domain allow-list, and updated test fixtures to use Mock facilities to both demonstrate that historical behavior has been maintained in the event that configuration is applied
* 
*

fix: update GSuite.DriveVisibility to more explicitly demonstrate that it needs configuration

---

rules/aws_eks_rules/source_ip_multiple_403.py
rules/aws_eks_rules/source_ip_multiple_403.yml

There are many naive web-scanners scanning EKS kube-api endpoints hosted in AWS ( checking things like `/phpinfo.php` `/cgi-bin/` ). 
It makes sense to me that we should ignore those types of scanners.. Since all kube api server endpoints begin the requestURI with either `/api/` or `/apis/` , we can leverage `string.startswith()` to do some (naive) exclusion filtering for this alert. 
* 
*

fix: eks_source_ip_multiple403s was triggering on naive web-scanners. so many naive web scanners.

---

packs/aws.yml

* pushing already existing and tested policies into prod for the policies->packs work
* added:  
- AWS.Modify.Cloud.Compute.Infrastructure
- AWS.PasswordPolicy.PasswordReuse
- AWS.ACM.Certificate.Expiration
- AWS.CloudFormation.Stack.Drifted
- AWS.CloudFormation.Stack.UsesIAMServiceRole
- AWS.CloudFormation.Stack.TerminationProtection
- AWS.CloudWatchLogs.DataRetention1Year
- AWS.CloudWatchLogs.Encrypted
- AWS.Config.RecordAllResourceTypes
- AWS.Config.GlobalResources
- AWS.DynamoDB.Autoscaling

fix: adding already existing and tested policies to aws pack in prod 

---

Pipfile
Pipfile.lock

panther_analysis_tool zip behavior has been updated
GitPython has a vuln that needs addressing
* 
```shell
(panther-analysis) user@computer:~/Sources/PAN/panther-analysis $ pip show panther-analysis-tool | sed -e '/^Location/d' 
Name: panther-analysis-tool
Version: 0.19.0
Summary: Panther command line interface for writing, testing, and packaging policies/rules.
Home-page: https://github.com/panther-labs/panther_analysis_tool
Author: Panther Labs Inc
Author-email: pypi@runpanther.io
License: AGPL-3.0
Requires: aiohttp, boto3, dynaconf, gql, jsonlines, jsonpath-ng, panther-core, requests, ruamel.yaml, schema, semver, typing-extensions
Required-by: 
(panther-analysis) user@computer:~/Sources/PAN/panther-analysis $ pip show GitPython | sed -e '/^Location/d'      
Name: GitPython
Version: …
```

chore: update panther_analysis_tool and GitPython

---

Pipfile
Pipfile.lock

panther_analysis_tool v0.19.1 has a bugfix relating to bulk-upload which we want to bring into this repo. 
* 
```shell
(panther-analysis) user@computer:~/Sources/PAN/panther-analysis $ pipenv run panther_analysis_tool --version | pbcopy 
panther_analysis_tool 0.19.1
```

feat: update panther_analysis_tool to v0.19.1, which has a bulk-upload bugfix that is important

---

packs/zoom.yml
rules/zoom_operation_rules/zoom_all_meetings_secured_with_one_option_disabled.py
rules/zoom_operation_rules/zoom_all_meetings_secured_with_one_option_disabled.yml

* extending zoom pack with new rule
*

new rule: alerts when zoom user toggles Require that all meetings are secured with one security option: from On to Off

---

global_helpers/panther_oss_helpers.py

- DynamoDB caching enables stateful detections in Panther. This PR adds the `put_dictionary()` and `get_dictionary()` methods as helper functions in `panther_oss_helpers`.
- With the code introduced in this PR, detection writers can send `string` keys and `dict` values to `put_dictionary()` in the same way they can send string sets to `put_string_set()`.
- This eliminates the need for detection writers to serialize and deserialize dictionaries. 
- Added `put_dictionary()` and `get_dictionary()` into `panther_oss_helpers`
- Tests were conducted in an internal Panther instance leveraging Unit Tests via the Panther console

Added support for dictionary values in DynamoDB

---

Pipfile
rules/standard_rules/brute_force_by_ip.yml

standard_rule/brute_force_by_ip detects failed logon attempts for various services. 
This detection had a relatively low threshold of detection ( 5 events in a 60 minute period ). 
This detection doesn't have a particularly prescriptive call to action, and as such moving severity from Medium to Info. 
* 
*

tune: standard_rule/brute_force_by_ip

---

Pipfile
Pipfile.lock

panther_analysis_tool version update was needed for supporting some new snyk logs
* 
```shell
user@computer:~/Sources/PAN/panther-analysis $ pipenv run panther_analysis_tool --version
panther_analysis_tool 0.19.5
```

fix: bump panther_analysis_tool to 0.19.5 for some additional snyk logs

---

rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.py
rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.yml

AWS Config can run the `ec2:DescribeTrafficMirroring`, which we should not raise an alert upon. Some other EC2 
I believe there are fewer pathways to initiating the TrafficMirroring calls, and so am not recreating the full list in [the other ec2 modification](https://github.com/panther-labs/panther-analysis/blob/master/rules/aws_cloudtrail_rules/aws_ec2_monitoring.py#L27) detection
* 
```shell
AWS.EC2.Traffic.Mirroring
[PASS] CreateTrafficMirrorFilter
[PASS] [title] arn:aws:sts::123123123123:assumed-role/MakeStuffPublic ec2 activity found for CreateTrafficMirrorFilter in account 123451234515 in region us-east-1.
[PASS] [dedup] arn:aws:sts::123123123123:assumed-role/MakeStuffPublic
[PASS] [alertContext] {"eventName": "CreateTrafficMirrorFilter", "eventSource": …
```

chore: tune out aws config checking on ec2 traffic mirroring

---

Pipfile

Relates to https://github.com/panther-labs/panther_analysis_tool/releases/tag/v0.19.6
* Bumps `panther-analysis-tool` requirement to `0.19.6`
* `make install` and `make test` succeed locally

Bump PAT version to 0.19.6

---

Pipfile.lock

`Pipfile.lock` needed to updated in #684
* Updated `Pipfile.lock` via `pipenv install --dev panther-analysis-tool`
```sh
$ source /Users/evangibler/.local/share/virtualenvs/panther-analysis-xBQFy9Wh/bin/activate.fish
$ panther_analysis_tool --version
panther_analysis_tool 0.19.6
```

Update Pipefile.lock for PAT 0.19.6

---

rules/slack_rules/slack_user_privilege_escalation.py
rules/slack_rules/slack_user_privilege_escalation.yml

When looking for an example detection I noticed that the description for slack_user_privilege_escalation was inaccurate. This PR fixes that along with making the titles more expressive. 
Also fixes a TODO item which elevates the severity level if admin/owner permissions is granted or ownership is transferred/granted to a critical severity. 
* Fixes description of the detection 
* Makes titles more expressive passing the affected user. 
* Increases severity to critical if admin/owner is granted or ownership is transferred/grante.
```
Slack.AuditLogs.UserPrivilegeEscalation
[PASS] Owner Transferred
[PASS] [title] Slack Owner Transferred from username (user@example.com)
[PASS] [dedup] Slack Owner Transferred from username (user@example.com)
[PASS] [alertContext] …
```

Refactor: slack_user_privilege_escalation

---

rules/dropbox_rules/dropbox_linked_team_application_added.py
rules/dropbox_rules/dropbox_linked_team_application_added.yml

This is an initial `Dropbox.TeamEvent` rule, specifically for an app being linked to a team.
The rule looks for:
- an `event_type` of `app_link_team`
- an `event_description` of `Linked app for team`
The base alert severity is `LOW`, though `HIGH` is returned if a non-team member is involved.
* Adds a `Dropbox.Linked.Team.Application.Added` rule
* Adds three accompanying tests:
* Positive test case for `LOW` severity
* Positive test case for `HIGH` severity
* Negative test case
```sh
Dropbox.Linked.Team.Application.Added
[PASS] Test-5f682
[PASS] [title] Dropbox Team Member Linked App by [user_name]
[PASS] [dedup] Dropbox Team Member Linked App by [user_name]
[PASS] [alertContext] {"additional_user_details": {"account_id": "dbid:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", …
```

Add Dropbox Team Member Linked App Rule

---

global_helpers/global_filter_cloudflare.py
global_helpers/global_filter_cloudflare.yml
packs/cloudflare.yml
rules/cloudflare_rules/cloudflare_firewall_ddos.py
rules/cloudflare_rules/cloudflare_firewall_ddos.yml
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked.py
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.py
rules/cloudflare_rules/cloudflare_firewall_suspicious_event_greynoise.py
rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.py
rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume_greynoise.py
rules/crowdstrike_rules/crowdstrike_detection_passthrough.py
rules/crowdstrike_rules/crowdstrike_dns_request.py

This PR introduces a global filter function for cloudflare events which users can modify to incorporate the local considerations for which events to include and exclude for rule processing.  I believe this approach of establishing a single module that includes a single filtering function incorporated into all detections for a given LogType will provide a way for users to define include/exclude filters for detections without also needing to consider the implications of future merge conflicts. 
I added a test case on rules/cloudflare_rules/cloudflare_firewall_ddos.yml called `Traffic Marked as L7DDoS but blocked ( INFO level alert ) WITH FILTER` which demonstrates the effect of a customer giving a custom definition to the global filter.  There is no special unittest case handling needed …

feat: logtype global filter for cloudflare events

---

Pipfile
Pipfile.lock

backend has been updated to policyuniverse 1.5.0.20220613
* Updates pip deps to synchronize policyuniverse versions
* `make test`

fix: sync policyuniverse version to backend

---

.github/release.yml

GitHub releases can honor an in-repo [release.yml](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) file when represent. 
In-repo releases work based on PR tags, so the following are the rules as I anticipate them
* `tuning` -> Goes into its own section, without regard to what it is that is being tuned.  ( appears at end of release notes )
* `rules` -> Means new rules are in the PR.
* `policies` -> Means new policies are in the PR 
* `queries` -> means new queries are in the PR
* `scheduled_rules` -> means new scheduled_rules are in the PR 
* `bugs` -> Equivalent to `tuning`
* `Anything Else` -> Goes into Miscellaneous 
* creates release notes template
*

chore: let automagic release note generation do more for us 

---

rules/gsuite_activityevent_rules/gsuite_google_access.yml

This detection spelled resource as reource
* 
*

chore: typo in the word resource

---

queries/snowflake_queries/snowflake_brute_force_ip_query.yml
queries/snowflake_queries/snowflake_brute_force_username_query.yml
queries/snowflake_queries/snowflake_login_without_mfa_query.yml

As part of the snowflake initiative, we are working to update current snowflake queries in an effort to strengthen query logic and ensure compatibility with our backend and customer environments, as well as add functionality in areas where logic has yet to cover. This PR is the first to be put out for this initiative, and focuses on queries dependent on the login_history table.
* The following three queries: 
snowflake_brute_force_ip_query.yml
snowflake_brute_force_username_query.yml
snowflake_login_without_mfa_query.yml
have all been updated to contain additional logical constraints. This is to ensure the limiting of results to only relevant events. 
* The queries have been run both in king of spades and within our backend snowflake instance and have been confirmed to return the same …

Reconfiguring login_history snowflake table dependent queries.

---

rules/snyk_rules/snyk_system_policysetting.py
rules/snyk_rules/snyk_system_policysetting.yml

Snyk [Policies](https://snyk.io/learn/security-policies/) define license and other security boundaries within the Snyk product. 
* adds detections that look for Snyk policy CRUD operations
```shell
Snyk.System.PolicySetting
[PASS] Snyk System Policy Setting event happened ( Security Policy )
[PASS] [title] Snyk: System [security] Policy Setting event [group.policy.create] performed by [05555555-3333-4ddd-8ccc-755555555555]
[PASS] [dedup] 05555555-3333-4ddd-8ccc-755555555555<NO_GROUPID>8fffffff-1555-4444-b000-b5555555555521111111-a222-4eee-8ddd-a99999999999
[PASS] [alertContext] {"actor": "05555555-3333-4ddd-8ccc-755555555555", "action": "group.policy.create", "orgId": "<NO_ORGID>", "groupId": "8fffffff-1555-4444-b000-b55555555555", "policy_type": "security"}
[PASS] Snyk …
```

feat: Snyk rules for policy settings

---

rules/aws_cloudtrail_rules/aws_ipset_modified.py
rules/aws_cloudtrail_rules/aws_ipset_modified.yml
rules/aws_cloudtrail_rules/aws_rds_publicrestore.py

Relates to: https://panther-labs.slack.com/archives/C026QGU2UG4/p1680127316947879
* Updates spelling from `recepientAccountId` to `recipientAccountId`
Tests pass:
```
AWS.IPSet.Modified
[PASS] CreateIPSet Event
[PASS] [title] IPSet was modified in []
[PASS] [dedup] IPSet was modified in []
[PASS] [alertContext] {"eventName": "CreateIPSet", "eventSource": "guardduty.amazonaws.com", "awsRegion": "us-east-1", "recipientAccountId": "<MISSING_ACCOUNT_ID>", "sourceIPAddress": "<MISSING_SOURCE_IP>", "userAgent": "<MISSING_USER_AGENT>", "userIdentity": "<MISSING_USER_IDENTITY>"}
[PASS] UpdateIPSet
[PASS] [title] IPSet was modified in []
[PASS] [dedup] IPSet was modified in []
[PASS] [alertContext] {"eventName": "CreateIPSet", "eventSource": …
```

Update event spelling for aws_ipset_modified and aws_rds_publicrestore

---

queries/crowdstrike_queries/CrowdStrike_Large_Zip_Creation_FDREvent.yml

context: https://app.asana.com/0/1200908948600035/1204323874535604/1204325835161944/f
quick fix for missed double table mention in file 

query fix: fqtn

---

rules/snyk_rules/snyk_ou_change.py
rules/snyk_rules/snyk_ou_change.yml
rules/snyk_rules/snyk_system_externalaccess.py
rules/snyk_rules/snyk_system_externalaccess.yml
rules/snyk_rules/snyk_system_policysetting.py

Detections for some Snyk changes
* OU Changes ( several )
* Setting that allows Snyk users external to the Org/Group access to the group/org projects
There's also a typo fix in dedup on `Snyk.System.PolicySetting`, which should be a no-op. 
```shell
Snyk.OU.Change
[PASS] Snyk Org Deletion ( HIGH )
[PASS] [title] Snyk: [Org] Organizational Unit settings have been modified via [org.delete] performed by [05555555-3333-4ddd-8ccc-755555555555]
[PASS] [dedup] 05555555-3333-4ddd-8ccc-75555555555521111111-a222-4eee-8ddd-a999999999998fffffff-1555-4444-b000-b55555555555org.delete
[PASS] [alertContext] {"actor": "05555555-3333-4ddd-8ccc-755555555555", "action": "org.delete", "orgId": "21111111-a222-4eee-8ddd-a99999999999", "groupId": "8fffffff-1555-4444-b000-b55555555555"}
[PASS] …
```

feat: Snyk detections for OU changes and external access changes

---

.vscode/settings.json
lookup_tables/greynoise/advanced/noise_advanced.yml
lookup_tables/greynoise/advanced/riot_advanced.yml
lookup_tables/greynoise/basic/noise_basic.yml
lookup_tables/greynoise/basic/riot_basic.yml

The audit logs for Panther Console was left out of the mappings for the Greynoise lookup tables. This PR adds them in!
Updated the Greynoise .yml files with the appropriate metadata.

Adding Panther.Audit to the Greynoise LUTs

---

policies/aws_load_balancer_policies/aws_alb_ssl_policy.py
policies/aws_load_balancer_policies/aws_alb_ssl_policy.yml

AWS Released support for using TLS 1.3 with AWS ELBs. This PR adds acknowledgment to `AWS.ELBv2.SSLPolicy` for the new TLS1.3 SSL Policy. 
**After this change**
Test output from this change  with supporting test case 
```shell
AWS.ELBv2.SSLPolicy
[PASS] Strong Ciphers Internet Facing
[PASS] [policy] true
[PASS] Default Ciphers
[PASS] [policy] false
[PASS] [dedup] defaultDedupString:AWS.ELBv2.SSLPolicy
[PASS] Default Ciphers Internal Load Balancer
[PASS] [policy] true
[PASS] Observed - No Listeners len() issue
[PASS] [policy] false
[PASS] [dedup] defaultDedupString:AWS.ELBv2.SSLPolicy
[PASS] TLS 1.3 listeners
[PASS] [policy] true
Path: .
Passed: 1
Failed: 0
Invalid: 0
```
---
**Before the change** …

fix: AWS ELBs now have TLS 1.3 SSL Policies

---

rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.py

missing event in deep_get

---

rules/zoom_operation_rules/zoom_operation_passcode_disabled.py
rules/zoom_operation_rules/zoom_operation_passcode_disabled.yml

When handling `Add` and `Delete` events, the `zoom_operation_passcode_disabled`
rule causes a run-time `KeyError` when attempting to access `"Change"`.
* Safely access `Change` and `DisabledSetting`. This seemed safer than filtering
only for `Update` events, but I'm happy to refactor and take that approach as
well.
* N/A

Safely handle Zoom user group context

---

global_helpers/global_filter_snyk.yml

My expectation is that this change would not have any impact in forks or private copies. 
* There was a typo in the yml file that describes the global filter for Snyk detections.

chore: there was a little copy-pasta in the global filter yaml file for Snyk

---

global_helpers/global_filter_tines.py
global_helpers/global_filter_tines.yml
global_helpers/global_helpers_test.py
global_helpers/panther_tines_helpers.py
global_helpers/panther_tines_helpers.yml
packs/tines.yml
rules/tines_rules/tines_sso_settings.py
rules/tines_rules/tines_sso_settings.yml

Tines.Audit logtype is in beta and here is the initialization of detections using this log type.
This change request adds
1. a rule for SSO settings being changed
2. a pack to group the rule(s)
3. global filters for tines to include/exclude tenants ( or whatever your criteria may be )
4. a global helper that provides alert_context for Tines detections
```text
Tines.SSO.Settings
[PASS] Tines SsoConfigurationSamlSet
[PASS] [title] Tines: [SsoConfigurationSamlSet] Setting changed by [user@company.com]
[PASS] [dedup] 17171_SsoConfigurationSamlSet
[PASS] [alertContext] {"actor": "user@company.com", "action": "SsoConfigurationSamlSet", "tenant_id": "8888", "user_email": "user@company.com", "user_id": "17171", "operation_name": "SsoConfigurationSamlSet", "request_ip": …
```

feat: Tines.Audit detections and pack

---

global_helpers/global_helpers_test.py
global_helpers/panther_snyk_helpers.py

Snyk audit logs log user by user_id, which is great. Being able to quickly get to which user is referred to by a user_id is also great, and this PR extends the Snyk alert_context helper to include a full url that identifies the user. 
Here's an example of `actor_link` in the `Snyk.Misc.Settings` detection. 
```text
Snyk.Misc.Settings
[PASS] Snyk Feature Flags changed
[PASS] [title] Snyk: [Group] Setting [Feature_Flags.Edit] performed by [05555555-3333-4ddd-8ccc-755555555555]
[PASS] [dedup] 05555555-3333-4ddd-8ccc-75555555555521111111-a222-4eee-8ddd-a999999999998fffffff-1555-4444-b000-b55555555555group.feature_flags.edit
[PASS] [alertContext] {"actor": "05555555-3333-4ddd-8ccc-755555555555", "action": "group.feature_flags.edit", "orgId": …
```

chore: add a clickable link to snyk alert context to identify users

---

packs/credential_security.yml

Creating a pack for rules (and associated data models & globals) related to credential security.
* Added a new `Credential Security` pack
* I manually checked each rules imports to ensure all globals were covered, and manually checked the standard rule's log types to ensure data models were covered

Adding credential security pack

---

Pipfile
Pipfile.lock

panther_analysis_tool version 0.22.2 includes support for  `MongoDB.OrganizationEvent` and `MongoDB.ProjectEvent` LogTypes

chore: update panther_analysis_tool to 0.22.2 

---

rules/okta_rules/okta_geo_improbable_access.py
rules/onelogin_rules/onelogin_high_risk_login.py
rules/slack_rules/slack_application_dos.py

These detections explicitly cast their cache TTLs to string. Dynamodb is kind enough to accept entry-specific data types on each document, and dynamodb's behavior when the TTL column is a string is [to ignore the value and not enforce the expiration](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-before-you-start.html#time-to-live-ttl-before-you-start-formatting). 
A future change will typecast the epoch_seconds kwarg to `int` inside  `panther_oss_helpers.set_key_expiration()`

fix: some cache ttls were getting stringified, which leads to dynamodb silently not expiring them

---

data_models/aws_cloudtrail_data_model.py
data_models/aws_cloudtrail_data_model.yml
global_helpers/global_helpers_test.py
global_helpers/panther_oss_helpers.py
rules/standard_rules/impossible_travel_login.py
rules/standard_rules/impossible_travel_login.yml

Panther can leverage IPInfo based location data to make impossible travel computations for any log source. This detection is setup only for `AWS.CloudTrail` log type in this PR, and if we like this approach we can readily extend it to other LogTypes
This PR:
1. Creates `panther_oss_helpers.km_between_ipinfo_loc()` which uses the Haversine formula to find the distance between two ipinfo location entries as measured in kilometers
2. Creates unit test cases for ☝️ 
3. Establishes a detection leveraging the above which caches IPInfo location information for login events, and compares incoming login events against the cache. 
```text
Standard.ImpossibleTravel.Login
[PASS] CloudTrail not ConsoleLogin
[PASS] CloudTrail ConsoleLogin no history
[PASS] …
```

feat: a generic approach to impossible travel for login style events

---

rules/snyk_rules/snyk_user_mgmt.py
rules/snyk_rules/snyk_user_mgmt.yml

This change modifies the `Snyk.User.Management` detection so that there is no alert when users are added to Snyk via SAML sign-in
```text
Snyk.User.Management
[PASS] Snyk User Removed
[PASS] [title] Snyk: [Org] User [Remove] performed by [05555555-3333-4ddd-8ccc-755555555555]
[PASS] [dedup] 05555555-3333-4ddd-8ccc-75555555555521111111-a222-4eee-8ddd-a999999999998fffffff-1555-4444-b000-b55555555555org.user.remove
[PASS] [alertContext] {"actor": "05555555-3333-4ddd-8ccc-755555555555", "action": "org.user.remove", "orgId": "21111111-a222-4eee-8ddd-a99999999999", "groupId": "8fffffff-1555-4444-b000-b55555555555", "actor_link": "https://app.snyk.io/group/8fffffff-1555-4444-b000-b55555555555/manage/member/05555555-3333-4ddd-8ccc-755555555555"}
[PASS] [severity] MEDIUM
[PASS] …
```

fix: When Snyk users are added via SAML, the userId on the audit log entry is the same as the userid of the added user

---

data_models/okta_data_model.py
data_models/okta_data_model.yml
packs/standard_ruleset.yml
rules/standard_rules/impossible_travel_login.yml

Standard.ImpossibleTravel.Login is now extended to include Okta.SystemLog. 
Additionally, this detection is now included in the Standard pack 
```text
Standard.ImpossibleTravel.Login
[PASS] CloudTrail not ConsoleLogin
[PASS] CloudTrail ConsoleLogin no history
[PASS] CloudTrail ConsoleLogin with history
[PASS] [title] Impossible Travel: [tester] in [LogSource Name] went [7098] km/h for [14197] km between [New York City] and [Auckland]
[PASS] [dedup] LogSourceName..tester
[PASS] [alertContext] {"actor_user": "tester", "previous": {"p_event_time": "2023-05-26 18:14:51", "city": "New York City", "country": "US", "lat": "40.71427", "lng": "-74.00597", "postal_code": "10004", "region": "New York", "region_code": "NY", "timezone": …
```

feat: extend the Standard.ImpossibleTravel.Login detection to include Okta.SystemLog

---

packs/cloudflare.yml
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked.yml
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.yml
rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.yml
rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume_greynoise.yml

`Cloudflare.HttpRequest.BotHighVolume` detection had thresholding settings that worked out to one request every six seconds. This change tunes the alert volume of requests up to 2req/sec. Googlebot reports that 2 req/sec is the "HIGH" setting. 
We also have disabled-by-default 2 cloudflare detections which surfaced alerts when Cloudflare has blocked traffic. These disabled detections were also removed from the cloudflare pack. 
*  No testing changes needed.

fix: Tune cloudflare bot alert up to 2req/sec. Disable some cloudflare blocked alerts due to cloudflare having blocked the request

---

rules/standard_rules/impossible_travel_login.py
rules/standard_rules/impossible_travel_login.yml

It's helpful for responders to have the units of measurement in the alert context and in the title. 
This PR also adds a link in the detection's runbook for how to inform IPInfo that an address has been incorrectly geolocated, should a user report that they are indeed not in some distant geography relative to their last login.

chore: add units to alert_context on standard impossible travel

---

global_helpers/gcp_base_helpers.py
rules/gcp_audit_rules/gcp_dns_zone_modified_or_deleted.py
rules/gcp_audit_rules/gcp_dns_zone_modified_or_deleted.yml

This PR adds detections for create, delete, patch, and update operations on GCP DNS zones. 
While the initial detection spec did not explicitly define `create` as a case, I opted to add it in as a match condition because the initial `update` example contained logs for a zone creation.
- Adds a detection rule for the following methods:
- `dns.changes.create`
- `dns.managedZones.delete`
- `dns.managedZones.patch`
- `dns.managedZones.update`
- Adds four unit tests
- Three `True`
- One `False`
- Tests pass as expected:
```
GCP.DNS.Zone.Modified.or.Deleted
[PASS] dns.managedZones.delete-should-alert
[PASS] [title] staging@pantherstaging.io performed dns.managedZones.delete on managedZones/test-zone
[PASS] [dedup] staging@pantherstaging.io performed dns.managedZones.delete on …
```

Add detections for GCP DNS zone operations

---

rules/gcp_audit_rules/gcp_dns_zone_modified_or_deleted.py
rules/github_rules/github_org_moderators_add.py
rules/github_rules/github_org_moderators_add.yml

Detection for adding a member to organization moderators.
```
GitHub.Org.Moderators.Add
[PASS] GitHub - Org Moderator Added
[PASS] [title] GitHub.Audit: User [sarah78] added user [john1987] to moderators in [example-io]
[PASS] [dedup] GitHub.Audit: User [sarah78] added user [john1987] to moderators in [example-io]
[PASS] [alertContext] {"action": "organization_moderators.add_user", "actor": "sarah78", "actor_location": "US", "org": "example-io", "repo": "", "user": "john1987"}
[PASS] GitHub - Org Moderator removed
```
* https://github.com/panther-labs/panther-analysis/actions/runs/5249536162/jobs/9482440906#step:8:4401

add: github rule add org moderator

---

packs/aws.yml

Deprecated dynamo db encryption policy removed from pack

remove dynamo encryption policy from pack

---

rules/gcp_audit_rules/gcp_dns_zone_modified_or_deleted.py
rules/gcp_audit_rules/gcp_firewall_rule_modified.py
rules/gcp_audit_rules/gcp_firewall_rule_modified.yml

This PR adds a detection for GCP firewall modification events. Rather than explicitly defining a tuple of firewall update-related methods, the rule uses a regex search with enough guardrails to lower the SNR of the rule (i.e., it should not evaluate to `True` on every firewall method or any other method).
Essentially, any service prefix before `v1` is allowed, but after that, only `Firewall.Update`, `compute.firewalls.patch`, or `compute.firewalls.update` methods are valid.
* Adds `gcp_firewall_rule_modified.py`
* Adds `gcp_firewall_rule_modified.yml` with three `True` test cases and one `False` test cases
```
GCP.Firewall.Rule.Modified
[PASS] compute.firewalls.update-should-alert
[PASS] [title] [GCP] user@domain.com performed …
```

Create detection for GCP firewall rule modifications

---

packs/notion.yml
rules/notion_rules/notion_workspace_audit_log_exported.py
rules/notion_rules/notion_workspace_audit_log_exported.yml

Detection to alert when the Notion audit log is exported.
* Adds `rules/notion_rules/notion_workspace_audit_log_exported.py` and  `rules/notion_rules/notion_workspace_audit_log_exported.yml`
* Added tests for not triggering and triggering the detection.

feat: Notion audit log exported detection

---

packs/notion.yml
rules/notion_rules/notion_many_pages_deleted.py
rules/notion_rules/notion_many_pages_deleted.yml

[<High level overview here>](https://www.notion.so/pantherlabs/Hackathon-notion-many-pages-deleted-fe435022aa39491a937ae07827327b47)
```
Notion.Many.Pages.Deleted
[PASS] Many Pages Deleted
[PASS] [title] Notion User [homer.simpson@yourcompany.io] deleted multiple pages with page ids [93cf05d3-6805-4ddc-abba-adsfjhnlkwje785].
[PASS] [dedup] Notion User [homer.simpson@yourcompany.io] deleted multiple pages with page ids [93cf05d3-6805-4ddc-abba-adsfjhnlkwje785].
[PASS] [alertContext] {"actor": {"id": "af06b6ff-dd5e-4024-b9ef-78fe77f55884", "object": "user", "person": {"email": "homer.simpson@yourcompany.io"}, "type": "person"}, "action": "page.deleted"}
```

add: notion rule many pages deleted

---

rules/gcp_audit_rules/gcp_firewall_rule_created.py
rules/gcp_audit_rules/gcp_firewall_rule_created.yml

Similar to #785, this PR adds a detection for GCP firewall rule creations. The method pattern for this rule specifies `Create` and `insert` for the methods.
I also wanted to point out the distinction between `compute.firewalls.insert` and `compute.firewalls.patch`:
```
Creates a firewall rule in the specified project using the data included in the request...
```
versus:
```
Updates the specified firewall rule with the data included in the request...
```
Given the verbiage, I opted to only include `insert` as part of this PR since `patch` is covered in the aforementioned PR.
The title code for this detection is a little more granular since a Compute Engine firewall rule will return a rule ID whereas an App Engine firewall rule will not return a rule ID, so in those cases the actual …

Add detection for GCP firewall rule creations

---

rules/gcp_audit_rules/gcp_firewall_rule_deleted.py
rules/gcp_audit_rules/gcp_firewall_rule_deleted.yml
rules/gcp_audit_rules/gcp_firewall_rule_modified.yml

This PR is similar to #791 but covers deletions rather than creations. Much of the detection is the same except for the method pattern:
```py
method_pattern = r"(?:\w+\.)*v1\.(?:Firewall\.Delete)|(compute\.firewalls\.delete)"
```
Since this is closely-related to both the above PR and #785, I wanted to create this as a fast follow-up PR.
I also wanted to add another test case for the firewall rule modification detection to cover AppEngine since the original PR only covered Compute Engine.
* Adds `gcp_firewall_rule_deleted.py`
* Adds `gcp_firewall_rule_deleted.yml` with three `True` test cases and two `False` test cases
* Adds `compute.non-update.firewall.method-should-not-alert` test to `gcp_firewall_rule_modified.yml`
* Tests pass as expected:
```
GCP.Firewall.Rule.Deleted
[PASS] …
```

Add detection for GCP firewall rule deletions

---

rules/gcp_audit_rules/gcp_log_bucket_or_sink_deleted.py
rules/gcp_audit_rules/gcp_log_bucket_or_sink_deleted.yml

This PR adds detections around logging bucket and sink deletions. The rule matching follows the regex pattern I have been using in other PRs with the exception of being more broad in matching the API version since this API is `v2` (and given this, I may open a future PR that handles this more gracefully for the other detections I've written recently).
Additionally, I wanted to explicitly alert on authorized requests per the detection spec. To do this, I run a nested `deep_get` on the contents of the `authorizationInfo` list since that list contains an inner dictionary.
* Adds `gcp_log_bucket_or_sink_deleted.py`
* Adds `gcp_log_bucket_or_sink_deleted.yml` with two `True` test cases and two `False` test cases
* Tests pass as expected:
```
GCP.Log.Bucket.Or.Sink.Deleted
[PASS] …
```

Add detections for GCP logging bucket or sink deletions

---

rules/gcp_audit_rules/gcp_logging_sink_modified.py
rules/gcp_audit_rules/gcp_logging_sink_modified.yml

Similar to #798, this PR adds a detection for GCP logging sink modifications. The detection logic is similar with the exception that explicit authorization checks are not present and only one method is checked in the `method_pattern`
* Adds `gcp_logging_sink_modified.py`
* Adds `gcp_logging_sink_modified.yml` with one `True` test case and one `False` test case
* Tests pass as expected:
```
GCP.Logging.Sink.Modified
[PASS] logging-sink.modifed-should-alert
[PASS] [title] [GCP]: [user@domain.com] updated logging sink [projects/test-project-123456/sinks/test-1]
[PASS] [dedup] [GCP]: [user@domain.com] updated logging sink [projects/test-project-123456/sinks/test-1]
[PASS] [alertContext] {"project": "test-project-123456", "principal": "user@domain.com", "caller_ip": …
```

Add detections for GCP logging sink modifications

---

rules/gcp_audit_rules/gcp_firewall_rule_created.py
rules/gcp_audit_rules/gcp_firewall_rule_deleted.py
rules/gcp_audit_rules/gcp_firewall_rule_modified.py

This is a small PR that allows for any API version to satisfy the pattern checking for a few GCP detections (specifically Firewall Rule creations, deletions, and modifications). 
Originally, this was explicitly `v1`, but this will allow future API versions to work (unless GCP changes the structure around entirely when moving to a new API version which is a separate issue).
* Updates the `method_pattern` to allow for `*v\d` rather than just `*v1` for the following detections
* `gcp_firewall_rule_created.py`
* `gcp_firewall_rule_deleted.py`
* `gcp_firewall_rule_modified.py`
* Tests for these rules still pass as expected:
```
GCP.Firewall.Rule.Created
[PASS] compute.firewalls.create-should-alert
[PASS] [title] [GCP]: [user@domain.com] created firewall rule with resource ID …
```

Allow for any API version for certain GCP detections

---

packs/notion.yml
rules/notion_rules/notion_workspace_settings_public_homepage_added.py
rules/notion_rules/notion_workspace_settings_public_homepage_added.yml

Adds a new rule to detect when a Notion workspace page is made public.
```
Notion.Workspace.Public.Page.Added
[PASS] Public page added
[PASS] [title] Notion User example@personemail.com added a new public page 4b801dc7-d724-4fbb-afd0-9885cbc12405 in workspace vvvvvvvv-dddd-4444-bbbb-666666666666
[PASS] [dedup] Notion User example@personemail.com added a new public page 4b801dc7-d724-4fbb-afd0-9885cbc12405 in workspace vvvvvvvv-dddd-4444-bbbb-666666666666
[PASS] [alertContext] {"actor": {"object": "user", "id": "44444444-cccc-7777-aaaa-666666666666", "type": "person", "person": {"email": "example@personemail.com"}}, "action": "workspace.settings.public_homepage_added"}
[PASS] Workspace Exported
Path: …
```

Rule: Notion public homepage added

---

packs/auth0.yml
rules/auth0_rules/auth0_user_joined_tenant.py
rules/auth0_rules/auth0_user_joined_tenant.yml

* Adds an info severity rule to capture when a new user is added to an Auth0 tenant
```
Auth0.User.Joined.Tenant
[PASS] User accepted an invitation
[PASS] [title] Auth0 User [homer.simpson@yourcompany.com] has accepted an invitation to join your organization's tenant [Org Auth0 Tenant Label].
[PASS] [dedup] Auth0 User [homer.simpson@yourcompany.com] has accepted an invitation to join your organization's tenant [Org Auth0 Tenant Label].
[PASS] [alertContext] {"actor": {"email": "homer.simpson@yourcompany.com", "name": "Homer Simpson", "user_id": "google-oauth2|105261262156475850461"}, "action": "Update an invitation"}
[PASS] User declined an invitation
[PASS] Other event
```

Rule: Auth0 User Joined Tenant

---

packs/auth0.yml
rules/auth0_rules/auth0_user_invitation_created.py
rules/auth0_rules/auth0_user_invitation_created.yml

Adds  Auth0 user invitation detection for both Tenants and Organizations.
* add `auth0_user_invitation_created.py` and `auth0_user_invitation_created.yml`
* update `auth0.yml`
Unit test results:
```
Auth0.User.Invitation.Created
[PASS] Test-org
[PASS] [title] Auth0 User [bob@panther.com] invited [larry@example.com] to Organization [Auth0 Org Label]]
[PASS] [dedup] Auth0 User [bob@panther.com] invited [larry@example.com] to Organization [Auth0 Org Label]]
[PASS] [alertContext] {"actor": {"email": "bob@panther.com", "name": "Bob", "user_id": "google-oauth2|115547599209686809398"}, "action": "Create invitations to organization"}
[PASS] Test-org-regex-fail
[PASS] Test-other-endpoint
[PASS] Test-no-invitee
[PASS] …
```

Add detection for user invitations to tenants and organizations

---

global_helpers/global_helpers_test.py
global_helpers/panther_greynoise_helpers.py
global_helpers/panther_ipinfo_helpers.py
global_helpers/panther_lookuptable_helpers.py
global_helpers/panther_tor_helpers.py

p_match has rolled out as part of enrichment, and that allows us to traverse enrichments by value.
extends the base class for lookup tables to walk all lookup tables on the event, collecting matches based on p_match value
added global helper unit tests

feat: find enrichments by value leveraging p_match field

---

packs/auth0.yml
rules/auth0_rules/auth0_mfa_risk_assessment_enabled.py
rules/auth0_rules/auth0_mfa_risk_assessment_enabled.yml

Detection for Auth0 MFA Policies
Fires an `HIGH` severity alert
* Adds `rules/auth0_rules/auth0_mfa_risk_assessment_enabled.py` & `rules/auth0_rules/auth0_mfa_risk_assessment_enabled.yaml` files and udpates the pack.
Test with
```
pipenv run panther_analysis_tool test --filter RuleID=Auth0.MFA.Risk.Assessment.Enabled
```
and got:
```
Auth0.MFA.Risk.Assessment.Enabled
[PASS] Risk Assessment Enabled
[PASS] [title] Auth0 User [user.name@yourcompany.io] enabled mfa risk assessment settings for your organization’s tenant [<NO_P_SOURCE_LABEL_FOUND>].
[PASS] [dedup] Auth0 User [user.name@yourcompany.io] enabled mfa risk assessment settings for your organization’s tenant [<NO_P_SOURCE_LABEL_FOUND>].
[PASS] [alertContext] {"actor": …
```

Add Auth0 MFA Risk Assessment Enabled

---

packs/crowdstrike.yml
rules/crowdstrike_rules/crowdstrike_macos_plutil_usage.py
rules/crowdstrike_rules/crowdstrike_macos_plutil_usage.yml

* Adds a medium severity rule for Crowdstrike logs that alerts when a user runs the `plutil` command.
```
Crowdstrike.Macos.Plutil.Usage
[PASS] Plutil used
[PASS] [title] Crowdstrike: plutil was used to modify a plist file on device [1234abcdefghijklmnop]
[PASS] [dedup] Crowdstrike: plutil was used to modify a plist file on device [1234abcdefghijklmnop]
[PASS] [alertContext] {"aid": "1234abcdefghijklmnop", "CommandLine": "plutil -insert somekey -string somevalue test.app.plist", "TargetProcessId": "488638905187012012", "RawProcessId": "51673", "ParentBaseFileName": "zsh", "ParentProcessId": "488592041865603507", "ImageFileName": "/usr/bin/plutil", "SHA256Hash": "fc708414b7e7c0df8d7711d0362b4dbd79a45fba65bdc646848fa8f50e9035de", "platform": "Mac"}
[PASS] Slack settings …
```

Rule: CrowdStrike MacOS plutil Usage

---

global_helpers/global_helpers_test.py

Sometimes users want to know if there is any GreyNoise enrichment or not, without inspecting any of the details about the enrichment's content. 
This had been a behavior in the now absent `GetGreyNoiseObject().noise` attribute. 
`GetGreyNoiseObject().lut_matches` serves this same purpose, and as such this adds a unit test to contract the behavior. 
```text
(panther-analysis) user@computer:~/Developer/PAN/panther-analysis $ make global-helpers-unit-test
pipenv run python global_helpers/*_test.py
............................................................................................................................................
----------------------------------------------------------------------
Ran 140 tests in 5.781s
OK
```

docs: add unit test to ensure that GetGreyNoiseObject({}).lut_matches is None

---

Makefile
queries/aws_queries/scheduled_rule_default.py
queries/snowflake_queries/snowflake_account_admin_assigned.py
queries/snowflake_queries/snowflake_brute_force_ip.py
queries/snowflake_queries/snowflake_brute_force_username.py
queries/snowflake_queries/snowflake_external_shares.py
queries/snowflake_queries/snowflake_key_user_password_login.py
queries/snowflake_queries/snowflake_login_without_mfa.py
queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success.py
queries/snowflake_queries/snowflake_public_role_grant.py
queries/snowflake_queries/snowflake_user_created.py
queries/snowflake_queries/snowflake_user_enabled.py

The queries directory was excluded from lint and test expectations. This PR updates the default lint and test targets to include the queries directory.
some reformatting of `queries/*/*.py` where the files did not comply with the expectations of the linter. 
```text
user@computer:~/Developer/PAN/panther-analysis $ make lint
pipenv run bandit -r data_models global_helpers policies queries rules templates --skip B101  # allow assert statements in tests
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: B101
[main]  INFO    running on Python 3.9.16
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:01
Run started:2023-06-26 16:47:45.188757
Test results:
No issues …
```

docs: Test+Lint queries directory

---

global_helpers/panther_base_helpers.py

The original `deep_walk` parameter types and type hints were explicitly expecting `dict` objects to be passed in for the `obj` parameter and only strings or a list of strings to be returned by `deep_walk`, respectively.
This PR updates the type hints to be more accurate (i.e., not just `dict` or `str`).
* Updates the `obj` parameter type hint to `Optional[Any]`
* The initial object will be a dictionary, but recursive calls may provide a value that is another dictionary, a list, or other type
* Updates the return type hints to `Optional[Any], Optional[List[Any]]` since the value type could also be something like an integer or boolean in addition to a string.
* Tests still pass as expected

Update deep_walk type hints

---

packs/tines.yml
rules/tines_rules/tines_team_destruction.py
rules/tines_rules/tines_team_destruction.yml

https://www.tines.com/api/audit-logs#:~:text=team%20was%20created-,TeamDestruction,-A%20team%20was
* Tines - TeamDestruction rule
```
Tines.Team.Destruction
[PASS] Detection Trigger
[PASS] [title] Tines [TeamDestruction] performed by [user@email.com] on [tines-log-source-name].
[PASS] [dedup] Tines [TeamDestruction] performed by [user@email.com] on [tines-log-source-name].
[PASS] [alertContext] {"actor": "user@email.com", "action": "TeamDestruction", "tenant_id": "1337", "user_email": "user@email.com", "user_id": "7331", "operation_name": "TeamDestruction", "request_ip": "98.224.225.84"}
[PASS] Tines Login
```

Tines Rule - Team Destruction

---

global_helpers/panther_base_helpers.py

When I was updating the documentation for this function yesterday I noticed that I left in an extra space.
This is a very small change for the sake of consistency.
* Removes an extra space in the `deep_walk` docstring
N/A

fix: update spacing in deep_walk docstring

---

rules/standard_rules/impossible_travel_login.py
rules/standard_rules/impossible_travel_login.yml

There was a vestigial tail of sorts in **Standard.ImpossibleTravel.Login** test case `Okta sign-in with history and impossible travel, VPN with service` where the alert_context attribute `"is_apple_priv_relay"` was set to true, though it shouldn't have been. 
To my ability to validate it, this nit wouldn't cause things to alert that otherwise shouldn't. 
This ultimately seems to be a side effect of how globals work inside the unit testing framework. By moving the definition of the global variable into `rule()`, we ensure that the global gets reset for each test case. 
I checked detections using globals ( ignoring the rules that have global-filters:  auth0_rule, tines_rule,  snyk_rule,  github_rules,  notion_rules,  cloudflare_rules ) and I didn't identify any enabled rules that had this …

fix: when a global is used as a state machine, it is preferable to define it in rule()

---

indexes/github.md
rules/github_rules/github_repo_collaborator_change.yml

Currently, two rules are named `GitHub Repository Visibility Change`
This PR fixes that

Fixes misnaming of github_repo_collaborator_change

---

global_helpers/gcp_environment.py
global_helpers/panther_base_helpers.py
rules/gcp_audit_rules/gcp_access_attempts_violating_vpc_service_controls.py
rules/gcp_audit_rules/gcp_access_attempts_violating_vpc_service_controls.yml
rules/gcp_audit_rules/gcp_log_bucket_or_sink_deleted.py
rules/gcp_audit_rules/gcp_permissions_granted_to_create_or_manage_service_account_key.py
rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.py

@edyesed mentioned that some GCP detections could benefit from using `deep_walk`, so this PR implements that.
* Updates the following detections to use `deep_walk`:
* `gcp_access_attempts_violating_vpc_service_controls.py`
* `gcp_log_bucket_or_sink_deleted.py`
* `gcp_permissions_granted_to_create_or_manage_service_account_key.py`
* `gcp_k8s_exec_into_pod.py`
* Tests still pass as expected

Rework a few GCP detections to use deep_walk

---

policies/aws_load_balancer_policies/aws_alb_ssl_policy.py
policies/aws_load_balancer_policies/aws_alb_ssl_policy.yml

Several "safe" TLS cipher selections were missing from the approved list of ciphers, while non-safe ciphers were being included. Requirements to be "safe": 1) TLSv1.2+ only; 2) Forward Secrecy.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
* Add ciphers `ELBSecurityPolicy-TLS13-1-2-Res-2021-06` and `ELBSecurityPolicy-TLS13-1-3-2021-06`.
* Remove ciphers `ELBSecurityPolicy-TLS-1-2-2017-01` and `ELBSecurityPolicy-TLS-1-2-Ext-2018-06`, as they do not support forward secrecy.
* Updated existing test to account for the removal of a previously approved cipher.

fix: Update list of "safe" TLS ciphers in AWS ALB SSL/TLS policy

---

global_helpers/panther_lookuptable_helpers.py

There are keys at the top level under `p_enrichment` that begin with `p_any_`. These `p_enrichment.p_any*` keys are sometimes (always?) arrays. 
* adds an explicit `ignore all keys under p_enrichment that begin with p_any_` to the base lookuptable helper. 
global helper unit tests and detection unit tests needed no updates with this change.

fix: explicitly ignore top level enrichments that start with 'p_any_' in the key name

---

global_helpers/global_filter_notion.py
global_helpers/global_filter_tailscale.py
global_helpers/global_filter_tailscale.yml
global_helpers/global_helpers_test.py
global_helpers/panther_tailscale_helpers.py
global_helpers/panther_tailscale_helpers.yml

- Pre dev work needed to reference alert context and add customizable global filters for tailscale
* added global filters and panther helpers for tailscale along with tests 
* also fixed comment in notion global filter referencing another integration to reference notion only 
* all tests passing

New: Global helpers and filters for tailscale

---

data_models/crowdstrike_fdr_data_model.py
rules/crowdstrike_rules/crowdstrike_base64_encoded_args.py

The current `Crowdstrike.Base64EncodedArgs` detection runs into issues for FDR event types which aren't `ProcessRollup2`. This PR fixes that.
* Allow CS-FDR UDM function `get_process_name` to return an empty string for cases where the `ImageFileName` field isn't present
* Add a check in the detection to pass on event types other than `ProcessRollup`
```
Crowdstrike.Base64EncodedArgs
[PASS] Command Line Tool Execution with Base64 Argument (Positive)
[PASS] [title] Crowdstrike: Execution with base64 encoded args: [powershell.exe] - ["c:\windows\system32\windowspowershell\v1.0\powershell.exe" -encodedcommand "agvsbg93b3jsza==" -someextracommand "helloworld"]
[PASS] [dedup] Crowdstrike: Execution with base64 encoded args: [powershell.exe] - …
```

fix: CS base64 rule fails for some event types

---

lookup_tables/greynoise/advanced/noise_advanced.yml
lookup_tables/greynoise/advanced/riot_advanced.yml
lookup_tables/greynoise/basic/noise_basic.yml
lookup_tables/greynoise/basic/riot_basic.yml
lookup_tables/ipinfo/ipinfo_asn.yml
lookup_tables/ipinfo/ipinfo_asn_datalake.yml
lookup_tables/ipinfo/ipinfo_location.yml
lookup_tables/ipinfo/ipinfo_location_datalake.yml
lookup_tables/ipinfo/ipinfo_privacy.yml
lookup_tables/ipinfo/ipinfo_privacy_datalake.yml
lookup_tables/tor/tor_exit_nodes.yml

We added `actor_ip` to `Github.Audit` recently. Updating Lookup tables to use it as well.
* Adding `actor_ip` to all enrichment LUTs
* Not yet tested

Adding Github.Audit Actor IP to lookup tables

---

rules/panther_audit_rules/panther_user_modified.py

I was discussing https://github.com/panther-labs/panther-analysis/pull/835 with a coworker when we noticed there was some dead code in it.
There is no need to set a string value for user when `user == None`, as this value doesn't leave the scope of the function, and the subsequent condition evaluates to false either way.
* Remove unneeded code
```console
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> user = None
>>> if user == "foo": print(user)
... 
>>> 
```

fix: remove unused branch

---

README.md

`make vscode-config` is helpful! First-time users may not have the `code` cli tool configured properly, though. This improvement adds those instructions. 
* Added a line highlighting `code` cli is needed
* Also cleaned up markdown syntax.

make vscode-config instruction improvement

---

README.md

`pipenv` was not installed on two different systems that I use. This PR adds the steps to install it, and add it to the path in order to satisfy that prerequisite.
* README.md file
* Confirmed it works across two systems

Documents steps to meet pipenv prereq

---

global_helpers/panther_base_helpers.py

The current `crowdstrike_detection_alert_context()` global helper doesn't provide `aid` context similar to how `crowdstrike_network_detection_alert_context()` and `crowdstrike_process_alert_context()` do. I'm not sure if there's a specific reason why it was omitted, but it would be really useful to have vs. extracting the value from the rules that have it in their titles.
* Adds `aid` context to `crowdstrike_detection_alert_context()` global helper
Tested using `panther_analysis_tool test --path /rules/crowdstrike_rules`

fix: Add missing CrowdStrike aid context to global helper

---

.github/workflows/lint-test.yml
Pipfile
Pipfile.lock
global_helpers/panther_box_helpers.py
global_helpers/panther_oss_helpers.py

This PR updates `panther-analysis` to use Python3.11. Since we consume this as part of PAT's CI tests, we need to update this so that we can use Python3.11 on the PAT side).
* Updates `python_version` to "3.11"
* Updates a few outdated dependencies

Update panther-analysis to use Python3.11

---

rules/dropbox_rules/dropbox_many_deletes.py
rules/dropbox_rules/dropbox_many_downloads.py
rules/gsuite_activityevent_rules/gsuite_drive_many_docs_deleted.py
rules/gsuite_activityevent_rules/gsuite_drive_many_docs_downloaded.py

Customer pointed out that some of the `alert_context` functions return a `PantherEvent` object instead of a regular Python `dict`, which threw them for a loop in their workflow. Since `alert_context` is expected to return a `dict` anyway, I changed those functions to accommodate the customer. 
* Changed 4 `alert_context` functions from `return event` to `return event.to_dict()`
* Ran `make test`, all tests returned successful.

Altered 4 rules to return dict, not PantherEvent

---

.github/workflows/lint-test.yml
Pipfile
Pipfile.lock
global_helpers/panther_box_helpers.py
global_helpers/panther_oss_helpers.py

This reverts commit 000f54dc771223eb7d99801948eb07b9076e2468.
We need to release a new version of PAT and this blocks that from happening until we can move _everything_ over to 3.11

Revert "Update panther-analysis to use Python3.11 (#872)"

---

data_models/azure_signin_data_model.py
data_models/azure_signin_data_model.yml
global_helpers/panther_azuresignin_helpers.py
packs/azure_signin.yml
rules/azure_signin_rules/azure_failed_signins.py
rules/azure_signin_rules/azure_failed_signins.yml
rules/azure_signin_rules/azure_failed_signins_deprecated.yml
rules/azure_signin_rules/azure_legacyauth.py
rules/azure_signin_rules/azure_legacyauth.yml
rules/azure_signin_rules/azure_legacyauth_deprecated.yml
rules/azure_signin_rules/azure_risklevel_passthrough.py
rules/azure_signin_rules/azure_risklevel_passthrough.yml
rules/azure_signin_rules/azure_risklevel_passthrough_deprecated.yml

Due to classification issues, we are merging the `Azure.Audit` and `Azure.SignIn` schemas into one (the former: `Azure.Audit`).
We need to migtea
Relates to https://app.asana.com/0/1205441909782364/1205232760343992/f
* Move the old rules to new files with `Enabled: false` and deprecated notices
* Duplicate the rules into the new schema and add a new guard `is_signin_event` in the rule function
CLI tests:

Migrate Azure.SignIn rules to Azure.Audit

---

rules/aws_cloudtrail_rules/aws_ecr_crud.yml
rules/aws_cloudtrail_rules/aws_ecr_events.yml
rules/aws_cloudtrail_rules/aws_lambda_crud.yml
rules/aws_cloudtrail_rules/aws_s3_activity_greynoise.yml
rules/aws_cloudtrail_rules/aws_unused_region.yml
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.yml
rules/gcp_audit_rules/gcp_iam_org_folder_changes.yml
rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.yml
rules/github_rules/github_organization_app_integration_installed.yml
rules/github_rules/github_public_repository_created.yml
rules/gsuite_activityevent_rules/google_workspace_admin_custom_role.yml
rules/okta_rules/okta_password_accessed.yml
rules/standard_rules/impossible_travel_login.yml
rules/zendesk_rules/zendesk_user_assumption.yml

We are adding some new functionality to uploads to validate the `SummaryAttributes` field, and found that some of our managed detections have invalid `SummaryAttributes` values.
* Changed invalid summary attributes to be valid
* `pat validate` in an instance with the enforce valid summary attributes feature enabled

Fixed invalid summary attributes

---

Pipfile
Pipfile.lock
global_helpers/global_helpers_test.py
global_helpers/panther_oss_helpers.py
rules/azure_signin_rules/azure_failed_signins.py
rules/azure_signin_rules/azure_legacyauth.py

`panther_detection_helpers.caching` module is replacing kv store global helpers
* All kv store globals got their logic replace with a call to the `caching` module
* All kv store globals got a deprecation note
* uploaded to my dev account and saw successful use of the kv store

replacing kv globals with caching funcs

---

Pipfile
Pipfile.lock
global_helpers/panther_box_helpers.py
global_helpers/panther_oss_helpers.py

#872 updated our dependencies and also the Python version; however, the latter is on hold for the time being so we reverted the change. The dependency updates are still needed so this PR re-introduces them.
Additionally, this PR updates PAT from `0.25.0` to `0.27.0`.
* Updates the dependencies in the `Pipfile` to what #872 specified

Update dependencies in Pipfile

---

Makefile
global_helpers/panther_oss_helpers.py

We want to wait until PE deploys using the panther detection helpers before using them here to avoid any timing issues
* Undo changes made here https://github.com/panther-labs/panther-analysis/pull/884
* Still moves check_account_age next to all the other kv helpers
* CI job

reverting using panther detection helpers in kv globals

---

policies/aws_cloudtrail_policies/aws_cloudtrail_s3_bucket_access_logging.py
policies/aws_cloudtrail_policies/aws_cloudtrail_s3_bucket_public.py
policies/aws_config_policies/aws_config_global_resources.py
policies/aws_vpc_policies/aws_vpc_default_network_acl_restricts_all_traffic.py
policies/aws_vpc_policies/aws_vpc_default_security_restrictions.py

The resource_lookup func can throw exceptions if the associated resource is not found. Updated existing detections that did not cater for that
* Manual tests

improve exception handling for some policies

---

global_helpers/panther_oss_helpers.py

This change was originally made in https://github.com/panther-labs/panther-analysis/pull/884
But that was reverted here https://github.com/panther-labs/panther-analysis/pull/889
This is adding it back now that we are ready to
* Replaces kv globals with new caching module
* CI jobs

replacing kv globals with caching module part 2

---

Pipfile

This was breaking because it was too old. I would hope we can use something less strict than `==` here.

Update dependency requirement

---

rules/notion_rules/notion_workspace_settings_enforce_saml_sso_config_updated.py

A minor bug which results in the state variable always being set to "<NO_STATE_FOUND>" so the title doesn't display correctly.
"workspace.settings.enforce_saml_sso_config_updated" line required to determine if state is enabled
* Added the line "workspace.settings.enforce_saml_sso_config_updated", back. 

Added removed workspace.settings line back

---

packs/okta.yml
rules/notion_rules/notion_page_view_impossible_travel.yml
rules/okta_rules/okta_geo_improbable_access.yml

Deprecating duplicate impossible travel rules which are notoriously noisy.  Global impossible travel rule will be refactored and updated in a separate PR.   https://www.notion.so/pantherlabs/Impossible-Travel-bff7c493e9314c6283be945491603c18?pvs=4
* Deprecated impossible travel rules for Okta and Notion
* No logic changes

deprecating duplicate impossible travel rules

---

rules/microsoft_rules/microsoft_exchange_external_forwarding.py
rules/microsoft_rules/microsoft_exchange_external_forwarding.yml
rules/notion_rules/notion_account_changed_after_login.py
rules/notion_rules/notion_login_from_new_location.py
rules/notion_rules/notion_page_accessible_to_guests.py
rules/okta_rules/okta_geo_improbable_access.py
rules/slack_rules/slack_application_dos.py

A customer noted that the `Microsoft365.Exchange.External.Forwarding` detection doesn't alert when the property `ForwardingAddress` is used. I added this property to the detection code.
* Added a check for `ForwardingAddress` to `Microsoft365.Exchange.External.Forwarding`.
* Added a unit test case for the above condition.
* Ran `make test`.

Expanded Microsoft365.Exchange.External.Forwarding to work with ForwardingAddress property

---

rules/okta_rules/okta_admin_role_assigned.py
rules/okta_rules/okta_admin_role_assigned.yml

The detection will only fire as high iff that field is Super admin where it should fire as high if the field contains Super admin.
* Update logic so severity is set to HIGH when privilegeGranted contains "Super administrator"
* Added a unit test for high severity

fixed severity issue for Super admin granted

---

rules/gsuite_activityevent_rules/gsuite_calendar_made_public.py
rules/gsuite_activityevent_rules/gsuite_calendar_made_public.yml

https://developers.google.com/admin-sdk/reports/v1/appendix/activity/calendar#change_calendar_acls
None means nobody can see your calendar. This should just be info level.
When changing a calendar from freebusy to say 'none' it should only be INFO severity.
Change severity based on access change
Is there a way to test for severity?

Set severity to INFO if making calendar private

---

queries/okta_queries/okta_harfile_iocs.yml

Okta released IOCs related to their recent incident.  Since IPs and user agents are trivial for an attacker to change, we opted to release these as a saved search rather than a detection rule to avoid potential false positives.
* Saved search for IPs and user agents released by Okta https://sec.okta.com/harfiles
* Ran search

saved search for IOCs published by Okta

---

LICENSE.txt

We're moving away from the AGPL for `panther-analysis` to the Apache Software License. As part of this, we will also no longer require signed CLAs.
* Updates `LICENSE.txt` with the Apache License 2.0 contents
* N/A

Move from AGPL to Apache Software License

---

.github/workflows/sync-from-upstream.yml

Change 'master' to 'main' as default for GH action since new default branch name is 'main'
* Changed var 
* Tested on commercial instance

Update sync-from-upstream.yml GH action from 'master' to 'main'

---

.github/workflows/lint-test.yml

This was a temporary fix to unblock #500. Other PRs were not seeing issues when running `make test`, so this PR reverts the change to unblock forks that need to run this Check.
* Removes the PAT clone from the `lint-test.yml` Workflow
* The tests pass as expected without the PAT repository being cloned

Remove PAT clone from lint-test Workflow

---

rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.py
rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.yml

The existing GCP K8S Exec into Pod rule currently matches more events than necessary, as the use of `any` means that any entry with `resource.type == "k8s_cluster"` will also result in a True rule evaluation. This also masked the issue with incorrect tests where the schema is incorrect (`resource` is a top-level field, but tests have it nested under `protoPayload`)
<details><summary>Example of a full audit log entry</summary>
<p>
```json
{
"protoPayload": {
"@type": "type.googleapis.com/google.cloud.audit.AuditLog",
"authenticationInfo": {
"principalEmail": "sanitised@example.com"
},
"authorizationInfo": [
{
"granted": true,
"permission": "io.k8s.core.v1.pods.exec.create",
"resource": "core/v1/namespaces/namespace_name/pods/pod_name/exec"
}
],
"methodName": …
```

gcp_k8s_rules: fix logic matching irrelevant events

---

.gitattributes

Each fork should have it's own CODEOWNERS. This could help with merge conflicts for that file when forked versions change their codeowners.

Always use the "our" CODEOWNERS

---

lookup_tables/greynoise/advanced/noise_advanced.yml
lookup_tables/greynoise/advanced/riot_advanced.yml
lookup_tables/greynoise/basic/noise_basic.yml
lookup_tables/ipinfo/ipinfo_asn.yml
lookup_tables/ipinfo/ipinfo_asn_datalake.yml
lookup_tables/ipinfo/ipinfo_location.yml
lookup_tables/ipinfo/ipinfo_location_datalake.yml
lookup_tables/ipinfo/ipinfo_privacy.yml
lookup_tables/ipinfo/ipinfo_privacy_datalake.yml
lookup_tables/tor/tor_exit_nodes.yml

The Zeek selectors were wrong (missing `$.` which is necessary to indicate a JSON path).
This is breaking customers.
We should get this published ASAP.

Fix the Zeek selectors in luts

---

rules/aws_cloudtrail_rules/aws_unauthorized_api_call.py

Customers were running into empty `dedup` values because the `dedup` function for this rule is looking for an `arn` key in the `userIdentity` object which does not exist (based on the test logs, this used to be a valid key and was likely removed).
This PR updates the `dedup` function to use `principalId` instead.
* Uses the `principalId` key rather than the nonexistent `arn` key
* Tests pass as expected:
```
AWS.CloudTrail.UnauthorizedAPICall
[PASS] Unauthorized API Call from Within AWS (IP)
[PASS] [title] Access denied to IAMUser [1111]
[PASS] [dedup] 1111
[PASS] [alertContext] {"eventName": "CreateServiceLinkedRole", "eventSource": "iam.amazonaws.com", "awsRegion": "us-east-1", "recipientAccountId": "123456789012", "sourceIPAddress": "3.10.107.144", "userAgent": …
```

Update aws_unauthorized_api_call dedup function

---

Makefile

The Makefile for this repo simplifies rule testing, especially when used in combination with docker.  However, there wasn't a way to pass additional arguments to the ultimate `panther_analysis_tool test` call, such as to only [run tests for a given path](https://github.com/panther-labs/panther_analysis_tool#test).
* Adding optional `TEST_ARGS` that can be passes to the make test targets, including passthrough to docker.
An example of running tests only for a given path, specified with `TEST_ARGS`, e.g. `make docker-test TEST_ARGS="--path rules/aws_cloudtrail_rules/"` 
```bash
$ make docker-test TEST_ARGS="--path rules/aws_cloudtrail_rules/"
docker run --mount "type=bind,source=/home/bfeld/src/github.com/rootshellz/panther-analysis,target=/home/panther-analysis" panther-analysis make test …
```

adding optional TEST_ARGS to the test targets

---

.github/workflows/sync-from-upstream.yml

We've had reports of merge conflicts for forks of this repo. There's a configuration option for the Fork Sync Action we use in the `sync-from-upstream` Workflow and this PR turns it on (by default it is `false`).
* Sets `git_config_pull_rebase: true` for the `sync-from-upstream.yml` Workflow
* N/A

Set git_config_pull_rebase: true for fork sync step

---

.github/workflows/sync-from-upstream.yml

We cut the release on Tuesday mornings around 10 AM Pacific, but we are upgrading customers at 7 AM on Tuesdays. This moves that to Wednesdays.

Auto deploy on Wednesday mornings

---

rules/panther_audit_rules/panther_user_modified.py

Rule was statically setting HIGH which means a UI change to override severity wouldn't stick. This change leverages the [DEFAULT](https://docs.panther.com/detections/rules/python#severity) value as the return string. This will allow overrides in the UI (or yaml file) to stick for this rule.
* Updated return value from High > Default

Updating panther_user_modified to use default severity

---

.github/workflows/sync-from-upstream.yml

I believe that we are running into merge conflicts on every release because the forked repos that run the code are not able to find a shared commit, resulting in divergent trees.
The `shallow_since` setting default pins this to 1 month. This PR changes it to 5 years. It's not that big of a repo and this command runs in CI so I don't think it will be an issue.
I also included `--allow-unrelated-histories` in the case that we miss even a shared commit even with `shallow_since`.
I also disabled the new `git_config_pull_rebase` as I am concerned that it could result in merges that are more difficult to reconcile.
See `shallow_since` in this docs: https://github.com/aormsby/Fork-Sync-With-Upstream-action

bump `shallow_since` from 1 month to 5 years to look back to the beginning of git history

---

.github/workflows/release.yml

We currently have a manual process for cutting `panther-analysis` releases and it is in a spot where we can automate it (at least via `workflow_dispatch`). This PR adds the initial Workflow. Once we see how this goes after a few releases, we can potentially add a cron schedule to automate the release entirely.
* Adds `release.yml` to automate `panther-analysis` releases
* These steps work manually so as far as that goes this has been thoroughly tested

Add Workflow to automate panther-analysis releases

---

.github/pull.yml

The current Action we rely on for syncing forks with our upstream changes is no longer maintained. This PR adds a [Pull](https://github.com/wei/pull) config so that fork owners can install the GitHub App and automatically consume the desired configuration.
* Adds Pull configuration
* N/A

Add Pull config

---

.github/workflows/release.yml

Addresses:
```
It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission? If you are not trying to authenticate with OIDC and the action is working successfully, you can ignore this message.
```
* Adds `permissions` to the release Workflow
* This is the configuration we use elsewhere for OIDC + GitHub Actions

Update release Workflow

---

global_helpers/panther_default.py
policies/aws_cloudtrail_policies/aws_cloudtrail_s3_bucket_public.py

The Events `codepipeline-cloudtrail-placeholder-bucket` Buckets are managed by AWS and are also public. This was causing the `aws_cloudtrail_s3_bucket_public` policy to alert when the buckets were inspected.
This PR adds an `EXCLUDED_BUCKET_NAMES` set for these buckets (and future buckets, if necessary) and also adds a list of AWS regions in order to build out the complete set of these bucket names.
* Adds a function to return a list of AWS regions
* Adds an `EXCLUDED_BUCKET_NAMES` set for buckets to ignore in the policy
* Tests still pass as expected

Add EXCLUDED_BUCKET_NAMES set for aws_cloudtrail_s3_bucket_public.py policy

---

packs/gcp_audit.yml
rules/gcp_audit_rules/gcp_inbound_sso_profile_created_or_updated.py
rules/gcp_audit_rules/gcp_inbound_sso_profile_created_or_updated.yml
rules/gcp_audit_rules/gcp_workforce_pool_created_or_updated.py
rules/gcp_audit_rules/gcp_workforce_pool_created_or_updated.yml
rules/gcp_audit_rules/gcp_workload_identity_pool_created_or_updated.py
rules/gcp_audit_rules/gcp_workload_identity_pool_created_or_updated.yml

Adds three new GCP SSO persistence rules that cover creations and updates:
- `GCP.Inbound.SSO.Profile.Created`
- `GCP.Workforce.Pool.Created.or.Updated`
- `GCP.Workload.Identity.Pool.Created.or.Updated`
* Adds the three aforementioned rules
* Updates the `gcp_audit` pack to include the new rules
Tests pass as expected:
```
$ make test TEST_ARGS="--path rules/gcp_audit_rules/"
pipenv run python -m unittest global_helpers/*_test.py
.............................................................................................................................................
----------------------------------------------------------------------
Ran 141 tests in 7.125s
OK
pipenv run panther_analysis_tool test --path rules/gcp_audit_rules/
[INFO][root]: Testing analysis items in …
```

Add GCP SSO persistence rules

---

.github/workflows/release.yml

A `GITHUB_TOKEN` environment variable must be used when using the `gh` CLI via GHA.
* Adds a `GITHUB_TOKEN` environment variable to `release.yml`
* N/A

 Update release Workflow with GITHUB_TOKEN env var

---

.github/workflows/release.yml

This PR corrects how the Workflow access the value of `NEW_VERSION` (i.e. accessing its value rather than trying to run it as a command).
* Updates how `NEW_VERSION` is accessed
* N/A

Update gh release create command

---

.github/workflows/release.yml

Since we don't create a tag locally, we cannot use `--notes-from-tag`. This PR instead uses `--generate-notes` to handle all of the generation for the release.
```
--generate-notes               Automatically generate title and notes for the release
```
* Uses `--generate-notes` rather than `--notes-from-tag` for release creation
* I tested this locally in a separate repository and it worked as expected

Use --generate-notes for release creation

---

.github/CODEOWNERS

Now that we have a separate threat research GitHub team, we can add it to `CODEOWNERS` to allow separate approvals.
* Adds `@panther-labs/threat-research` to `CODEOWNERS`
* N/A

Add threat research team to CODEOWNERS

---

packs/standard_ruleset.yml

The impossible travel rule includes Notion Audit Log unit tests, so we need to include the Notion Data Models to allow the tests to pass.
Can't save filters to Impossible Travel detection unless Notion detection pack is enabled/Notion data model is brought in.
* Added the Standard.Notion.AuditLogs data model to the Standard pack

Update standard_ruleset.yml to include Notion Data Model

---

rules/github_rules/github_secret_scanning_alert_created.py
rules/github_rules/github_secret_scanning_alert_created.yml

This PR makes minor improvements to the `GitHub.Secret.Scanning.Alert.Created` rule. The core logic was sound, but I wanted to include more accurate logs and better `.get` default values.
* Updates `github_secret_scanning_alert_created.py`
* Updates `github_secret_scanning_alert_created.yml`
* `make fmt; make lint; make test`

Update github_secret_scanning_alert_created rule/tests

---

.github/dependabot.yml

Recent changes such as https://github.com/panther-labs/panther-analysis/pull/939 have introduced pinned GitHub actions.  This is a great practice, but the flip side is: pinned dependencies also need to be kept up to date.  Thankfully, Dependabot can do that for us!
I'm interested in this because we want to keep actions up to date in our downstream fork, and we'll avoid merge conflicts if they're also up to date in the upstream.
* Add a dependabot [version update](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) config for GitHub Actions
I enabled this on my private fork of the `panther-analysis` repo and verified that I got the expected PRs.  You can check this out here: …

Enable Dependabot for GitHub actions

---

global_helpers/panther_base_helpers.py
global_helpers/panther_default.py
packs/gravitational_teleport.yml
rules/gravitational_teleport_rules/teleport_auth_errors.py
rules/gravitational_teleport_rules/teleport_auth_errors.yml
rules/gravitational_teleport_rules/teleport_create_user_accounts.py
rules/gravitational_teleport_rules/teleport_create_user_accounts.yml
rules/gravitational_teleport_rules/teleport_local_user_login_without_mfa.py
rules/gravitational_teleport_rules/teleport_local_user_login_without_mfa.yml
rules/gravitational_teleport_rules/teleport_lock_created.py
rules/gravitational_teleport_rules/teleport_lock_created.yml
rules/gravitational_teleport_rules/teleport_long_lived_certs.py
rules/gravitational_teleport_rules/teleport_long_lived_certs.yml
rules/gravitational_teleport_rules/teleport_network_scanning.py
rules/gravitational_teleport_rules/teleport_network_scanning.yml
rules/gravitational_teleport_rules/teleport_role_created.py
rules/gravitational_teleport_rules/teleport_role_created.yml
rules/gravitational_teleport_rules/teleport_root_login.py
rules/gravitational_teleport_rules/teleport_root_login.yml
rules/gravitational_teleport_rules/teleport_saml_created.py
rules/gravitational_teleport_rules/teleport_saml_created.yml
rules/gravitational_teleport_rules/teleport_scheduled_jobs.py
rules/gravitational_teleport_rules/teleport_scheduled_jobs.yml
rules/gravitational_teleport_rules/teleport_suspicious_commands.py
rules/gravitational_teleport_rules/teleport_suspicious_commands.yml

This PR updates the Gravitational Teleport rule set.
- The documentation links for existing rules needed some updating to new locations
- Added the name of the Teleport cluster into some of titles (useful for multi-cluster organizations)
- Added a Rule to detect local user logins without using multi-factor auth
- Added a Rule to detect the creation of Teleport Locks (used to pre-emptively disable previously-issued certificates)
- Added a Rule to detect the creation of abnormally long-lived certificates
- Added a Rule to detect when Roles are created
- Added a Rule to detect logins as root
- Added a Rule to detect the creation of SAML connectors

Teleport: Update Rules

---

queries/kubernetes_queries/kubernetes_admission_controller_created_query.yml
queries/kubernetes_queries/kubernetes_cron_job_created_or_modified_query.yml
queries/kubernetes_queries/kubernetes_new_daemonset_deployed_query.yml
queries/kubernetes_queries/kubernetes_overly_permissive_linux_capabilities_query.yml
queries/kubernetes_queries/kubernetes_pod_attached_to_node_host_network_query.yml
queries/kubernetes_queries/kubernetes_pod_create_or_modify_host_path_vol_mount_query.yml
queries/kubernetes_queries/kubernetes_pod_in_default_name_space_query.yml
queries/kubernetes_queries/kubernetes_pod_using_host_ipc_namespace_query.yml
queries/kubernetes_queries/kubernetes_pod_using_host_pid_namespace_query.yml
queries/kubernetes_queries/kubernetes_privileged_pod_created_query.yml
queries/kubernetes_queries/kubernetes_secret_enumeration_query.yml
queries/kubernetes_queries/kubernetes_service_type_node_port_deployed_query.yml
queries/kubernetes_queries/kubernetes_unauthenticated_api_request_query.yml
queries/kubernetes_queries/kubernetes_unauthorized_pod_execution_query.yml
rules/gravitational_teleport_rules/teleport_long_lived_certs.py

scheduled queries cause errors when the referenced tables have not been created
* set enabled: false on all k8s scheduled queries

k8s queries disabled by default

---

data_models/github_data_model.py
rules/standard_rules/admin_assigned.yml

GitHub's audit logs don't explicitly define an admin role and instead offers a few events that indicate admin permissions were assigned to a user (or at least when an attempt is made). 
Originally, the data model only accounted for `team.promote_maintainer`, but there are two additional events that indicate admin permissions are being assigned or attempting to be assigned (at least at an organization level).
This PR adds the additional events and returns the event name rather than `<UNKNOWN_ROLE>` when these events are encountered. Worst case, the data model falls back to `<UNKNOWN_ADMIN_ROLE>` .
* Adds additional admin events to the GitHub Data Model
* Return the event name when possible
* `make fmt; make lint; make test`
```
[PASS] Github - User Promoted
[PASS] …
```

Update GitHub Data Model to display admin-add events instead of UNKNOWN_ROLE

---

.vscode/example_settings.json
README.md
pyproject.toml

`make fmt` runs both `isort` and `black` on all files in the repository; however, it would also be nice for individual files to be formatted automatically on save. This PR updates the configuration applied by `make vscode-config` to include settings to run the equivalent of what `make fmt` runs when saving a file.
This PR also updates the `README` file with a link to the required VSCode extension and makes a note of the added functionality for the Make target and also adds the `black` and `isort` configuration to `pyproject.toml`.
* Adds `make fmt` equivalents to `example_settings.json`
* Updates `README.md`
* Adds `pyproject.toml`
* The new settings work as expected -- I tested this by running `make vscode-config`, installing the formatting extension, and saving a modified file with …

Allow for auto-formatting on save when using VSCode

---

.bandit
.pylintrc
.vscode/example_settings.json
Makefile
README.md

Similar to #981, this PR mirrors the `make lint` configuration in `example_settings.json` which are then applied to the Workspace when `make vscode-config` is run.
This PR also introduces a `.bandit` and `.pylintrc` file to make the configuration more concise.
* Adds `make lint` configuration to `example_settings.json`
* Cleans up `make lint` using new configuration files
* I tested this locally and the linting settings took effect after running `make vscode-config`

Add linting config to example_settings.json

---

Pipfile
Pipfile.lock
README.md

This PR updates PAT to `0.34.0` ahead of today's release.
* Updates PAT to `0.34.0`
* Runs `make deps-update`
* Makes a small `README.md` update
* `make test`

Update PAT to 0.34.0

---

rules/aws_cloudtrail_rules/abnormally_high_event_volume.yml
rules/aws_cloudtrail_rules/aws_ec2_ebs_encryption_disabled.yml
rules/aws_cloudtrail_rules/aws_ec2_gateway_modified.yml
rules/aws_cloudtrail_rules/aws_ec2_manual_security_group_changes.yml
rules/aws_cloudtrail_rules/aws_ec2_monitoring.yml
rules/aws_cloudtrail_rules/aws_ec2_network_acl_modified.yml
rules/aws_cloudtrail_rules/aws_ec2_route_table_modified.yml
rules/aws_cloudtrail_rules/aws_ec2_security_group_modified.yml
rules/aws_cloudtrail_rules/aws_ec2_startup_script_change.yml
rules/aws_cloudtrail_rules/aws_ec2_vpc_modified.yml
rules/aws_cloudtrail_rules/aws_ecr_crud.yml
rules/aws_cloudtrail_rules/aws_ecr_events.yml
rules/aws_cloudtrail_rules/aws_iam_assume_role_blocklist_ignored.yml
rules/aws_cloudtrail_rules/aws_iam_entity_created_without_cloudformation.yml
rules/aws_cloudtrail_rules/aws_iam_user_key_created.yml
rules/aws_cloudtrail_rules/aws_ipset_modified.yml
rules/aws_cloudtrail_rules/aws_key_compromised.yml
rules/aws_cloudtrail_rules/aws_lambda_crud.yml
rules/aws_cloudtrail_rules/aws_network_acl_permissive_entry.yml
rules/aws_cloudtrail_rules/aws_rds_master_pass_updated.yml
rules/aws_cloudtrail_rules/aws_rds_publicrestore.yml
rules/aws_cloudtrail_rules/aws_resource_made_public.yml
rules/aws_cloudtrail_rules/aws_root_console_login.yml
rules/aws_cloudtrail_rules/aws_saml_activity.yml
rules/aws_cloudtrail_rules/aws_security_configuration_change.yml
rules/aws_cloudtrail_rules/aws_securityhub_finding_evasion.yml
rules/aws_cloudtrail_rules/aws_snapshot_backup_exfiltration.yml
rules/aws_cloudtrail_rules/aws_snapshot_made_public.yml
rules/aws_cloudtrail_rules/aws_user_login_profile_modified.yml

Add references to rules (aws_cloudtrail_rules)

---

rules/aws_s3_rules/aws_s3_unauthenticated_access.yml
rules/aws_s3_rules/aws_s3_unknown_requester_get_object.yml

Add references to rules (aws_s3_rules)

---

rules/crowdstrike_rules/aws_authentication_from_crowdstrike_unmanaged_device.yml
rules/crowdstrike_rules/crowdstrike_base64_encoded_args.yml
rules/crowdstrike_rules/crowdstrike_credential_dumping_tool.yml
rules/crowdstrike_rules/crowdstrike_cryptomining_tools.yml
rules/crowdstrike_rules/crowdstrike_detection_passthrough.yml
rules/crowdstrike_rules/crowdstrike_macos_add_trusted_cert.yml
rules/crowdstrike_rules/crowdstrike_macos_osascript_administrator.yml
rules/crowdstrike_rules/crowdstrike_macos_plutil_usage.yml
rules/crowdstrike_rules/crowdstrike_remote_access_tool_execution.yml
rules/crowdstrike_rules/crowdstrike_reverse_shell_tool_executed.yml
rules/crowdstrike_rules/crowdstrike_systemlog_tampering.yml
rules/crowdstrike_rules/crowdstrike_unusual_parent_child_processes.yml
rules/crowdstrike_rules/crowdstrike_wmi_query_detection.yml
rules/crowdstrike_rules/okta_login_from_crowdstrike_unmanaged_device.yml
rules/crowdstrike_rules/onepassword_login_from_crowdstrike_unmanaged_device.yml

Add references to rules (crowdstrike_rules)

---

rules/gcp_audit_rules/gcp_access_attempts_violating_vpc_service_controls.yml
rules/gcp_audit_rules/gcp_bigquery_large_scan.yml
rules/gcp_audit_rules/gcp_cloud_storage_buckets_modified_or_deleted.yml
rules/gcp_audit_rules/gcp_destructive_queries.yml
rules/gcp_audit_rules/gcp_dns_zone_modified_or_deleted.yml
rules/gcp_audit_rules/gcp_gcs_iam_changes.yml
rules/gcp_audit_rules/gcp_gcs_public.yml
rules/gcp_audit_rules/gcp_iam_admin_role_assigned.yml
rules/gcp_audit_rules/gcp_iam_corp_email.yml
rules/gcp_audit_rules/gcp_iam_custom_role_changes.yml
rules/gcp_audit_rules/gcp_iam_org_folder_changes.yml
rules/gcp_audit_rules/gcp_logging_settings_modified.yml
rules/gcp_audit_rules/gcp_permissions_granted_to_create_or_manage_service_account_key.yml
rules/gcp_audit_rules/gcp_service_account_or_keys_created.yml
rules/gcp_audit_rules/gcp_sql_config_changes.yml
rules/gcp_audit_rules/gcp_unused_regions.yml
rules/gcp_audit_rules/gcp_user_added_to_iap_protected_service.yml
rules/gcp_audit_rules/gcp_vpc_flow_logs_disabled.yml

Add references to rules (gcp_audit_rules)

---

rules/notion_rules/notion_account_changed_after_login.yml
rules/notion_rules/notion_login_from_blocked_ip.yml
rules/notion_rules/notion_login_from_new_location.yml
rules/notion_rules/notion_many_pages_deleted.yml
rules/notion_rules/notion_many_pages_exported.yml
rules/notion_rules/notion_page_accessible_to_api.yml
rules/notion_rules/notion_page_accessible_to_guests.yml
rules/notion_rules/notion_page_shared_to_web.yml
rules/notion_rules/notion_page_view_impossible_travel.yml
rules/notion_rules/notion_scim_token_generated.yml
rules/notion_rules/notion_workspace_audit_log_exported.yml
rules/notion_rules/notion_workspace_exported.yml
rules/notion_rules/notion_workspace_settings_enforce_saml_sso_config_updated.yml
rules/notion_rules/notion_workspace_settings_public_homepage_added.yml

Add references to rules (notion_rules)

---

rules/tines_rules/tines_actions_disabled_changes.yml
rules/tines_rules/tines_custom_ca.yml
rules/tines_rules/tines_enqueued_retrying_job_deletion.yml
rules/tines_rules/tines_global_resource_destruction.yml
rules/tines_rules/tines_sso_settings.yml
rules/tines_rules/tines_story_items_destruction.yml
rules/tines_rules/tines_story_jobs_clearance.yml
rules/tines_rules/tines_team_destruction.yml
rules/tines_rules/tines_tenant_authtoken.yml

Add references to rules (tines_rules)

---

rules/okta_rules/okta_app_unauthorized_access_attempt.yml
rules/okta_rules/okta_geo_improbable_access.yml
rules/okta_rules/okta_group_admin_role_assigned.yml
rules/okta_rules/okta_user_account_locked.yml
rules/okta_rules/okta_user_mfa_factor_suspend.yml
rules/okta_rules/okta_user_mfa_reset.yml
rules/okta_rules/okta_user_mfa_reset_all.yml

Add references to rules (okta_rules)

---

rules/zoom_operation_rules/zoom_all_meetings_secured_with_one_option_disabled.yml
rules/zoom_operation_rules/zoom_new_meeting_passcode_required_disabled.yml
rules/zoom_operation_rules/zoom_sign_in_method_modified.yml
rules/zoom_operation_rules/zoom_sign_in_requirements_changed.yml
rules/zoom_operation_rules/zoom_two_factor_authentication_disabled.yml
rules/zoom_operation_rules/zoom_user_promoted_to_privileged_role.yml

Add references to rules (zoom_rules)

---

.github/workflows/test.yml

This PR moves away from `make test` to Instance-based testing to ensure that rules are validated within Panther rather than relying on PAT's local output.
* Changes `make test` to `pipenv run panther_analysis_tool test --api-host ${{ secrets.API_HOST }} --api-token ${{ secrets.API_TOKEN }}` in `test.yml`
* We're using this successfully for internal changes

Update how tests are run in test.yml

---

templates/example_rule.yml

while we support the `InlineFIlters` parameter in the YAML definition, it was missing from our template.
adding lines to our template file that are found in our documentation.
created a simple detection and uploaded it via PAT to verify the syntax works.

adding example inline filter syntax to the rule template

---

Dockerfile
Pipfile
Pipfile.lock

Snyk picked up a Critical CVE in the `python:3.9-slim` image. Swapping to Wolfi, white a little more verbose, gives us a much better CVE footprint.
Grype results using Wofli:
```
grype panther-analysis:latest
✔ Vulnerability DB                [no update available]
✔ Loaded image                                                                                                     panther-analysis:latest
✔ Parsed image                                                     sha256:3f5f7c130cad2f55161b8351c47c67517507685646d0ed855ba17c7a8a56aaf9
✔ Scanned for vulnerabilities     [2 vulnerability matches]
├── by severity: 0 critical, 1 high, 1 medium, 0 low, 0 negligible
└── by status:   0 fixed, 2 not-fixed, 0 ignored
[0010]  WARN unable to create any package-file relationships …
```

[sync] Address CVEs; move to Wolfi-based Dockerfile (#45)

---

rules/aws_cloudtrail_rules/aws_ami_modified_for_public_access.py
rules/aws_cloudtrail_rules/aws_ami_modified_for_public_access.yml

Customers are seeing false positives with the recently-modified `aws_ami_modified_for_public_access.py/.yml` rule. This PR reverts the change to the original behavior which was correct.
AWS docs on this: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html
The CLI command specifies that `Group=all` is what makes an AMI public, not sharing the AMI with a user.
* Reverts changes to `aws_ami_modified_for_public_access.py/.yml`

[sync] Revert changes to aws_ami_modified_for_public_access.py/.yml (#48)

---

lookup_tables/greynoise/advanced/noise_advanced.yml
lookup_tables/greynoise/advanced/riot_advanced.yml
lookup_tables/greynoise/basic/noise_basic.yml
lookup_tables/greynoise/basic/riot_basic.yml
lookup_tables/ipinfo/ipinfo_asn.yml
lookup_tables/ipinfo/ipinfo_asn_datalake.yml
lookup_tables/ipinfo/ipinfo_location.yml
lookup_tables/ipinfo/ipinfo_location_datalake.yml
lookup_tables/ipinfo/ipinfo_privacy.yml
lookup_tables/ipinfo/ipinfo_privacy_datalake.yml
lookup_tables/tor/tor_exit_nodes.yml

LUT IP selectors should be kept up to date
* LUT IP selectors for the new Azure.MonitorActivity schema
* config changes

[sync] Add Azure.MonitorActivity to ip selectors for LUTs (#50)

---

packs/netskope.yml
rules/netskope_rules/netskope_admin_user_change.yml

This was originally part of the Netskope rule pack, but failed to upload due to bad logic in the DynamicSeverity function
* New rule to detect when admin users are created, deleted, or updated in Netskope
* Fixed DynamicSeverity function
* make test

[sync] Reintroduce netskope_admin_user_change rule with fixed severity function

---

rules/gcp_audit_rules/gcp_iam_service_account_key_create.yml

Detect iam.serviceAccountKeys.create method for privilege escalation in GCP. 
Categorization
TA0004:T1548
Strategy Abstract
The Identity and Access Management (IAM) service manages authorization and authentication for a GCP environment. This means that there are very likely multiple privilege escalation methods that use the IAM service and/or its permissions.
Technical Context
If your user is assigned a custom IAM role, then iam.roles.update will allow you to update the “includedPermissons” on that role. Because it is assigned to you, you will gain the additional privileges, which could be anything you desire.
Blind Spots and Assumptions
Assumes proper GCP logging and audit policies.
False Positives
Legitimate administrative activity that is authorized and expected.
Validation
The exploit …

[sync] Add detection of iam.serviceAccountKeys.create event (#53)

---

rules/gcp_audit_rules/gcp_iam_roles_update_prielege_escalation.yml

Detect iam.roles.update method for privilege escalation in GCP.
TA0004:T1548
The Identity and Access Management (IAM) service manages authorization and authentication for a GCP environment. This means that there are very likely multiple privilege escalation methods that use the IAM service and/or its permissions.
If your user is assigned a custom IAM role, then iam.roles.update will allow you to update the “includedPermissons” on that role. Because it is assigned to you, you will gain the additional privileges, which could be anything you desire.
Assumes proper GCP logging and audit policies.
Legitimate administrative activity that is authorized and expected.
The exploit script for this method can be found [here](https://github.com/RhinoSecurityLabs/GCP-IAM-Privilege-Escalation/blob/master …

[sync] Add GCP.iam.roles.update.Privilege.Escalation rule (#49)

---

rules/gcp_audit_rules/gcp_cloudbuild_potential_privilege_escalation.yml

Detect privilege escalation attacks designed to gain access to the Cloud Build Service Account.  Depending on what logs are generated by the exploit, this ticket could result in multiple detections.
TA0004:T1548
A user with permissions to start a new build with Cloud Build can gain access to the Cloud Build Service Account and abuse it for more access to the environment.
[Cloud Build](https://cloud.google.com/cloud-build/) is a service that “lets you build software quickly across all languages. Get complete control over defining custom workflows for building, testing, and deploying across multiple environments such as VMs, serverless, Kubernetes, or Firebase”.  You might use Cloud Build for a variety of reasons, but even if you don’t use it at all, you may still be vulnerable to this …

[sync] GCP.CloudBuild.Potential.Privilege.Escalation rule (#54)

---

rules/gcp_audit_rules/gcp_cloudfunctions_functions_create.yml

Goal
Detect cloudfunctions.functions.create method for privilege escalation in GCP. 
Categorization
TA0004:T1548
Strategy Abstract
The Identity and Access Management (IAM) service manages authorization and authentication for a GCP environment. This means that there are very likely multiple privilege escalation methods that use the IAM service and/or its permissions.
Technical Context
For this method, we will be creating a new Cloud Function with an associated Service Account that we want to gain access to. Because Cloud Function invocations have access to the metadata API, we can request a token directly from it, just like on a Compute Engine instance.
The required permissions for this method are as follows:
cloudfunctions.functions.call OR cloudfunctions.functions.setIamPolicy …

[sync] Add GCP.Cloudfunctions.Functions.Create rule (#58)

---

packs/gcp_audit.yml
rules/gcp_audit_rules/gcp_iam_service_account_key_create.yml
rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create.yml

In order for the new GCP rules to  be usable, we need to add them to the `gcp_audit` Pack. This PR adds seven new rules to said pack.
This can merge after all of the GCP rule additions are merged.
* Adds seven new rules to the `gcp_audit.yml` pack

[sync] Add new GCP rules to gcp_audit.yml pack (#62)

---

rules/aws_guardduty_rules/aws_guardduty_high_sev_findings.py
rules/aws_guardduty_rules/aws_guardduty_low_sev_findings.py
rules/aws_guardduty_rules/aws_guardduty_low_sev_findings.yml
rules/aws_guardduty_rules/aws_guardduty_med_sev_findings.py
rules/aws_guardduty_rules/aws_guardduty_med_sev_findings.yml

Identifies duplicate GuardDuty alerts and groups them into single alerts in Panther.
* Change dedup string from event.id to event.title, since event.id is highly unique and offers no deduplication potential
* Change dedup interval for high/med/low sev GuardDuty alerts from 1/1/8 hours to 1/8/24 hours
* `make fmt, make lint, make test`
* Based on observations from AWS GuardDuty alert volumes in production environments

[sync] improved dedup for GuardDuty passthrough alerts (#57)

---

Pipfile
Pipfile.lock

We're going to use the latest version of PAT rather than `0.37.1`.
* Updates PAT from `0.37.1` to `0.38.0`

[sync] Update PAT to 0.38.0 (#61)

---

Pipfile.lock

PAT `0.38.1` was released which updates the nested PDH version from `0.1.3` to `0.2.0`. This PR updates PAT to the new version.
* Runs `make deps-update` to update `Pipfile.lock`

Update PAT to 0.38.1 (#65)

---

.github/workflows/check-packs.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/validate.yml

Fork PRs won't have access to the new secrets we're using for Workflows. This PR adds the `pull_request_target` trigger to our CI Workflows.
* Adds `pull_request_target:` to each of the CI Workflows
* TBD

Add pull_request_target to CI Checks

---

.github/workflows/check-packs.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/validate.yml

We can rely solely on `pull_request_target` for the CI Checks.
Otherwise, fork PRs will see failures for these Checks while the `pull_request_target` Checks will work.
* Removes `pull_request` from CI Checks; leaves `pull_request_target`
* N/A

Remove pull request trigger

---

rules/okta_rules/okta_potentially_stolen_session.py
rules/okta_rules/okta_potentially_stolen_session.yml

Okta may include events in the system log that make it look like an Okta (admin) user suddenly changed user agent and IP: https://support.okta.com/help/s/article/okta-integrations-showing-as-rawuseragent-with-okta-ips?language=en_US
Prior to February 7, the `externalSessionId` was "unknown" which meant this Panther rule ignored the problematic events. However, starting February 7th this seems to have changed and Okta has started generating session ids corresponding to these Okta-owned, internal events.
The result is that we (a customer of Panther's) started getting hit with alerts making it seem like sessions were hijacked when in fact it's just that these internal Okta user agent/ip events were causing alerts to fire.
To fix this, note that the `client.id` field contains a unique ID …

Ignore Okta internal admin console accesses in stolen session rule

---

rules/okta_rules/okta_potentially_stolen_session.py
rules/okta_rules/okta_potentially_stolen_session.yml

Okta added some additional context to their event logs which was causing the `Potentially Stolen Session` Rule to fire off false positives.
This PR adds some additional checks focused on the `dtHash` field which is used for Okta threat hunting[0].
TBD if `dtHash` is included by default since it's located in the `debugContext` object. That said, we'll return `False` if `unknown` is returned like we do for `session_id`.
[0] https://www.rezonate.io/glossary/what-is-okta-dthash/
* Adds `dtHash` checks and fuzzing to `okta_potentially_stolen_session.py`
* Adds a couple of additional fields to the String Set (`sign_on_mode` and `threat_suspected`)
* Tests pass as expected when accounting for `dtHash`

[sync] Use additional event data for Okta Stolen Session Rule (#70)

---

rules/aws_cloudtrail_rules/aws_software_discovery.py
rules/aws_cloudtrail_rules/aws_software_discovery.yml
rules/aws_cloudtrail_rules/aws_unauthorized_api_call.yml
rules/aws_eks_rules/system_namespace_public_ip.py
rules/aws_eks_rules/system_namespace_public_ip.yml
rules/gsuite_reports_rules/gsuite_drive_overly_visible.py
rules/gsuite_reports_rules/gsuite_drive_overly_visible.yml
rules/gsuite_reports_rules/gsuite_drive_visibility_change.py
rules/gsuite_reports_rules/gsuite_drive_visibility_change.yml
rules/okta_rules/okta_anonymizing_vpn_login.yml

Identified top 5 noisiest Panther managed rules and improved dedup and severity functions to better match the intent of the rules
* AWS.Software.Discovery - dedup on principalID, increase alert threshold to 50, dedup period to 6 hours
* AWS.CloudTrail.UnauthorizedAPICall - increase threshold and dedup period
* Amazon.EKS.Audit.SystemNamespaceFromPublicIP - dedup on source IP and increase dedup period
* GSuite.DriveVisibilityChanged - dedup on actor.user and increase dedup period
* Okta.Anonymizing.VPN.Login - decrease severity and increase dedup period
* Deleted duplicate deprecated GSuite.DriveVisibilityChanged rule
* make test

[sync] dedup and severity improvements for noisiest rules (#72)

---

rules/gcp_audit_rules/gcp_computeinstances_create_privilege_escalation.py
rules/gcp_audit_rules/gcp_computeinstances_create_privilege_escalation.yml

Detect compute.instances.create method for privilege escalation in GCP.
TA0004:T1548
The Identity and Access Management (IAM) service manages authorization and authentication for a GCP environment. This means that there are very likely multiple privilege escalation methods that use the IAM service and/or its permissions.
This method creates a new Compute Engine instance with a specified Service Account, then sends the token belonging to that Service Account to an external server. This means you don’t need to access the instance at all.
The following permissions are required for this method:
- compute.disks.create
- compute.instances.create
- compute.instances.setMetadata
- compute.instances.setServiceAccount
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- …

[sync] GCP compute.instances.create Privilege Escalation - rule (#63)

---

data_models/github_data_model.py

Updates GitHub data model to consider `action = 'team.add_repository' and permission = 'admin'` as an admin event for udm.assigned_admin_role and udm.get_event_type methods
* Adds a CONDITIONAL_ADMIN_EVENTS variable that considers events as admin related when permission also equals "admin"
* make test

[sync] GitHub Data Model Admin Actions update (#79)

---

lookup_tables/tor/tor_exit_nodes.yml
rules/gcp_k8s_rules/gcp_k8s_ioc_activity.yml

Adds a new `GCP.K8s.IOC.Activity` rule to mirror https://github.com/panther-labs/panther-analysis-internal/blob/main/queries/kubernetes_queries/kubernetes_ioc_activity.yml in GCP

[sync] Add GCP.K8s.IOC.Activity rule (#80)

---

rules/gcp_k8s_rules/gcp_k8s_privileged_pod_created.py
rules/gcp_k8s_rules/gcp_k8s_privileged_pod_created.yml

* Added rule to detect when GKE k8s privileged pods are being created ([JIRA ticket](https://panther-labs.atlassian.net/browse/TR-216))
* `pipenv run panther_analysis_tool test --path rules/gcp_k8s_rules/ --filter RuleID="GCP.K8S.Privileged.Pod.Created"`

[sync] GCP K8S Privileged Pod Created - rule (#81)

---

rules/standard_rules/impossible_travel_login.py

This fixes the standard login check to properly detect the use of Apple Private Relay. The second condition in all() is overly permissive in what's considered a private relay because it looks for _any_ service.

standard_rules/impossible_travel_login: set IS_PRIVATE_RELAY to true only when private relay is in use

---

Pipfile
Pipfile.lock

PAT just had a release. updating the version in the panther-analysis pipfile
* pipfile version bump

Update panther_analysis_tool version

---

packs/gcp_audit.yml
packs/netskope.yml
simple_rules/gcp_audit_rules/gcp_cloudbuild_potential_privilege_escalation_simple.yml
simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_create_simple.yml
simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_update_simple.yml
simple_rules/gcp_audit_rules/gcp_iam_roles_update_privilege_escalation_simple.yml
simple_rules/gcp_audit_rules/gcp_iam_service_account_key_create_simple.yml
simple_rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create_simple.yml
simple_rules/gcp_audit_rules/gcp_serviceusage_apikeys_create_privilege_escalation_simple.yml
simple_rules/gcp_k8s_rules/gcp_k8s_ioc_activity_simple.yml
simple_rules/gcp_k8s_rules/gcp_kubernetes_new_daemonset_deployed_simple.yml
simple_rules/netskope_rules/netskope_admin_logged_out_simple.yml
simple_rules/netskope_rules/netskope_admin_user_change_simple.yml
simple_rules/netskope_rules/netskope_many_deletes_simple.yml
simple_rules/netskope_rules/netskope_personnel_action_simple.yml
simple_rules/netskope_rules/netskope_unauthorized_api_calls_simple.yml

This PR adds a `.Simple` suffix to Simple Detection Rules in order to differentiate them from Python Rules.
* Adds a `.Simple` suffix to Simple Detection Rules
* Test pass as expected

Add .Simple suffix to Simple Rule IDs

---

simple_rules/gcp_k8s_rules/gcp_k8s_pod_using_host_pid_namespace_simple.yml

Add GCP.K8s.Pod.Using.Host.PID.Namespace rule to mirror https://github.com/panther-labs/panther-analysis-internal/blob/main/queries/kubernetes_queries/kubernetes_pod_using_host_pid_namespace.yml in GCP

[sync] Add GCP.K8s.Pod.Using.Host.PID.Namespace rule (#84)

---

simple_rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network_simple.yml

This detection monitor for the creation of pods which are attached to the host's network. This allows a pod to listen to all network traffic for all deployed computer on that particular node and communicate with other compute on the network namespace. Attackers can use this to capture secrets passed in arguments or connections.

Add GCP.K8s.Pod.Attached.To.Node.Host.Network.Simple rule

---

rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.py

Detection fails if volume  mount path is not present in log.

Fix GCP.K8S.Pot.Create.Or.Modify.Host.Path.Volume.Mount detection

---

Pipfile
Pipfile.lock

This week's PAT update which bumps PAT from `0.40.0` to `0.41.0`.
* Updates PAT via `make deps-update`
* `make fmt`, `make lint`, `make test`

Update PAT to 0.41.0

---

data_models/crowdstrike_fdr_data_model.yml

Rules that reference CrowdStrike source_ip datamodel field were returning None
* Updates CrowdStrike datamodel source_ip to $.aip
* make test returns expected IP instead of None

updates source_ip in crowdstrike datamodel to aip

---

global_helpers/global_helpers_test.py
global_helpers/panther_zoom_helpers.py

The [get_zoom_usergroup_context](https://github.com/panther-labs/panther-analysis/blob/release/global_helpers/panther_zoom_helpers.py#L26) function is returning IndexOutOfRange errors if there is no `-` in event's `operation_detail`  field

Fixed IndexOutOfRange error in get_zoom_usergroup_context

---

Pipfile
Pipfile.lock

PAT `0.42.0` had a regression with a reference before assignment error. This PR updates PAT to `0.43.0` which contains the fix.
* Updates PAT to `0.43.0`
* `make lint; make fmt; make test`

Update PAT to 0.43.0

---

Pipfile
Pipfile.lock

This PR updates PAT to `0.44.0` which should help with #1153 
* Updates PAT to `0.44.0`
* `make fmt; make lint; make test`

Update PAT to 0.44.0

---

CONTRIBUTING.md

We don't require a signed CLA for contributors now that we're using the Apache license.
* Removes the CLA reference from `CONTRIBUTING.md`
* N/A

Remove CLA reference from contribution guidelines

---

Dockerfile

Adds installation of prettier in Dockerfile.
* `make docker-build`
* Start container and run `make fmt` in it

Add npm install in dockerfile

---

.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/upload.yml

All of our Workflows were doing `make install` and then `make venv`. These duplicate the `pipenv --sync-dev` calls so they were redundant. 
We also don't need the `npm install` step for PRs, so this PR just uses `make venv` for all Workflows.
- Removes `make install` calls from all Workflows
Checks pass as expected.

Use make venv rather than make install

---

Pipfile
Pipfile.lock

This PR updates PAT to `0.45.0`.
* Updates PAT to `0.45.0`
* `make fmt; make lint; make test`

Update PAT to 0.45.0

---

.husky/pre-commit
Makefile
package-lock.json
package.json

Adds git pre-commit hook to format the source code.
- Moves `prettier` to a dev dependency
- Adds a `make fmt` pre-commit hook using [husky](https://typicode.github.io/husky/)
- Makes `prettier` print only the changed files
- Runs successfully before a git commit

Format code before committing it

---

rules/okta_rules/okta_password_accessed.py
rules/okta_rules/okta_password_accessed.yml

Problem is in the confusion between User and AppUser fields in logs. AppUser alternatId is only their name, User is their email for alternatId.
So the actor.alternateId is email and taken from User.
target.alternateId is name and taken from AppUser.
- fixed false positives for `Okta Password Accessed` rule ([Jira](https://panther-labs.atlassian.net/browse/THREAT-267))

fix - Okta Password Accessed False positive

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_2fa_disabled.py
rules/mongodb_rules/mongodb_2fa_disabled.yml

Detect when 2FA settings are disabled.
https://attack.mitre.org/techniques/T1556/006/ 
Check MongoDB Atlas logs for indicators of 2FA being disabled.
Disable 2FA settings in MongoDB Atlas to generate relevant events.
Assumes proper MongoDB logging.
Could be valid administrator activity.
Disable 2FA settings to trigger alerts. 
Medium
Re-enable 2FA settings and reset user credentials.
https://www.mongodb.com/docs/atlas/security-multi-factor-authentication/

Add MongoDB.2FA.Disabled rule

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_user_created_or_deleted.py
rules/mongodb_rules/mongodb_user_created_or_deleted.yml
rules/mongodb_rules/mongodb_user_roles_changed.py
rules/mongodb_rules/mongodb_user_roles_changed.yml

Detect when new users are added and deleted.  The severity of the alerts should be higher if the users have administrative privileges.
https://attack.mitre.org/techniques/T1136/003/ 
https://attack.mitre.org/techniques/T1531/ 
Looks for events in the MongoDB Atlas logs related to user creation and deletion.
Use the test MongoDB Atlas system to create/delete users to generate relevant events.
Assumes proper MongoDB Atlas logging.
Could be valid administrator activity
Create/delete users and admins to trigger alerts.  
Low if user, High if admin
Validate that the action was authorized and expected.
https://www.mongodb.com/docs/v4.2/tutorial/create-users/ 
https://www.mongodb.com/docs/atlas/reference/user-roles/

 Add MongoDB.User.Created.Or.Deleted and Add MongoDB.User.Roles.Changed rules

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_alerting_disabled.py
rules/mongodb_rules/mongodb_alerting_disabled.yml

Detect when security alerts are disabled or deleted.
https://attack.mitre.org/techniques/T1562/001/ 
MongoDB provides security alerting policies for notifying admins when certain conditions are met.  Detect when these policies are disabled or deleted.
Disable/delete security alerts in MongoDB Atlas to generate relevant logs.
Assumes proper MongoDB Atlas logging.
N/A
Disable/delete security alert settings to generate alerts in Panther instance.
High
Re-enable security alerts

MongoDB - alerting disabled (rule)

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_access_allowed_from_anywhere.py
rules/mongodb_rules/mongodb_access_allowed_from_anywhere.yml

Detect when 0.0.0.0 is added to the project's IP access list, which allows access from anywhere.
https://attack.mitre.org/techniques/T1021/ 
Atlas only allows client connections to the database deployment from entries in the project's IP access list. Detect when 0.0.0.0 is added to that list, which allows access from anywhere.
Allow access to project from anywhere to generate relevant logs.
Assumes proper MongoDB Atlas logging.
Could be legitimate administrator activity for specific project.
Allow access to project from anywhere to trigger alerts. 
Medium
Check if this activity was legitimate. If not, delete 0.0.0.0 from the list of allowed ips.
https://www.mongodb.com/docs/atlas/security/ip-access-list/

MongoDB - Allow access from anywhere (rule)

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_identity_provider_activity.py
rules/mongodb_rules/mongodb_identity_provider_activity.yml

Detect when changes are made to IDP settings
https://attack.mitre.org/techniques/T1556/007/ 
Changes to identity provider settings are privileged activities that should be carefully audited.  Attackers may add or change IDP integrations to gain persistence to environments
"FEDERATION_SETTINGS_CREATED" "FEDERATION_SETTINGS_DELETED" "FEDERATION_SETTINGS_UPDATED" "IDENTITY_PROVIDER_CREATED" "IDENTITY_PROVIDER_UPDATED" "IDENTITY_PROVIDER_DELETED" "IDENTITY_PROVIDER_ACTIVATED" "OIDC_IDENTITY_PROVIDER_UPDATED" "IDENTITY_PROVIDER_DEACTIVATED" "IDENTITY_PROVIDER_JWKS_REVOKED" "OIDC_IDENTITY_PROVIDER_ENABLED" "OIDC_IDENTITY_PROVIDER_DISABLED"
Assumes proper MongoDB Atlas logging
IDP related events could be legitimate administrative activity, but should be carefully reviewed to ensure the activity …

Add MongoDB.Identity.Provider.Activity rule

---

packs/mongodb.yml
rules/mongodb_rules/mongodb_logging_toggled.py
rules/mongodb_rules/mongodb_logging_toggled.yml

Add MongoDB.Logging.Toggled rule

Add MongoDB.Logging.Toggled rule

---

global_helpers/panther_base_helpers.py

MSFT Graph alert context included userStates, but not fileStates or hostStates.
- Add fileStates and hostStates to MSFT Graph alert context, if present
- make test

add file/host state to msft graph alert context

---

rules/aws_cloudtrail_rules/aws_iam_assume_role_blocklist_ignored.yml
rules/aws_cloudtrail_rules/aws_root_access_key_created.yml

Some of our test data timestamps was for the 0th day of the month, which doesn't exist. This would cause some YAML parsers to have the big sad when they tried to parse our rules, unless you took special care to configure them to ignore those invalid timestamps. This makes those timestamps valid.
- Make timestamps valid
- `pat test`

Fix timestamps

---

Pipfile
Pipfile.lock

This PR updates PAT to 0.48.0 and `panther_detection_helpers` to `0.4.0`. Both of these releases add Python 3.11 support.
- Updates PAT to `0.48.0`
- Updates PDH to `0.4.0`
- `make fmt; make lint; make test`

Update PAT to 0.48.0; PDH to 0.4.0

---

.github/workflows/check-packs.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/sync-from-upstream.yml
.github/workflows/test.yml
.github/workflows/upload.yml
Pipfile
Pipfile.lock
dependabot.yml

Several of our upstream Actions were outdated and were not pinned to known versions. This PR updates them and uses the known SHA.
- Updates outdated Actions; uses the SHA for the latest version
- CI Checks pass as expected

Update Action versions; use SHAs

---

rules/gcp_audit_rules/gcp_storage_hmac_keys_create.py
rules/gcp_audit_rules/gcp_storage_hmac_keys_create.yml

python from sdyaml
One rule was still in sdyaml format
- replaces Detection yaml logic with python rule function
- make test

migrates the gcp_storage_hmac_keys_create rule to

---

rules/push_security_rules/push_security_app_banner_acknowledged.py
rules/push_security_rules/push_security_app_banner_acknowledged.yml
rules/push_security_rules/push_security_mfa_method_changed.py
rules/push_security_rules/push_security_mfa_method_changed.yml
rules/push_security_rules/push_security_new_app_detected.py
rules/push_security_rules/push_security_new_app_detected.yml
rules/push_security_rules/push_security_new_saas_account_created.py
rules/push_security_rules/push_security_new_saas_account_created.yml
rules/push_security_rules/push_security_open_security_finding.py
rules/push_security_rules/push_security_open_security_finding.yml
rules/push_security_rules/push_security_phishable_mfa_method.py
rules/push_security_rules/push_security_phishable_mfa_method.yml
rules/push_security_rules/push_security_phishing_attack.py
rules/push_security_rules/push_security_phishing_attack.yml
rules/push_security_rules/push_security_unauthorized_idp_login.py
rules/push_security_rules/push_security_unauthorized_idp_login.yml

Rule for Push Security webhook events

Push Security rules

---

.github/dependabot.yml
.github/workflows/check-packs.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/sync-from-upstream.yml
.github/workflows/test.yml
.github/workflows/upload.yml

Relates to: EPD-370
Pinning Action versions to the full SHA rather than the version is a best practice from a supply chain security perspective. Dependabot will handle any updates for us.
* Moves all Actions to their latest respective commit SHA
* Checks still pass as expected

Use full Action SHAs rather than versioned releases

---

queries/auth0_queries/auth0_cic_credential_stuffing_query.yml
rules/auth0_rules/auth0_cic_credential_stuffing.py
rules/auth0_rules/auth0_cic_credential_stuffing.yml

Okta has determined that the cross-origin authentication feature in Customer Identity Cloud (CIC) is prone to being targeted by threat actors orchestrating credential-stuffing attacks.  Okta has observed suspicious activity that started on April 15.  Review tenant logs for unexpected fcoa, scoa, and pwd_leak events.
https://attack.mitre.org/techniques/T1110/004/ 
Log Events to Review:
fcoa - Failed cross-origin authentication
scoa - Successful cross-origin authentication
pwd_leak - Someone attempted to login with a leaked password
In this type of attack, adversaries attempt to sign-in to online services using large lists of usernames and passwords potentially obtained from previous data breaches or unrelated entities, or from phishing or malware campaigns.
Assumes use of Customer Identity …

THREAT-321 Auth0 CIC Credential Stuffing

---

Pipfile.lock

PA counterpart of https://github.com/panther-labs/panther_analysis_tool/pull/510
Removing the `panther-core` pin in PAT's `setup.py` resolved the issue we were seeing with downgrades.
- Runs `make deps-update` to update PAT (and, more importantly, `panther-core`
- Pipfile.lock is correct
- Tests pass as expected

Update panther-core to 0.10.1 via PAT

---

.github/workflows/check-packs.yml

Relates to: https://panther-labs.atlassian.net/browse/EPD-437

Using GITHUB_OUTPUT env var instead of old ::set-output shorthand

---

packs/aws_decoy.yml
rules/aws_securityfinding_rules/decoy_dynamodb_accessed.py
rules/aws_securityfinding_rules/decoy_dynamodb_accessed.yml
rules/aws_securityfinding_rules/decoy_iam_assumed.py
rules/aws_securityfinding_rules/decoy_iam_assumed.yml
rules/aws_securityfinding_rules/decoy_s3_accessed.py
rules/aws_securityfinding_rules/decoy_s3_accessed.yml
rules/aws_securityfinding_rules/decoy_secret_accessed.py
rules/aws_securityfinding_rules/decoy_secret_accessed.yml
rules/aws_securityfinding_rules/decoy_systems_manager_parameter_accessed.py
rules/aws_securityfinding_rules/decoy_systems_manager_parameter_accessed.yml

Detect access to AWS honeypot resources
Honeypots, Deception
This post focuses on another approach of creating private decoy resources in your account that are intended to look legitimate, but don’t have any useful or sensitive data and are not exposed publicly. These decoys are designed to alert you about suspicious activities that could indicate AWS credentials exposure or account compromise. You can use the decoys in conjunction with other techniques, such as creating deception environments and public and private honeypots to better detect suspicious activity in your accounts and applications.
Technical Context provides detailed information and background needed for a responder to understand all components of the alert. This should appropriately link to any platform or tooling …

AWS Honeypot Detections threat-306

---

Pipfile
Pipfile.lock

This PR updates PAT from `0.49.2` to `0.50.0`.
- Updates PAT to `0.50.0` via `make deps-update`
- Tests pass as expected

Update PAT to 0.50.0

---

Pipfile.lock

PAT `0.50.1` contains a small Regex fix.
- Updates PAT to `0.50.1` via `make deps-update`
- Tests pass as expected

Update PAT to 0.50.1

---

rules/okta_rules/okta_anonymizing_vpn_login.py
rules/okta_rules/okta_anonymizing_vpn_login.yml

Some customers have reported a high false-positive rate for this rule from employees signing in from apple devices using Apple Private Relay. While it's true that Apple Relay is an annonymizing service, the majority of logins from the Relay will be genuine. This PR will cause any alerts generated by Apple Relay logins to be INFO severity, allowing them to be recorded and referencable, but not forwarded to analysts for investigation.
- Added a `severity` function to change the alert severity to INFO if `ipinfo_privacy` determines the source IP belongs to Apple Relay
- Added a unit test for a mocked Apple Relay login
- Ran all test cases, confirmed they passed with the expected severities (where applicable)

Edit: Downgrade Okta.Anonymizing.VPN.Login to INFO severity if Apple Relay used

---

Dockerfile

There's no reason to run `pipenv uninstall --all` in a hermetic environment (hence the failure).
- Removes `pipenv uninstall --all` `RUN` directive.
- Image builds successfully

Remove unnecessary pipenv step

---

Pipfile
Pipfile.lock

This PR updates PAT to `0.51.0`.
- Updates PAT to `0.51.0` via `make deps-update`
- Tests pass as expected

Update PAT to 0.51.0

---

rules/crowdstrike_rules/crowdstrike_unusual_parent_child_processes.py

Explorer launching powershell isn't a critical alert. Explorer and CMD launching powershell are the two most common ways to execute the application. Any regular powershell user is likely to trigger this daily. 
The relationships present is the rule are not a strong match for the underlying "T1036.005 Masquerading: Match Legitimate Name or Location" used in the rule reference https://medium.com/falconforce/falconfriday-e4554e9e6665. That technique is meant to be tagged to approximate names or locations of legitimate system files and this rule has no logic to account for that, the rule is no more than `if match(parent and child): alert critical`. Today this rule is largely for unusual executions of powershell or cmd from office or svchost binaries.
Either remove this relationship entirely, …

Remove explorer/powershell relationship

---

.github/workflows/release.yml
.github/workflows/upload.yml
correlation_rules/snowflake_data_exfiltration.yml
packs/snowflake.yml
queries/snowflake_queries/scheduled_rule_default_snowflake.py
queries/snowflake_queries/snowflake_file_downloaded_query.yml
queries/snowflake_queries/snowflake_file_downloaded_signal.yml
queries/snowflake_queries/snowflake_table_copied_into_stage_query.yml
queries/snowflake_queries/snowflake_table_copied_into_stage_signal.yml
queries/snowflake_queries/snowflake_temp_stage_created_query.yml
queries/snowflake_queries/snowflake_temp_stage_created_signal.yml

snowflake data exfiltration
In April 2024, Mandiant received threat intelligence on database records that were subsequently determined to have originated from a victim’s Snowflake instance. Mandiant notified the victim, who then engaged Mandiant to investigate suspected data theft involving their Snowflake instance. During this investigation, Mandiant determined that the organization’s Snowflake instance had been compromised by a threat actor using credentials previously stolen via infostealer malware. The threat actor used these stolen credentials to access the customer’s Snowflake instance and ultimately exfiltrate valuable data. At the time of the compromise, the account did not have multi-factor authentication (MFA) enabled. …

Snowflake Data Exfiltration CR

---

queries/aws_queries/cloudtrail_2_minute_count_query.yml
rules/carbonblack_rules/cb_audit_flagged.yml

Some of our YAML files use tabs instead of spaces, which is discouraged by YAML spec. [See this conversation in Slack](https://panther-labs.slack.com/archives/C0719AH18SV/p1721055874307739) for additional context.
- This PR replaces all tabs with spaces in our YAML files.
- `pat validate` succeeded

Formatting: Converting Tabs to Spaces in YAML Files

---

correlation_rules/okta_login_without_push.yml
correlation_rules/potential_compromised_okta_credentials.yml
packs/multisource_correlations.yml
rules/okta_rules/okta_login_signal.py
rules/okta_rules/okta_login_signal.yml
rules/okta_rules/okta_login_without_push_marker.py
rules/okta_rules/okta_login_without_push_marker.yml
rules/push_security_rules/push_security_authorized_idp_login.py
rules/push_security_rules/push_security_authorized_idp_login.yml

Correlation rules for Push Security log source
- 2 correlation rules for Push Security + Okta
- pat validate

Push Security correlation rules

---

rules/gcp_audit_rules/gcp_cloud_run_set_iam_policy.py
rules/gcp_audit_rules/gcp_cloud_run_set_iam_policy.yml

This unsafe lookup is triggering `AttributeError("'NoneType' object has no attribute 'endswith'")` for some customers.
- Ensure a safe default is set for this case
- Added a new unit test that covers this code path

Update safe lookup

---

correlation_rules/aws_cloudtrail_stopinstance_followed_by_modifyinstanceattributes.yml
correlation_rules/aws_potentially_compromised_service_role.yml
correlation_rules/aws_privilege_escalation_via_user_compromise.yml
correlation_rules/aws_user_takeover_via_password_reset.yml
correlation_rules/gcp_cloud_run_service_create_followed_by_set_iam_policy.yml
correlation_rules/github_advanced_security_change_not_followed_by_repo_archived.yml
correlation_rules/okta_login_without_push.yml
correlation_rules/potential_compromised_okta_credentials.yml
correlation_rules/secret_exposed_and_not_quarantined.yml
correlation_rules/snowflake_data_exfiltration.yml

Some customers were experiencing timeouts from some of the new OOTB Correlation Rules. This bumps the default timeout for some of the Correlation Rules with 1 hour+ lookback windows. In particular there was a two or three minute timeout for some Correlation Rules looking back at 12-24 hours of data.
- For Correlation Rules with lookback windows over 1 hour, increase the default timeout
- Actually, bumped everything based on some feedback from users in high volume environments
- pat test

Update default timeouts

---

rules/slack_rules/slack_user_privilege_escalation.py
rules/slack_rules/slack_user_privilege_escalation.yml

Updating the Slack Audit log UserPrivilegeEscalation to correctly user target instead of actor. We got alerts for our IT team promoted to Admin or Owner. Realized it was an error in the alert and corrected it. 
- Updated the Slack UserPrivilegeEscalation alert to correctly differentiate between the actor and target. Actor being the user making the change and target being the user, the chances are occurring on.
- Used the already definded dict `USER_PRIV_ESC_ACTIONS` for alert Titles
- Updated alert Titles to correctly reference the target instead of the actor. 
- Add local variable `action` to improve readability.
- Updated tests to test the new behavior
- Updated tests to be YAML
- Formatted YAML file with Prettier
- `pipenv run panther_analysis_tool test --skip-disabled-tests …

Correct the target and actor in Slack Audit log UserPrivilegeEscalation plus clean up

---

rules/slack_rules/slack_user_privilege_escalation.yml

Noticed that the move from JSON to YAML had caused the addition of the `entity` block to be missed. The tests therefore show `unknown-actor` and `unknown-email`. This does not impact the functionality issue but could lead to confusion. 
```
Slack.AuditLogs.UserPrivilegeEscalation
[PASS] Permissions Assigned
[PASS] [title] Slack User Assigned Permissions <unknown-actor> (<unknown-email>)
[PASS] [dedup] Slack User Assigned Permissions <unknown-actor> (<unknown-email>)
[PASS] [alertContext] {"actor-name": "username", "actor-email": "user@example.com", "actor-ip": "1.2.3.4", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
[PASS] [severity] MEDIUM
[PASS] Role Changed to Admin
[PASS] [rule] …
```

Add entity JSON object to Slack Privilege Escalation tests

---

correlation_rules/aws_potentially_compromised_service_role_cr.yml
correlation_rules/github_advanced_security_change_not_followed_by_repo_archived.yml
queries/aws_queries/aws_potentially_compromised_service_role.yml

Rules cannot be converted from one analysis type to another while keeping the same RuleID.
- Reintroduces `AWS.Potentially.Stolen.Service.Role` as deprecated and changes RuleID of the new scheduled rule
- Reverts `GitHub.Advanced.Security.Change.NOT.FOLLOWED.BY.Repo.Archived` to Sequence CR with order reversed
- pat validate
- pat upload

CR upload fixes

---

correlation_rules/aws_potentially_compromised_service_role_cr.yml
correlation_rules/github_advanced_security_change_not_followed_by_repo_archived.yml
queries/aws_queries/aws_potentially_compromised_service_role.yml

Prepare for v3.61.0 release
- consolidate commits from release branch
- pat upload

Prepare for `v3.61.0`

---

rules/auth0_rules/auth0_user_invitation_created.yml
rules/auth0_rules/auth0_user_joined_tenant.yml
rules/aws_cloudtrail_rules/aws_ecr_crud.yml
rules/aws_cloudtrail_rules/aws_ecr_events.yml
rules/aws_cloudtrail_rules/aws_iam_group_read_only_events.yml
rules/aws_cloudtrail_rules/aws_s3_activity_greynoise.yml
rules/aws_cloudtrail_rules/aws_software_discovery.yml
rules/box_rules/box_new_login.yml
rules/box_rules/box_untrusted_device.yml
rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.yml
rules/gcp_audit_rules/gcp_logging_sink_modified.yml
rules/microsoft_rules/microsoft_graph_passthrough.py
rules/okta_rules/okta_geo_improbable_access.yml

Related to #1327 , limited to info rules which are not currently being routed to alert destinations.
Info severity alerts are auto-closed and primarily used as signal generators for correlation rules.  This change stores matches in the Signals table for correlations, while keeping them off the alert interface.
- Set CreateAlert: false for Info severity rules which are not currently being routed to alert destinations.
- pat test

Info Alerts are Signals, Nonrouted

---

rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.py
rules/aws_cloudtrail_rules/aws_ec2_traffic_mirroring.yml

EC2 traffic mirroring rule is noisy in many environments.
- Don't alert on Describe events
- Longer dedup window
- make test

traffic mirroring tuning

---

rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.py
rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.yml
rules/gcp_k8s_rules/gcp_k8s_privileged_pod_created.py
rules/gcp_k8s_rules/gcp_k8s_privileged_pod_created.yml

Tuning 2 noisy GCP K8S alerts
- dedup on actor name
- longer dedup period
- make test

GCP K8S tuning

---

rules/aws_cloudtrail_rules/aws_snapshot_made_public.py
rules/aws_cloudtrail_rules/aws_snapshot_made_public.yml

Customers have complained that a significant number of alerts from `AWS.CloudTrail.SnapshotMadePublic` are due to a Snapshot being shared with an individual user. Some would argue that "sharing with a single user" and "made public to all users" are 2 different actions entirely. This PR alters the rule to still track individual shares for reference, but only alert if a snapshot is truly made public.
- Added a dynamic severity function to `AWS.CloudTrail.SnapshotMadePublic`, which returns `INFO` if the snapshot has only been shared with a single person, as opposed to a group.
- Added a new unit test for a single-user share, and confirmed the alert is generated at INFO severity.

Add Dynamic Severity to AWS.CloudTrail.SnapshotMadePublic

---

global_helpers/crowdstrike_event_streams_helpers.py
rules/crowdstrike_rules/event_stream_rules/crowdstrike_ip_allowlist_changed.py
rules/crowdstrike_rules/event_stream_rules/crowdstrike_single_ip_allowlisted.py

`pypanther`'s testing suite always runs the auxiliiary functions (`title`, `dedup`, `alert_context`, etc.) regardless of whether the unit test is expected to return True or False. This is different from PAT's behaviour, where those functions only run when the unit test has `ExpectedResult=True`. Due to this expectation, some rules have auxilliary functions designed in a way where they don't execute properly for all test logs. This PR addresses the problem with 2 of our rules.
- Added logic to 2 rules to ensure they don't raise exceptions when processing log events for all tests
- Confirmed that ALL tests pass when using both PAT and `pypanther`

Fix Unit Tests Failing in Pypanther

---

rules/aws_cloudtrail_rules/aws_cloudtrail_account_discovery.yml
rules/aws_cloudtrail_rules/aws_unauthorized_api_call.yml
rules/aws_eks_rules/system_namespace_public_ip.yml

These 3 info alerts are intended to be used in conjunction with correlation rules or as part of investigation of other alerts.  With the introduction of Signals we are converting them from info alerts to Signals.
- CreateAlert: false
- pat test

Convert to Signals

---

rules/aws_cloudtrail_rules/aws_saml_activity.py

Automated tools can attempt to delete SAML providers multiple times, causing false positives.
- Only alert when no errorCode is present in the log
- pat test

AWS SAML Activity Tuning

---

packs/asana.yml
packs/atlassian.yml
packs/aws.yml
packs/azure_signin.yml
packs/box.yml
packs/cisco_umbrella_dns.yml
packs/cloudflare.yml
packs/credential_security.yml
packs/crowdstrike.yml
packs/crowdstrike_event_streams.yml
packs/gsuite_reports.yml
packs/multisource_correlations.yml
packs/notion.yml
packs/onelogin.yml
packs/slack.yml
packs/standard_ruleset.yml
packs/wiz.yml
packs/zoom.yml

Some of the detections used in packs are generic (i.e. they can be used for other log types, and the use data models to do so). In such cases, the unit tests will fail if the data models for those log types aren't present. Additionally, some packs were missing global helpers (either because a new rule was added, or because the top-level helper was included in the pack, but it's dependencies weren't.)
For CI/CD users, these changes are moot, since they always upload the full repo, but for Console users, this can lead to missing dependencies when enabling packs.
For more information, [see this ticket in #ask](https://panther-labs.slack.com/archives/C0719AH18SV/p1725391042439389?thread_ts=1722285039.363829&cid=C0719AH18SV).
- If a rule in a pack can be used for a certain log type, the data …

Update Pack Manifests with Data Models and Globals

---

data_models/gcp_data_model.py
data_models/gcp_data_model.yml
rules/gcp_audit_rules/gcp_iam_service_accounts_get_access_token_privilege_escalation.py
rules/gcp_audit_rules/gcp_iam_service_accounts_get_access_token_privilege_escalation.yml

A customer was receiving alerts from the out-of-the-box (OOTB) detection `GCP IAM serviceAccounts getAccessToken Privilege Escalation`. The alert message included `[GCP]: [<ACTOR_NOT_FOUND>] performed [GenerateAccessToken] on project`, which indicated that Panther's data model did not recognize the actor correctly.
Upon investigation, we found that the issue arose because the GCP Audit schema in Panther was only mapping the `principalEmail` field as the `actor_user`, while for third-party identity callers, GCP populates the `principalSubject` field instead of `principalEmail`. This behavior is confirmed by the [GCP documentation](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog#authenticationinfo).
- Added a method `get_actor_user` to use …

added get_actor_user method to data model

---

packs/aws.yml
packs/okta.yml
packs/onepassword.yml
queries/aws_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device_FDREvent.yml
queries/crowdstrike_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device_Query.yml
queries/crowdstrike_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device_Query.yml
queries/crowdstrike_queries/onepass_login_from_crowdstrike_unmanaged_device_query.yml
queries/okta_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device_FDREvent.yml
queries/onepassword_queries/onepass_login_from_crowdstrike_unmanaged_device_FDREvent.yml

Some of the queries recently added to packs involve more than one table, which may result in the pack failing to update if the customer has not ingested the corresponding log types yet.
Typically, each pack contains items focusing a single log type (or family of log types). When a customer creates a log source for those log types and ingests data, the data lake tables for those log types are also created. In some queries (namely the "Unauthorized Crowdstrike Device" queries), 2 tables are referenced: a crowdstrike table, and whichever log table the pack utilizes. If the customer hasn't previously ingested crowdstrike logs, the crowdstrike table won't exist, and the query will fail to compile (leading to the pack failing to update).
The same issue can happen if we move these queries to the …

Remove Multi-Table Queries from Packs

---

correlation_rules/notion_account_changed_after_login.yml
correlation_rules/onelogin_successful_login_after_high_risk_failed_login.yml
packs/notion.yml
packs/onelogin.yml
rules/notion_rules/notion_account_changed.py
rules/notion_rules/notion_account_changed.yml
rules/notion_rules/notion_account_changed_after_login.yml
rules/notion_rules/notion_login.py
rules/notion_rules/notion_login.yml
rules/onelogin_rules/onelogin_high_risk_login.yml
rules/onelogin_rules/onelogin_login.py
rules/onelogin_rules/onelogin_login.yml

Converted two caching rules to correlation:
- Notion.AccountChangedAfterLogin
- OneLogin.HighRiskLogin

THREAT-354 Converting caching rules to correlation

---

.github/workflows/check-mitre.yml
.scripts/mitre_mapping_check.py
Makefile

If a rule has a MITRE ATT&CK report mapping with an invalid format, the mapping doesn't resolve properly in the UI. This PR adds some automation to check for misformatted MITRE mappings and alert on them.
See [this PR](https://github.com/panther-labs/panther-analysis/pull/1322) for more details.
This check didn't really fit as part of `pat validate` or `pat test`, since it's concerned with the format of the YAML file, so we chose to add it a script that can be run as part of `make lint`.
- added a `.scripts` directory, with a python script to check the mapping formats
- automatically run the script when `make lint` is invoked
- Artificially misformatted a MITRE mapping and confirmed the script alerted on it when using `make lint`, and confirm it didn't raise any false positives when no …

Add Format Checker for MITRE ATT&CK Matrix Report Mappings

---

Pipfile
Pipfile.lock
global_helpers/panther_sublime_helpers.py
global_helpers/panther_sublime_helpers.yml
packs/sublime.yml
rules/sublime_rules/sublime_mailboxes_deactivated.py
rules/sublime_rules/sublime_mailboxes_deactivated.yml
rules/sublime_rules/sublime_message_flagged.py
rules/sublime_rules/sublime_message_flagged.yml
rules/sublime_rules/sublime_message_source_deleted_or_deactivated.py
rules/sublime_rules/sublime_message_source_deleted_or_deactivated.yml
rules/sublime_rules/sublime_rules_deleted_or_deactivated.py
rules/sublime_rules/sublime_rules_deleted_or_deactivated.yml

Added Sublime Security Rules for such logs
- rules.deactivate
- rules.delete
- message_source.deactivate_mailboxes
- message_source.deactivate
- message_source.delete

THREAT-387 Sublime Security Rules

---

rules/aws_cloudtrail_rules/aws_security_configuration_change.py
rules/aws_cloudtrail_rules/aws_security_configuration_change.yml

Fixes https://github.com/panther-labs/panther-analysis/issues/466
- Adds a mock to the invalid rule test
- Removes hardcoded example ALLOW_LIST
- make test

Fix issue 466: Add mock to rule test

---

rules/github_rules/github_action_failed.py

While prepping for the GitHub podcast, I ran across a few small QoL improvements to this rule
- don't use deep_get for single-level nesting
- change the ordering of the `all()` call
- locally

Clean up GitHub rule

---

packs/auth0.yml
packs/aws.yml
packs/gcp_audit.yml
packs/gcp_k8.yml
packs/github.yml
packs/multisource_correlations.yml
packs/snowflake.yml
queries/crowdstrike_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device.yml
queries/crowdstrike_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device.yml
queries/crowdstrike_queries/onepassword_login_from_crowdstrike_unmanaged_device.yml
queries/dropbox_queries/Dropbox_Many_Deletes.yml
queries/dropbox_queries/Dropbox_Many_Downloads.yml
rules/github_rules/github_repo_hook_modified.yml
rules/gitlab_rules/gitlab_audit_password_reset_multiple_emails.yml
rules/gitlab_rules/gitlab_production_password_reset_multiple_emails.yml
templates/example_scheduled_rule.yml

After revamping the `check-packs` function in PAT, we discovered a number of rules that weren't assigned to any Packs. This PR either assigns them to a pack, or adds an exception tag to exclude them from the check.
- Added a new pack for GCP K8s
- Added exceptions for the Crowdstrike Unmanaged Device rules
- A bunch of other rules got added or excluded from packs
- `pat check-packs` passed, so there shouldn't be any issues with missing pack dependencies
- `pat validate` passed
- All of these rules have already existed in the repo, so if they have noise issues/bugs, we should know about them by now. They should be fine to add to packs.

Add Unpacked Items to Packs

---

rules/standard_rules/impossible_travel_login.py
rules/standard_rules/impossible_travel_login.yml

[Intelsat](https://www.intelsat.com/) provides in-flight wifi for a number of airlines (American, Alaska, etc) among other mobile services but like any ASN provides geographic information for a fixed spot on the globe. This leads to false positives when persons using in-flight wifi have login activity shortly before or after a login from in-flight. An example:
- Login from LAX airport before boarding a flight at 17:00
- Login from Intelsat in-flight wifi at 17:30 tied to Tysons Landing, Virginia. 
Adds a check on `ipinfo_asn` lookups and excludes Intelsat's ASN `AS22351` from triggering the rule or being included in `new_login_stats`. Any additional satellite network ASNs identified can be added to the `SATELLITE_NETWORK_ASNS `constant. 
- New test for a true positive impossible travel …

Filter out Intelsat satellite network plane wifi from Impossible Travel

---

.github/workflows/check-deprecated.yml
.scripts/deleted_rules.py
rules/gsuite_activityevent_rules/gsuite_workspace_calendar_external_sharing.py

Linter in Github Action fails with:
```
rules/gsuite_activityevent_rules/gsuite_workspace_calendar_external_sharing.py:20:0: W1404: Implicit string concatenation found in call (implicit-str-concat)
```
- Explicitly join the strings.
- Updates Check Removed Rules workflow to use the `develop` branch.

Fix linter error in gsuite_workspace_calendar_external_sharing.py

---

.scripts/mitre_mapping_check.py

Schema test files typically contain multiple documents, separated by dashes. The Analysis Spec loader used by Panther Analysis Tool doesn't support such files, and causes errors if they are present in the repo when `make lint-mitre` is run. Since schema tests do not contain MITRE mappings, we added an exclusion pattern to prevent schema test files from being loaded by the script.
- Added a check to ignore any files with names matching `*_tests.y*ml` from the linting script
- Tested script with several schema test files in repo, each containing multiple documents, and confirmed that no errors occurred

Configure `lint-mitre` to ignore schema test files

---

queries/aws_queries/cloudtrail_password_spraying_query.yml
queries/aws_queries/ec2_crud_activity_by_role_query.yml
queries/aws_queries/ec2_crud_activity_by_useragent_query.yml
queries/aws_queries/vpc_dns_tunneling_query.yml
queries/okta_queries/okta_activity_audit.yml
queries/okta_queries/okta_admin_access_granted.yml
queries/okta_queries/okta_mfa_password_reset_audit.yml
queries/okta_queries/okta_session_id_audit.yml
queries/okta_queries/okta_support_access.yml
queries/snowflake_queries/snowflake_0108977_configuration_drift_query.yml
queries/snowflake_queries/snowflake_0108977_configuration_drift_threat_hunting.yml
queries/snowflake_queries/snowflake_0108977_ip_query.yml
queries/snowflake_queries/snowflake_0108977_ip_threat_hunting.yml
queries/snowflake_queries/snowflake_0108977_suspected_user_access_query.yml
queries/snowflake_queries/snowflake_0108977_suspected_user_access_threat_hunting.yml
queries/snowflake_queries/snowflake_0108977_suspected_user_activity_threat_hunting.yml
queries/snowflake_queries/snowflake_account_admin_assigned_query.yml
queries/snowflake_queries/snowflake_brute_force_ip_query.yml
queries/snowflake_queries/snowflake_brute_force_username_query.yml
queries/snowflake_queries/snowflake_external_shares_query.yml
queries/snowflake_queries/snowflake_key_user_password_login_query.yml
queries/snowflake_queries/snowflake_login_without_mfa_query.yml
queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success_query.yml
queries/snowflake_queries/snowflake_user_created_query.yml
queries/snowflake_queries/snowflake_user_enabled_query.yml
templates/example_scheduled_query.yml

Panther no longer supports a different backend than Snowflake, and having multiple different fields to specify a scheduled query's SQL body has caused confusion. By pruning all references to `AthenaQuery` and `SnowflakeQuery`, we can make our repo consistent with our recommended best practices for customers.
- removed all `AthenaQuery` fields
- renamed all `SnowflakeQuery` fields to `Query`
- `pat validate` passes

Migrate `AthenaQuery` and `SnowflakeQuery` to just `Query`

---

rules/gsuite_activityevent_rules/gsuite_external_forwarding.py
rules/gsuite_activityevent_rules/gsuite_external_forwarding.yml

A customer raised an issue with the current detection - email forwarding change events can come from applications with name `user_accoutns` or `login`. They observed events where `applicationName=login` did not raise alerts. We confirmed this behaviour and updated the rule.
- restrict `applicationName` to `login` or `user_accounts` instead of just `user_accounts`
- used a recent email forwarding event from our own logs as a test case

Allow 'applicationName=login` for `GSuite.ExternalMailForwarding`

---

rules/gsuite_reports_rules/gsuite_drive_external_share.py
rules/gsuite_reports_rules/gsuite_drive_external_share.yml

Request for  in exception pattern. This approach would enable the creation of rules such as:
• allow anyone to share with a specific address
• allow a specific sender address to share with anyone
• and everything in between
- added sender-receiver pairs in exception pattern
- `pat test`

ASK-833   `GSuite.Drive.ExternalFileShare` sender-receiver pairs in EXCEPTION_PATTERN

---

packs/aws.yml
policies/aws_waf_policies/aws_waf_logging_configured.py
policies/aws_waf_policies/aws_waf_logging_configured.yml

This PR adds a new detection rule that ensures AWS WAF (Web Application Firewall) logging is configured and sending logs to valid destinations, such as Amazon S3, CloudWatch Logs, or Kinesis Firehose. Proper logging is essential for monitoring AWS WAF activity.
Python policy file: aws_waf_logging_configured.py
This file contains logic to validate if AWS WAF logging is configured to a valid destination (S3, CloudWatch Logs, or Kinesis Firehose).
It checks the LoggingConfiguration field in AWS WAF resources and validates the destination ARNs.
Metadata file: aws_waf_logging_configured.yml
Adds metadata for the new rule, specifying:
PolicyID: "AWS.WAF.LoggingConfigured"
Severity: High
Tags for easier categorization
Includes test cases for different logging configurations (e.g., valid/invalid …

Add AWS WAF Logging Configured Policy

---

global_helpers/panther_aws_helpers.py

Closes #1403
`aws_guardduty_context` helper function does not include `accountId` in the alert context
- Includes `accountId` in the dict returned by `aws_guardduty_context`

feat: include accountId in aws_guardduty_context

---

correlation_rules/aws_cloudtrail_stopinstance_followed_by_modifyinstanceattributes.yml
correlation_rules/aws_console_sign-in_without_okta.yml
correlation_rules/aws_privilege_escalation_via_user_compromise.yml
correlation_rules/aws_sso_access_token_retrieved_by_unauthenticated_ip.yml
correlation_rules/aws_user_takeover_via_password_reset.yml
correlation_rules/gcp_cloud_run_service_create_followed_by_set_iam_policy.yml
correlation_rules/github_advanced_security_change_not_followed_by_repo_archived.yml
correlation_rules/notion_login_followed_by_account_change.yml
correlation_rules/okta_login_without_push.yml
correlation_rules/onelogin_successful_login_after_high_risk_failed_login.yml
correlation_rules/potential_compromised_okta_credentials.yml
correlation_rules/secret_exposed_and_not_quarantined.yml
correlation_rules/snowflake_data_exfiltration.yml
rules/crowdstrike_rules/event_stream_rules/crowdstrike_ephemeral_user_account.yml
rules/crowdstrike_rules/event_stream_rules/crowdstrike_new_admin_user_created.yml

Correlation rules that run too frequently are very cost-ineffective. This PR defaults all managed CRs to running once per day and looking back over the past 36 hours (while respecting the relative time constraints between events using `WithinTimeFrameMinutes`.
- adjusted all CR schedule `RateMinutes` to 1440 (24 hours)
- adjusted all CR `LookbackWindowMinutes` to 2160 (36 hours) to allow for log latency
- added `WithinTimeFrameMinutes` to transitions to preserve the original lookback window
- `make test`
- `pat validate`

Adjust CR Schedules and Lookbacks

---

global_helpers/panther_aws_helpers.py
global_helpers/panther_box_helpers.py
global_helpers/panther_cloudflare_helpers.py
global_helpers/panther_crowdstrike_fdr_helpers.py
global_helpers/panther_duo_helpers.py
global_helpers/panther_lookuptable_helpers.py
global_helpers/panther_okta_helpers.py

Some alert context helpers were erroneously typing `event: dict`.   This breaks some things after PyPanther conversion because events are type PantherEvent.
- Remove dict typing from alert context helpers
- make test

Fix event dict typing

---

global_helpers/panther_wiz_helpers.py
rules/wiz_rules/wiz_cicd_scan_policy_updated_or_deleted.py
rules/wiz_rules/wiz_connector_updated_or_deleted.py
rules/wiz_rules/wiz_data_classifier_updated_or_deleted.py
rules/wiz_rules/wiz_image_integrity_validator_updated_or_deleted.py
rules/wiz_rules/wiz_integration_updated_or_deleted.py
rules/wiz_rules/wiz_revoke_user_sessions.py
rules/wiz_rules/wiz_rotate_service_account_secret.py
rules/wiz_rules/wiz_rule_change.py
rules/wiz_rules/wiz_saml_identity_provider_change.py
rules/wiz_rules/wiz_service_account_change.py
rules/wiz_rules/wiz_update_ip_restrictions.py
rules/wiz_rules/wiz_update_login_settings.py
rules/wiz_rules/wiz_update_scanner_settings.py
rules/wiz_rules/wiz_update_support_contact_list.py
rules/wiz_rules/wiz_user_created_or_deleted.py
rules/wiz_rules/wiz_user_role_updated_or_deleted.py

Wiz audit logs events can have a service account as an actor. This isn't currently reflected properly in alert titles.
- Add a helper function to determine if the actor is a user or service account.
- Update all rules to use this logic in their titles.
- These changes have been tested on a Wiz log source for the last few weeks.

Fix Wiz Audit Log Titles for Service Account Actors

---

deprecated.txt
packs/gcp_k8.yml
rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.yml

fixing ruleID typo on gcp_k8s_pod_create_or_modify_host_path_vol_mount.yml

---

queries/okta_queries/okta_52_char_username_threat_hunt.yml

On October 30, 2024, a vulnerability was internally identified in generating the cache key for AD/LDAP DelAuth. The Bcrypt algorithm was used to generate the cache key where we hash a combined string of userId + username + password. Under a specific set of conditions, listed below, this could allow users to authenticate by providing the username with the stored cache key of a previous successful authentication.
Customers meeting the pre-conditions should investigate their Okta System Log for unexpected authentications from usernames greater than 52 characters between the period of July 23rd, 2024 to October 30th, 2024. 
- Saved query to investigate unexpected authentications from usernames greater than 52 characters between the period of July 23rd, 2024 to October 30th, 2024.
- tested in …

Okta AD/LDAP Delegated Authentication - Username Above 52 Characters Security Advisory

---

rules/standard_rules/sign_in_from_rogue_state.py
rules/standard_rules/sign_in_from_rogue_state.yml

An oversight in the rule caused it to error if there wasn't a `p_enrichment` value for IPInfo location.
- Added logic to gracefully return false if we can't find a matching country in `pycountry` for some reason, including due to the enrichment data being absent
- added unit test for missing enrichment data
- added unit test for enrichment data referencing an unknown country code

Fix Standard.SignInFromRogueState for Unenriched Events

---

rules/wiz_rules/wiz_alert_passthrough.py
rules/wiz_rules/wiz_alert_passthrough.yml

We've observed large numbers of low-level alerts for some customers, due to a handful of Wiz rules failing for a large number of resources. The current dedup behaviour of the Panther rule is to group based on the resource ID. This PR alters the behaviour to dedup low-level alerts based on the Wiz rule ID instead, ensuring that low-severity policies that fail against many resources don't generate alert storms.
This should be more useful to Panther customers as well, since they get 1 alert informing them that many resources have failed the policy.
Simulations testing this against alert metadata from several volunteering customers say alert reductions between 10%-50%
- add alternative dedup logic for low-severity Wiz alerts to group based on the Rule ID instead of the Resource ID
- tested an …

Wiz.Alert.Passthrough: New Dedup Logic

---

global_helpers/global_helpers_test.py
global_helpers/panther_aws_helpers.py
global_helpers/panther_base_helpers.py
global_helpers/panther_okta_helpers.py

Adds a helper function to convert an event into a PantherFlow query to investigate the context surrounding the event.  It searches +/- 30 minutes, for the logtype of the event, with any similar `p_any` indicator fields.
- New `pantherflow_investigation` helper
- Updated AWS and Okta alert context to add PantherFlow Investigation query
- generated queries tested in dev environment

PantherFlow Investigator Helper

---

data_models/aws_cloudtrail_data_model.py
data_models/aws_cloudtrail_data_model.yml

In preparation for https://github.com/panther-labs/panther-analysis/pull/1439 creating a get_user datamodel for AWS to correctly identify the username depending on user type.
- add get_user to datamodel
- validated against [documentation](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html#cloudtrail-event-reference-user-identity-fields)
- will update unit tests after applying event.udm('user') in subsequent PR

Add get_user to AWS datamodel

---

packs/aws.yml
rules/aws_eks_rules/anonymous_api_access.py
rules/aws_eks_rules/anonymous_api_access.yml

Tuned version of https://github.com/panther-labs/panther-analysis/pull/1405
This change introduces a new detection rule for identifying anonymous API access to the Kubernetes API server in Amazon EKS clusters. Anonymous access should be disabled in production environments to prevent unauthorized access, as it poses a potential security risk. Detecting anonymous requests helps ensure that EKS clusters are properly configured for secure API usage.
- Added a new detection rule Amazon.EKS.AnonymousAPIAccess to monitor and detect anonymous API requests to the Kubernetes API server.
- Included a YAML configuration for the rule with severity set to medium and associated MITRE ATT&CK references.
- Provided test cases to validate both anonymous and non-anonymous API requests.
- Documented …

THREAT-413 - Tune EKS Anonymous API Access Detection Rule (#1405)

---

global_helpers/global_helpers_test.py
global_helpers/panther_base_helpers.py
packs/msft_graph.yml
packs/zoom.yml
rules/microsoft_rules/microsoft365_external_sharing.py
rules/zoom_operation_rules/zoom_user_promoted_to_privileged_role.py
rules/zoom_operation_rules/zoom_user_promoted_to_privileged_role.yml

Fix for https://github.com/panther-labs/panther-analysis/issues/1435
- update email regex to properly identify email addresses
- updated unit tests

Update Email Regex

---

rules/okta_rules/okta_new_behavior_accessing_admin_console.py
rules/okta_rules/okta_new_behavior_accessing_admin_console.yml

If Okta field `debugContext.debugData.logOnlySecurityData` came as a string instead of json, there was no alert for `Okta New Behaviors Acessing Admin Console` rule
- added check for type of `debugContext.debugData.logOnlySecurityData` and jsonification if needed
- changed tests' format from yml to json
pat test

Okta New Behaviors Acessing Admin Console — jsonify logOnlySecurityData string

---

packs/github.yml
rules/github_rules/github_repo_ruleset_modified.py
rules/github_rules/github_repo_ruleset_modified.yml

The cool kidz these days are using ruleset instead of or in combination with branch protection rules. This rule alerts to modifications (update, destroy) of rulesets and adds an INFO-level signal for ruleset creations if desired for future correlation rules. Filters can be applied in global_filter_github and the github_alert_context is enriched specific to repo ruleset changes.
[1] https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets
- Create GitHub.Repo.RulsetModified rule
- Tests for each create/update/destroy event type
- Update the github.yml pack
pat test, make lint

Create Github.Repo.RulesetModified rule

---

lookup_tables/ipinfo/ipinfo_asn.yml
lookup_tables/ipinfo/ipinfo_asn_datalake.yml
lookup_tables/ipinfo/ipinfo_location.yml
lookup_tables/ipinfo/ipinfo_location_datalake.yml
lookup_tables/ipinfo/ipinfo_privacy.yml
lookup_tables/ipinfo/ipinfo_privacy_datalake.yml
lookup_tables/tor/tor_exit_nodes.yml

EKS LUT selector fields were not accurate
- $.spec.clusterIP -> $.responseObject.spec.clusterIP

Update LUT selectors

---

rules/aws_s3_rules/aws_s3_access_ip_allowlist.py
rules/aws_s3_rules/aws_s3_access_ip_allowlist.yml

`AWS.S3.ServerAccess.IPWhitelist` would raise an error if the version of the accessing IP was different from the version of the allowed CIDR range. I added an additional check to confirm whether the addresses are both IPv4 or IPv6, and return `False` if they are not.
- add `is_subnet` function to rule, which allows comparison of IPv4 and IPv6 networks
- Manual testing passed the vibe check
- New unit test also passes

Patch AWS.S3.ServerAccess.IPWhitelist to work with IPv6

---

.github/ISSUE_TEMPLATE/new_analysis.yml
.github/ISSUE_TEMPLATE/tuning.yml

Adds issue templates for new rule and tuning requests.

Issue Templates for New Analysis and Tuning

---

.github/workflows/release.yml

Makes the Release workflow to default to the `main` branch instead of the repository's default (`develop`).

fix: default release workflow to main

---

packs/standard_ruleset.yml
rules/standard_rules/brute_force_by_user.py
rules/standard_rules/brute_force_by_user.yml

Hakmiller noticed that our `Standard.BruteForceByIP` rule is actually checking by username, not IP. He requested we either make the title clearer, or adjust the rule to check by IP instead. Since changing a rule's title has numerous consequences, I've instead decided to adjust the logic to check by IP, and copied the existing logic to a new rule, `Standard.BruteForceByUser`, so customers can keep the same behaviour if they wish.
- Title and dedup changes to `Standard.BruteForceByIP`
- Added new rule `Standard.BruteForceByUser`, which has the original logic of `Standard.BruteForceByIP`
- Updated standard pack to include new rule
- Titles and dedups for both rules work as expected

Split 'Standard.BruteForceByIP' into IP and Username versions

---

packs/aws.yml
policies/aws_iam_policies/aws_iam_role_github_actions_trust.py
policies/aws_iam_policies/aws_iam_role_github_actions_trust.yml

This policy ensures secure configuration of AWS IAM roles used with GitHub Actions by validating trust relationships. It enforces restrictions on the Principal, aud (audience), and sub (subject) conditions to prevent unauthorized access to AWS resources. Misconfigurations such as wildcards in the Principal or overly permissive sub conditions can lead to potential exploitation, so this policy mitigates such risks by enforcing proper validation rules.
- Validates the Principal.Federated field to ensure it is either GitHub's OIDC provider (oidc- provider/token.actions.githubusercontent.com) or skips validation for non-GitHub principals. It rejects wildcards as insecure.
- Ensures Condition.StringEquals for aud is correctly set to sts.amazonaws.com.
- Enforces scoping of Condition.StringLike …

Github Actions OIDC IAM Role Trust Relation

---

rules/snowflake_rules/snowflake_stream_brute_force_by_ip.py
rules/snowflake_rules/snowflake_stream_brute_force_by_ip.yml
rules/snowflake_rules/snowflake_stream_brute_force_by_username.py
rules/snowflake_rules/snowflake_stream_brute_force_by_username.yml

We've observed a high number of alerts caused by JWT validation issues from our automations rotating tokens, and this PR will fix that.
- Failed logins due to JWT issues are now signals
- Failed logins logs due to event overflow are ignored; these events are generated only when we've had a bunch of previous failed logins, so we will already have alerted if we start seeing these
- Added new unit tests for both types of error message

Snowflake Brute Force Tuning

---

.github/workflows/test.yml

The test GHA currently runs PAT test but not make test, which misses the unit tests for global helpers and data models.
- Add `make data-models-unit-test global-helpers-unit-test` step to test workflow
- GHA test

Test GHA runs unit tests

---

Makefile

In [this docs change request](https://app.gitbook.com/o/-LgddDaIOc7MA4mxoaPa/s/-LgdiSWdyJcXPahGi9Rs-2910905616/~/changes/2924/panther-developer-workflows/ci-cd/detections-repo/~/comments/HZTP8nl23iNZyMnfruxZ?node=sr7cV5P1qs1Q#working-with-deprecated-rules) that adds info on working with deprecated detection content, after I suggested not mentioning make check-deprecated, @ben-githubs said, "My concern was that, if it isn't documented, we will get questions about it."
What do you think about adding code comments like this?
Added a comment for both check-deprecated and remove-deprecated
n/a

Add comments for check-deprecated and remove-deprecated in Makefile

---

policies/aws_iam_policies/aws_iam_role_github_actions_trust.py
policies/aws_iam_policies/aws_iam_role_github_actions_trust.yml

This policy was causing false positives in our test environment.
- Parse AssumeRolePolicyDocument into json if needed
- Reworked logic to not generate false positives on non-github related resources
- new unit tests

[Tuning] GitHub Actions Trust Policy

---

rules/aws_cloudtrail_rules/aws_cloudtrail_event_selectors_disabled.yml

SPS-Commerce noticed that we have a small typo in the `DisplayName` of the rule. Here is the corresponding thread: https://panther-labs.slack.com/archives/C060Z8KNGJ3/p1738008281806559
The DisplayName of the rule was updated to "CloudTrail Event Selectors Disabled". Initially, it was "CloudTrail Event Delectors Disabled".

Update aws_cloudtrail_event_selectors_disabled.yml DisplayName

---

packs/aws.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_attempt_to_leave_org.py
rules/aws_cloudtrail_rules/aws_cloudtrail_attempt_to_leave_org.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_identity_verifications.py
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_identity_verifications.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_send_quota.py
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_send_quota.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_ses_sending_enabled.py
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_ses_sending_enabled.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_enumeration.yml
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_list_identities.py
rules/aws_cloudtrail_rules/aws_cloudtrail_ses_list_identities.yml

Adding some rules related to misc. Stratus Red Team techniques.
- 3 new rules plus some SES signals
- All rules/signals have unit tests

Stratus AWS: Misc Detections

---

.scripts/mitre_mapping_check.py

After we introduced the index PR, a newly-added JSON file caused the mitre script to fail.
- update lint-mitre to ignore anything inside the index dir
- add better error reporting: log failed attempts to scan a detection and continue
- ran locally, confirmed errors were logged as expected
- confirmed that with the index filter, no errors occurred

Update `lint-mitre` to Ignore Indexes

---

policies/aws_lambda_policies/aws_lambda_public_access.py
policies/aws_lambda_policies/aws_lambda_public_access.yml

Lack of default return values was causing lambdas without policies to trigger false positives.  There was also an issue where conditions to allow [unauthenticated public access](https://docs.aws.amazon.com/lambda/latest/dg/urls-auth.html#urls-auth-none) would cause false negatives.
- add default values to get and deep_get
- add logic and severity function for unauthenticated public access
- new unit tests

[Tuning] Public Lambda Policy Tuning

---

rules/github_rules/github_repo_ruleset_modified.py
rules/github_rules/github_repo_ruleset_modified.yml

My initial rule neglected to account for Org-wide ruleset in the title and used the default github_alert_context for the user field, which is inappropriate for repo ruleset changes. 
- Ensure title reflects organization-wide ruleset changes
- Add test for that title change
- Overwrite user field in alert_context it's the actor field as the default in github_alert_context is the user field
- pat test
- make lint

Fix GitHub.Repo.RulesetModified title and context

---

Pipfile
Pipfile.lock

After upgrading to `pylint 3.3.4` there occur import errors while using `pylint`. It happens due to a dependency on [pylint-print](https://gitlab.com/nwmitchell/pylint-print), which appears to be unmaintained and incompatible with pylint 3.x.x
- Dropped pylint-print dependency
```
pip install pulint -U 
pipenv run pylint [path]
```

ASK-1420 Remove pylint-print dependency

---

policies/aws_iam_policies/aws_iam_role_github_actions_trust.py
policies/aws_iam_policies/aws_iam_role_github_actions_trust.yml

`AWS.IAM.Role.GitHubActionsTrust` policy had `token.actions.githubusercontent.com:sub` hardcoded to need exactly one possible beginning of value containing `*` (`repo:org/repo:*`), which could cause the policy to fail even when `org` and `repo` were trusted but named differently.
- Added the possibility to add trusted org/repo pairs
- pat test

ASK-1387 Tuning AWS.IAM.Role.GitHubActionsTrust policy to be more flexible

---

data_models/aws_vpcflow_data_model.yml
rules/aws_vpc_flow_rules/aws_vpc_healthy_log_status.yml

Noticed an issue with the VPC Flow data model referencing the wrong field.  Also noticed that these SKIPDATA VPC logs [are non-actionable](https://www.reddit.com/r/aws/comments/zt1xhg/vpc_flow_logs_when_is_logstatus_skipdata_a_concern/?rdt=41505), so converted the rule to a signal.
- Fix data model
- Convert to signal
- Updated unit tests

[Tuning] VPC Healthy Log Status

---

rules/aws_eks_rules/anonymous_api_access.py

Making some tuning changes to prevent a bunch of low-level alerts, while preserving the signals
- Adjusted dedup logic to only apply to alerts higher than INFO severity
- Tests all pass; ran it through a data replay for a noisy timespan and reduced alerts by 50%

stop deduping info-level alerts

---

.scripts/generate_indexes.py

It was brought to my attention that seemingly unrelated changes were being written to the indexes. The index script is meant to always produce the same output for the same input, so there should be no changes written when rules aren't substantially changed. It looked like scheduled rules were being randomly exchanged for their scheduled queries ([commit 1](https://github.com/panther-labs/panther-analysis/commit/7e8015fb16c981d847b64ca022028aedcfb715c3) & [commit 2](https://github.com/panther-labs/panther-analysis/commit/af113a13c7a3fd05dbb1a28ce01a4691cf5a0c36)) when the intent is to always show the query.
- Fix the name deduplication logic by checking for pretty and raw `AnalysisTypes` and fixing a logic error with how I was using `itertools.groupby`. I didn't realize there was a …

fix: Index stability for scheduled rules vs. scheduled queries

---

packs/aws.yml
rules/aws_guardduty_rules/aws_guardduty_critical_sev_findings.py
rules/aws_guardduty_rules/aws_guardduty_critical_sev_findings.yml

Amazon GuardDuty has recently released composite [attack sequence findings](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-attack-sequence-finding-types.html), which use the [severity level 9.0](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings-severity.html#guardduty-finding-severity-level-critical). Previously the max severity number for detections was 8.9.
- Adds GuardDuty critical detection
- Detection has unit tests from Amazon GuardDuty sample findings.

Add guardduty critical

---

rules/aws_cloudtrail_rules/aws_resource_made_public.py
rules/aws_cloudtrail_rules/aws_resource_made_public.yml

The policyuniverse library incorrectly considers policies with wildcard principals ("Principal": "\*") as internet accessible, even when they have restrictive conditions like organization ID restrictions.  The is_internet_accessible method in policyuniverse considers a policy statement internet accessible if ANY of its condition entries are internet accessible. ARN patterns with wildcards in the account number position (arn:aws:iam::\*:role/...) are considered internet accessible by the _arn_internet_accessible method.
- Modified the policy_is_internet_accessible function in the aws_resource_made_public.py rule to add an additional check for policies with organization ID restrictions. If a statement has a wildcard principal but also has organization ID conditions, we consider it not …

Check for org ID restrictions in policies

---

rules/azure_signin_rules/azure_role_changed_pim.py
rules/azure_signin_rules/azure_role_changed_pim.yml

The rule `Azure.Audit.RoleChangedPIM` originally had a `DedupPeriodMinutes` value of 0, but our rule engine doesn't allow values smaller than 5. I adjusted the value to 5, and introduced a `dedup` function to the rule which ensures that each event is a separate alert (which is the assumed intent of setting the dedup period to 0).
- changed `DedupPeriodMinutes` to 5
- set rule to dedup based on `p_row_id` which is unique for every event
- linting and unit tests all pass

Azure.Audit.RoleChangedPIM: Ensure Every Event is a Separate Alert

---

.github/workflows/sync-from-upstream.yml

The `GITHUB_TOKEN` token doesn't have the `workflows` permission in order to be able to edit Github actions and whenever the upstream panther-analysis repository has any changes under `.github/workflows` it fails to open a Pull Request with the upstream changes.
This change introduces a `PANTHER_SYNC_UPSTREAM` token which when it's present and has the appropriate permissions (`Administration`, `Content`, `Pull Requests` and `Workflows`), then it will allow the action to open a Pull Request even when the underlying Github actions have updates as well.
**Don't merge until [our docs](https://docs.panther.com/panther-developer-workflows/detections-repo/public-fork#keeping-in-sync-with-upstream) are updated.** 
- Introduces `PANTHER_SYNC_UPSTREAM` token injection
- Fallbacks to `GITHUB_TOKEN` …

Enable sync to upstream Github action can change Github actions

---

rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.py
rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.yml

A customer reported receiving the following error when running this rule:
```
TypeError("unhashable type: 'ImmutableCaseInsensitiveDict'")
``` 
It was determined that their incoming events have an unexpected value for `instanceType`:
```json
"instanceType": {
"value": "g5.8xlarge"
}
```
- fix logic to work in cases where `instanceType` is a string and also when it is an object
- added new unit test

AWS.EC2.LaunchUnusualEC2Instances: Add support for dictionary 'instanceType' values

---

.scripts/generate_indexes.py

Currently the entire `detection-coverage.json` file is a single-line JSON array, and that causes problems when trying to merge PRs because each PR is editing the same line. By making it multi-line, we should be able to merge additions and removals without conflicts.
- changed JSON dump to have a 4-space indent, which forces multi-line formatting
- dry-ran `generate_indexes.py` and confirmed the output looked accurate

Make detection-coverage.json multi-line

---

rules/github_rules/github_repo_vulnerability_dismissed.yml

The rule had 2 unit tests with the same name and similar payload. This causes issues when trying to upload using PyPanther. I removed one of them.
- remove unit test from `github_repo_vulnerability_dismissed.yml`
- Tests still pass

Github.Repo.VulnerabilityDismissed: Remove duplicate unit test

---

rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml

Turns `Lambda Update Function Code` and `AWS.Lambda.UpdateFunctionConfiguration` into signals.
- `make test`

Turn Lambda Update alerts into signals (3.72.1 patch) 

---

rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml

Turns `Lambda Update Function Code` and `AWS.Lambda.UpdateFunctionConfiguration` into signals.
- `make test`

Turn Lambda Update alerts into signals (3.73.1 patch)

---

rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml

Turns `Lambda Update Function Code` and `AWS.Lambda.UpdateFunctionConfiguration` into signals.
- `make test`

Turn Lambda Update alerts into signals (3.74.1 patch) 

---

rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml

Turns `Lambda Update Function Code` and `AWS.Lambda.UpdateFunctionConfiguration` into signals.
- `make test`

Turn Lambda Update alerts into signals (3.75.1 patch) 

---

packs/snowflake.yml
queries/snowflake_queries/snowflake_brute_force_ip.py
queries/snowflake_queries/snowflake_brute_force_ip.yml
queries/snowflake_queries/snowflake_brute_force_username.py
queries/snowflake_queries/snowflake_brute_force_username.yml
queries/snowflake_queries/snowflake_failed_logins_query.yml

I've adjusted the brute force scheduled rules to make them more reliable, and also added some QoL improvements as well.
- filter common error messages due to token rotations to be signals instead of alerts
- changed the rules to use a new query that returns events instead of aggregates, and allow the threshold to be adjustable in the rule YAML spec
- add the number of failed logins to the alert title
- add summary attributes to better understand the distribution of indicators at a glance
- after adding new fields to the unit tests, all tests pass

ASK 1969 - Tuning Snowflake.BruteForceBy* Rules

---

rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml
rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml

Turns `AWS.Lambda.UpdateFunctionCode` and `AWS.Lambda.UpdateFunctionConfiguration` into signals.
- `make test`

fix: turn Lambda Update alerts into signals

---

rules/snowflake_rules/snowflake_stream_external_shares.py
rules/snowflake_rules/snowflake_stream_external_shares.yml

A mismatch between the Panther-managed Snowflake.DataTransferHistory schema and the log messages coming from Snowflake — specifically around the ACCOUNT_NAME field.
- Dropped non-existent fields from rule logic and tests
pat test

[fix] ASK-1780 Snowflake. DataTransferHistory rule using non-existent field

---

indexes/alpha-index.md
indexes/aws.md
indexes/detection-coverage.json
rules/aws_cloudtrail_rules/aws_key_compromised.py
rules/aws_cloudtrail_rules/aws_key_compromised.yml

AWS has added a few changes to the monitored policy since it was initially committed.
Check one of the new policies attached (OG through v3)
Remove custom dedup function. We should remember that if the interpolation values differ from the title, there will be odd side-effects around merging alerts that don't match the title.
Simplified rule logic
Updated tests
Updated and ran tests

update comp keys rule

---

rules/gcp_audit_rules/gcp_destructive_queries.py

Alert storm for GCP.Destructive.Queries rule
- Add dedup to GCP.Destructive.Queries

Add dedup to GCP.Destructive.Queries

---

.gitignore

Adding mcp.json to gitignore so that we (and customers) can set up an MCP server without having our API credentials stored in the repo 😳 
- add mcp.json to gitignore
- I looked and mcp.json was ignored

Add mcp.json to gitignore

---

rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.py
rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.yml

Customer identified a couple typos and experienced excessive alerts. This PR fixes the types and moves the rule to Beta statis (INFO severity) to stem the bleeding while we fix the issues.
- add `Beta` tag
- spelling fixes
- N/A

Google.Workspace.ManyDocsDownloaded: Fix typos and move to beta status

---

rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.py

The EC2 unusual launch detection currently returns an error if the instanceType lookup returns a dictionary. The lookup function fixes this error, but the instance type function being called is unnecessary unless the eventSource and eventName are appropriate.
Change return logic to use `and` to return false faster.
Move lookup of instance type into return logic to avoid unnecessary event processing.
Local PAT testing passes
```
Test Summary
Path: ./rules/aws_cloudtrail_rules
Passed: 1
Skipped: 0
Failed: 0
Invalid: 0
```

Unusual EC2 launch logic fixup

---

.vscode/schemas/correlation_rule.json

Correlation rule schema was incorrectly categorizing the Detection field as an object when it should be a list.
- Schema update
- Validated that VScode passes schema checks for all Correlation Rules
ASK-1782

Fix schema

---

rules/aws_cloudtrail_rules/aws_backdoor_lambda_function.py

Adjust the title for this detection so it will pull the name instead of returning unknown.

Adjust AWS Potential Backdoor Lambda Function title

---

queries/snowflake_queries/snowflake_brute_force_ip_query.yml
queries/snowflake_queries/snowflake_brute_force_username_query.yml

We tuned the streaming rules to ignore JWT mismatches as false-positives, but we didn't tune the queries themselves. This PR ignores those error codes.
- ignore error code 394304, which corresponds to a JWT finger print mismatch
- N/A

ASK-1696: Ignore JWT mismatch in queries

---

rules/gcp_audit_rules/gcp_destructive_queries.py
rules/gcp_audit_rules/gcp_destructive_queries.yml

Adjust the tuning strategy to prevent alert storms from a few users updating/deleting from many tables. Also adjusts the severities to only surface the more severe table-level deletions as actionable alerts, and relegate the row-level deletions to loggable signals.
- remove `dedup`
- add `severity`
- adjust title format based on the type of action taken in the event
- previously the title displayed incorrectly for tableDeletion and datasetDeletion events; this is fixed now
- new unit test

GCP.Destructive.Queries: More tuning

---

rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.py
rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.yml

Recently we learned that the `download` event is generated every time Google Drives performs a sync to a local device, which means the majority of alerts generated by this rule would be false positives. As far as I can tell, we don't get enough information about the client in the ActivityEvent logs to filter Drive syncs out, so the next best option is to move the rule toa. signal.
[See ASK-1860 for additional context.](https://panther-labs.atlassian.net/browse/ASK-1860)
- make `Google.Workspace.ManyDocsDownloaded` a signal
- make test

Google.Workspace.ManyDocsDownloaded: Convert to Signal

---

rules/aws_cloudtrail_rules/aws_console_login_without_mfa.py
rules/aws_cloudtrail_rules/aws_console_login_without_mfa.yml
rules/aws_cloudtrail_rules/aws_ec2_many_passwors_read_attempts.py
rules/aws_cloudtrail_rules/aws_software_discovery.py
rules/aws_cloudtrail_rules/aws_unauthorized_api_call.py
rules/aws_cloudtrail_rules/aws_vpce_access_denied.py
rules/aws_cloudtrail_rules/aws_vpce_external_principal.py
rules/aws_cloudtrail_rules/aws_waf_disassociation.py

- Updated AWS CloudTrail rules to use `event.udm('actor_user')` instead of `userIdentity.principalId`
pat test

THREAT-431 Update AWS rules to use new `get_actor_user` udm

---

rules/aws_cloudtrail_rules/aws_unauthorized_api_call.py
rules/aws_cloudtrail_rules/aws_unauthorized_api_call.yml

pypanther test failing with `Exception occurred in dedup(): detection [AWS.CloudTrail.UnauthorizedAPICall-prototype] method [dedup] returned [NoneType], expected [str]`
- Updated aws_unauthorized_api_call.py by adding dedup default
pat test

Update aws_unauthorized_api_call.py by adding p_log_type

---

.github/workflows/check-packs.yml

Removes the `set-output` command since it will be deprecated ([docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)).
- Replaces `set-output` with `echo` to the `$GITHUB_OUTPUT` file

[THREAT-453] Remove set-output from Github Action

---

rules/aws_cloudtrail_rules/aws_ec2_multi_instance_connect.py
rules/aws_cloudtrail_rules/aws_ssm_decrypt_ssm_params.py
rules/aws_cloudtrail_rules/aws_ssm_decrypt_ssm_params.yml
rules/aws_cloudtrail_rules/aws_ssm_distributed_command.py

Some of our rules are designed to cache items for a set time after the first entry, but the caching helpers don't support this currently. As a workaround for now, we can cache these according to an arbitrary "time bucket" instead.
- update the cache keys to include a timetsamp
- all the keys are generated properly

Changes to some caching rules for time-based caching

---

queries/snowflake_queries/snowflake_brute_force_ip_query.yml
queries/snowflake_queries/snowflake_brute_force_username_query.yml

Customer ran into an error during their CircleCI deployment when using the panther_analysis_tool to upload analysis items after updating to our latest release (v3.77.0). The error appears related to changes made in this recent [PR](https://github.com/panther-labs/panther-analysis/pull/1599/files).
- replaced `is not` by `!=`

ASK-1980 Snowflake queries syntax error

---

rules/okta_rules/okta_anonymizing_vpn_login.py

Suggested improvement to the VPN title - domain is often empty making it less helpful for the title. This update includes more info in the title, including the service and IP, for at a glance reference and easier triage. The combo of service and asOrg should give enough info to have an idea about potential issues with the activity. Set up to handle  to keep the context concise.

Okta VPN Login Title Enhancement

---

rules/aws_cloudtrail_rules/aws_cloudtrail_event_selectors_disabled.py

the current code does not work in intended way.
the logic below fails if `includes` is `None`.
```python
if not isinstance(includes, list):
includes = [includes]
```
and this rule will always return true
i added custom check for None.
```python
if includes is None:
includes = []
```
```python
includes = deep_walk({}, "requestParameters", "eventSelectors", "include
⋮ ManagementEvents")
assert includes is None
includes = [includes]
print(includes)
result = not all(includes)
print(result)
```

Fiixing list conversion in AWS.CloudTrail.EventSelectorsDisabled

---

Pipfile.lock
rules/gsuite_activityevent_rules/gsuite_suspicious_logins.py
rules/gsuite_activityevent_rules/gsuite_suspicious_logins.yml

The current `GSuite.SuspiciousLogins` rule only triggers on explicitly named suspicious login event types (e.g., `suspicious_login`). However, Google may flag logins as suspicious via the `parameters.is_suspicious` field even when the `event.name` is a benign value like `login_success`. These edge cases were not being detected under the existing rule logic.
This update broadens the rule to catch such events
- Expanded rule logic to trigger if:
- `event.name` is in `SUSPICIOUS_LOGIN_TYPES`, **or**
- `parameters.is_suspicious == true`
- Added a new unit test covering the edge case where:
- `event.name = login_success`
- `parameters.is_suspicious = true`
- Made a minor change to title logic

Made improvements to rule to catch suspicious login success events

---

rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.py

The alert title is misleading and does not reflect the detection logic.
This change:
- Updates the alert title to accurately reflect the detection logic (i.e. `AccessDenied` error when retrieving secrets)
- Includes the `errorMessage` in the alert context, which is a crucial piece of information for security engineers and incident responders

fix(aws): fix alert title and include error message

---

indexes/alpha-index.md
indexes/detection-coverage.json
indexes/gworkspace.md
indexes/saas.md
packs/gsuite_reports.yml
rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.py
rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.yml
rules/gsuite_activityevent_rules/gsuite_suspicious_logins.py
rules/gsuite_activityevent_rules/gsuite_suspicious_logins.yml

After adding the check for `is_suspicious` tag to the `GSuite suspicious login rule` the rule became noisier. At the same time, the are issues that this check catches, so deleting it would be wrong.
- Divided the rule into two. That way, customers can decide for themselves whether they want this new check enabled or not.
pat test

ASK-2236 Increase in alerts for `GSuite suspicious login` rule

---

.vscode/schemas/lookup_table.json

VScode schemas were failing on managed LUTs with Refresh settings.
- added Refresh field
- made Filename optional
- VScode approves of managed LUT files now

Schema fix for managed LUTs

---

rules/aws_eks_rules/system_namespace_public_ip.yml

The MITRE mappings for this rule pointed to "Initial Access: Deliver Malicious App via Authorized App Store", which was wildly inaccurate. This PR adjusts the mapping to "Discovery: Log Enumeration" which seems a more appropriate tactic and technique for what the rule is designed to detect (access to system logs from external IP).
- Change MITRE mapping and add corresponding tags
- N/A

Update MITRE mapping: Amazon.EKS.Audit.SystemNamespaceFromPublicIP

---

packs/gcp_audit.yml
rules/gcp_audit_rules/gcp_iam_corp_email.py
rules/gcp_audit_rules/gcp_iam_corp_email.yml

Fixes the `GCP.IAM.CorporateEmail` rule to not break when GCP services make changes. [See this PR for more info.](https://github.com/panther-labs/panther-analysis/pull/1573)
- add additional filtering for new binding members
- added a new unit test

Add support for GCP Service Manager to GCP.IAM.CorporateEmail

---

global_helpers/panther_type_hints.py
global_helpers/panther_type_hints.yml

Some people really like type hints (myself included) since IDEs can provide autocompletion for specific functions and helpful tooltips. If you wanted type hints for Panther-specific data types, you had to import them from `panther_core`, which the majority of our users don't know enough about to know where to import the types from. This PR brings those types into a helper module, making them more accessible.
- Adding `PantherEvent`, `ImmutableCaseInsensitiveDict`, and `ImmutableList` as importable types for type hinting
- I have type hints, it works

Add PantherEvent type hints

---

.vscode/schemas/query.json

new email config property should not show errors in IDEs
- updated schema file for queries
tested before:
after:

add email config to query schema

---

rules/standard_rules/impossible_travel_login.py
rules/standard_rules/impossible_travel_login.yml

Adds a check for matching IPs in the standard impossible travel detection - failure to check caused false positives when the geolocation information was changed within the caching period. Required updating the Notion test case because the IPs matched. Also added the IPs to the title for response QOL - helps with at-a-glance identification of common IPs within the environment as well as AWS, MS, etc. Used EVENT_CITY_TRACKING in the rule detection for consistency with the title IP lookup.

Impossible travel IP logic check
