panther-labs/panther-analysis

.github/CODEOWNERS, README.md
Updated the README to more accurately reflect the dual nature of the repository.
* Updated the README structure to discuss `analysis` and `panther-cli` separately
* Added Austin as a code owner
* N/A
=> README update

CONTRIBUTING.md, README.md, analysis/aws_rules/cis/aws_cloudtrail_modified.yml, analysis/aws_rules/cis/aws_console_login_failed.yml, analysis/aws_rules/cis/aws_console_login_without_mfa.yml, analysis/aws_rules/cis/aws_ec2_gateway_modified.yml, analysis/aws_rules/cis/aws_ec2_network_acl_modified.yml, analysis/aws_rules/cis/aws_ec2_route_table_modified.yml, analysis/aws_rules/cis/aws_ec2_security_group_modified.yml, analysis/aws_rules/cis/aws_ec2_vpc_modified.yml, analysis/aws_rules/cis/aws_iam_policy_modified.yml, analysis/aws_rules/cis/aws_kms_cmk_loss.yml, analysis/aws_rules/cis/aws_s3_bucket_policy_modified.yml, analysis/aws_rules/cis/aws_unauthorized_api_call.yml, analysis/policies/managed/aws_ec2_instance_detailed_monitoring_enabled.yml, analysis/policies/managed/aws_ec2_instance_ebs_optimized.yml, analysis/policies/managed/aws_rds_instance_has_high_availability.py, analysis/policies/managed/aws_rds_instance_has_high_availability.yml, analysis/policies/s3/aws_s3_bucket_versioning_enabled.yml
Small changes after dogfooding
* Add missing references
* Fix a bug in the RDS HA Policy about RDS Aurora
* CI
=> Add references, fix a bug in RDS Instance HA policy

README.md
Discovered an alternative, not officially documented, workflow for making a private fork of this repository so I decided to add it as an alternative setup.
* Updated README
* Tested the method manually
=> Alternative Development Workflow

analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.py, analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.yml, analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.py, analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.yml, analysis/osquery_rules/osquery_mac_alf_disabled.py, analysis/osquery_rules/osquery_mac_alf_disabled.yml, analysis/osquery_rules/osquery_mac_osx_attacks.py, analysis/osquery_rules/osquery_mac_osx_attacks.yml, analysis/osquery_rules_cis/osquery_mac_enable_auto_update.yml
Add a new folder for generic CloudTrail rules and fix a bug in the S3 Insecure Access rule
* Described above
* Locally with the CLI
=> AWS Rules - DeleteBucket, S3 Insecure Access Fix

analysis/aws_rules_cis/aws_cloudtrail_created.yml, analysis/aws_rules_cis/aws_cloudtrail_stopped.yml, analysis/aws_rules_cis/aws_config_service_created.yml, analysis/aws_rules_cis/aws_config_service_disabled_deleted.yml, analysis/aws_rules_cis/aws_console_login_failed.yml, analysis/aws_rules_cis/aws_console_login_without_mfa.yml, analysis/aws_rules_cis/aws_ec2_gateway_modified.yml, analysis/aws_rules_cis/aws_ec2_network_acl_modified.yml, analysis/aws_rules_cis/aws_ec2_route_table_modified.yml, analysis/aws_rules_cis/aws_ec2_security_group_modified.yml, analysis/aws_rules_cis/aws_ec2_vpc_modified.yml, analysis/aws_rules_cis/aws_iam_policy_modified.yml, analysis/aws_rules_cis/aws_kms_cmk_loss.yml, analysis/aws_rules_cis/aws_root_activity.yml, analysis/aws_rules_cis/aws_s3_bucket_policy_modified.yml, analysis/aws_rules_s3_access_logs/aws_s3_access_error.yml, analysis/aws_rules_s3_access_logs/aws_s3_access_ip_whitelist.yml, analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.yml, analysis/aws_rules_s3_access_logs/aws_s3_unauthenticated_access.yml, analysis/aws_rules_vpc_flow_logs/aws_vpc_healthy_log_status.yml, analysis/aws_rules_vpc_flow_logs/aws_vpc_inbound_traffic_port_blacklist.yml, analysis/aws_rules_vpc_flow_logs/aws_vpc_inbound_traffic_port_whitelist.yml, analysis/aws_rules_vpc_flow_logs/aws_vpc_unapproved_outbound_dns.yml
Add clarification to the Rule IDs to reduce any possible confusion. 
* Remove the "CloudTrail" prefix in some IDs, since they focus on changes made to other services and not CloudTrail itself.
* Locally with the CLI
=> [aws_rules] shorten and clarify rule IDs

analysis/aws_policies_managed/aws_guardduty_enabled.yml
Renamed this policy to be more in line with its functionality.
=> Rnamed guard duty enabled policy

analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.yml, analysis/osquery_rules/osquery_mac_alf_disabled.yml
A small adjustment to the s3 delete rule
* Set severity to Info and add Runbook for s3_delete rule
* CI
=> s3 bucket destroyed runbook and severity adjustment

analysis/aws_policies_s3/aws_s3_bucket_not_publicly_writable.yml, analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.py, analysis/aws_rules_cloudtrail/aws_s3_bucket_deleted.yml, analysis/aws_rules_cloudtrail/aws_update_credentials.py, analysis/aws_rules_cloudtrail/aws_update_credentials.yml, analysis/aws_rules_s3_access_logs/aws_s3_access_error.py, analysis/aws_rules_s3_access_logs/aws_s3_access_ip_whitelist.py, analysis/aws_rules_s3_access_logs/aws_s3_access_ip_whitelist.yml, analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.py, analysis/aws_rules_s3_access_logs/aws_s3_insecure_access.yml, analysis/aws_rules_s3_access_logs/aws_s3_unauthenticated_access.py, analysis/aws_rules_s3_access_logs/aws_s3_unauthenticated_access.yml, analysis/osquery_rules/osquery_mac_alf_disabled.py, analysis/osquery_rules/osquery_mac_osx_attacks.py
Rule tuning and new capabilities
* Disable some by default that requires config, tag properly
* Use dedup and title functions
* Locally with panther_analysis_tool
=> OSS Tuning Pt 1

analysis/aws_rules_cis/aws_cloudtrail_stopped.py, requirements-top-level.txt
* Dedup and Title for cloudtrail stopped rule
* Update requirements top level
* CI
=> merge and dedup for cloudtrail stopped

global_helpers/panther.py
Adding helper functions for simple integer counters.
* Add counter helpers
* Lazily construct DynamoDB table clients
This helps with CI and also is a performance improvement - if no rules need these tables, we won't waste cycles configuring their clients.
* `make lint test`
Deployed latest `master` and ran the following:
```python
def main():
"""Unit tests"""
assert(1 == increment_counter("panther", 1))
assert(3 == increment_counter("labs", 3))
assert(-1 == increment_counter("panther", -2))
assert(-1 == increment_counter("panther", 0))
assert(10 == increment_counter("panther", 11))
assert(10 == get_counter("panther"))
assert(3 == get_counter("labs"))
assert(0 == get_counter("nonexistent"))
reset_counter("panther")
reset_counter("labs")
assert(0 == get_counter("panther"))
assert(0 == …
```
=> Add counter helper functions

osquery_rules/osquery_linux_aws_commands.yml, osquery_rules/osquery_linux_logins_non_office.yml, osquery_rules/osquery_mac_unwanted_chrome_extensions.yml, osquery_rules/osquery_ossec.yml, osquery_rules/osquery_suspicious_cron.yml
Changing reports to be of the form: map[string][]string
* Changing format of reports
* Deployed to account
=> Updated reports to use new format

Makefile, aws_cloudtrail_rules/aws_cloudtrail_created.py, aws_cloudtrail_rules/aws_cloudtrail_stopped.py, aws_cloudtrail_rules/aws_config_service_created.py, aws_cloudtrail_rules/aws_config_service_disabled_deleted.py, aws_cloudtrail_rules/aws_console_login_without_mfa.py, aws_cloudtrail_rules/aws_console_root_login.py, aws_cloudtrail_rules/aws_console_root_login.yml, aws_cloudtrail_rules/aws_console_root_login_failed.py, aws_cloudtrail_rules/aws_console_root_login_failed.yml, aws_cloudtrail_rules/aws_ec2_gateway_modified.py, aws_cloudtrail_rules/aws_ec2_network_acl_modified.py, aws_cloudtrail_rules/aws_ec2_route_table_modified.py, aws_cloudtrail_rules/aws_ec2_security_group_modified.py, aws_cloudtrail_rules/aws_ec2_vpc_modified.py, aws_cloudtrail_rules/aws_iam_policy_modified.py, aws_cloudtrail_rules/aws_kms_cmk_loss.py, aws_cloudtrail_rules/aws_root_activity.py, aws_cloudtrail_rules/aws_s3_bucket_deleted.py, aws_cloudtrail_rules/aws_s3_bucket_deleted.yml, aws_cloudtrail_rules/aws_s3_bucket_policy_modified.py, aws_cloudtrail_rules/aws_unauthorized_api_call.py, aws_cloudtrail_rules/aws_update_credentials.py, aws_s3_policies/aws_s3_bucket_secure_access.py, aws_s3_rules/aws_s3_insecure_access.py, aws_s3_rules/aws_s3_insecure_access.yml, aws_vpc_policies/aws_vpc_flow_logs.py, global_helpers/panther_oss_helpers.py
Small edits to CloudTrail rules
* Add rules for all login scenarios - IAMUsers vs Root, MFA vs not, Success vs Fail
* Update Makefile to lint all global/policy/rule folders
* Remove unnecessary usage of .get()
* panther analysis tool locally
=> CloudTrail Rule Updates

aws_cloudtrail_rules/aws_unauthorized_api_call.py, aws_cloudtrail_rules/aws_update_credentials.py, aws_cloudtrail_rules/aws_update_credentials.yml, aws_s3_rules/aws_s3_unknown_requester_get_object.py, global_helpers/panther_oss_helpers.py, global_helpers/panther_oss_helpers.yml
A collection of small updates
* Move some rule-based functions into generic helper functions
* Add a new case to the s3 unknown requester rule to account for Snowflake.
* Locally with the PAT
=> update s3 and cloudtrail rules

aws_cloudtrail_rules/aws_unauthorized_api_call.py, aws_s3_rules/aws_s3_access_error.py
Removing some false positives.
* No longer alert on `DescribeEventAggregates` unauthorized API calls, these just happen sometimes when clicking around the console without admin privileges
* No longer alert on `IncompleteBody` s3 access errors, these just happen sometimes when AWS services are talking to s3
* `make test`
=> Reducing some noise

aws_cloudtrail_rules/aws_unauthorized_api_call.py
Reducing more noise
* Adding another exception to the unauthorized API access rule. You were right Jack 🤣 
* `make test`
=> Reduce noise

aws_s3_rules/aws_s3_access_error.py, aws_s3_rules/aws_s3_access_ip_whitelist.py, aws_s3_rules/aws_s3_access_ip_whitelist.yml, aws_s3_rules/aws_s3_insecure_access.py, aws_s3_rules/aws_s3_unknown_requester_get_object.py
Russ found an unsafe lookup causing an error in the demo account, so I fixed it. I also fixed a few other unsafe lookups I found while poking around.
* Fixed some unsafe lookups
* `make test`
=> Fixed some unsafe lookups

aws_cloudtrail_rules/aws_iam_user_recon_denied.py
Set the threshold to 10 instead of 5
=> [cloudtrail] update threshold on recon rule

aws_cloudtrail_rules/aws_iam_user_recon_denied.yml, global_helpers/panther_oss_helpers.py
This helper function never worked.
* Fix broken helper
* Observed it properly working
=> Fix broken helpler

.github/CODEOWNERS
=> Remove Jack as CODEOWNER

requirements.txt
The requirements.txt file needs to be updated for CircleCI to be able to properly handle SummaryAttributes
(current version points to v0.3.4, SummaryAttributes was introduced in v0.3.5)
All changes are limited to the `requirements.txt` file
=> Updated using `make deps-update`

aws_cloudtrail_rules/aws_console_login_without_saml.yml
Change this display name to better identify the rule's purpose.
=> Change displayname

README.md, aws_s3_rules/aws_s3_unknown_requester_get_object.py, aws_s3_rules/aws_s3_unknown_requester_get_object.yml
Fixes small bug found during dogfood session causes alerts to fire when they shouldn't. Closes #118 
* fixed typo
* test case for snowflake
* `make ci`
=> bug fix - unknown requester

box_rules/box_access_granted.py, box_rules/box_access_granted.yml, box_rules/box_anomalous_download.py, box_rules/box_anomalous_download.yml, box_rules/box_brute_force_login.py, box_rules/box_brute_force_login.yml, box_rules/box_malicious_content.py, box_rules/box_malicious_content.yml, box_rules/box_new_login.py, box_rules/box_new_login.yml, box_rules/box_policy_violation.py, box_rules/box_policy_violation.yml, box_rules/box_suspicious_login_or_session.py, box_rules/box_suspicious_login_or_session.yml, box_rules/box_untrusted_device.py, box_rules/box_untrusted_device.yml, box_rules/box_user_downloads.py, box_rules/box_user_downloads.yml, box_rules/box_user_permission_updates.py, box_rules/box_user_permission_updates.yml, global_helpers/panther_base_helpers.py
Initial set of rules for `Box.Events` data source. Closes #95 
* New rules and tests cases for box events
* `make ci`
=> box initial ruleset

box_rules/box_user_permission_updates.py
Missing some share events in the permission update rule. This adds those events.
* Added missing "share" `event_type`s to permissions rules
* `make ci`
=> expand permission update

aws_cloudtrail_rules/aws_console_root_login_failed.yml, aws_cloudtrail_rules/aws_root_activity.yml, aws_cloudtrail_rules/aws_root_console_login.yml, aws_cloudtrail_rules/aws_root_failed_console_login.yml, aws_cloudtrail_rules/aws_security_configuration_change.py
We noticed a few irregularities/rooms for improvement in monitoring AWS root user activity.
* Remove duplicate login and failed login rules
* Add threshold to failed root logins
* Update the summary_attributes for the root activity rule
* Unit testing
=> Root activity monitoring tuning

gsuite_reports_rules/gsuite_permissions_delegated.py, gsuite_reports_rules/gsuite_permissions_delegated.yml
Fix title in gsuite permission delegated. Closes #125 
* updated title function verbiage and extraction
* updated test case with fields to extract
*`make ci`
=> gsuite perms delegated

aws_cloudtrail_rules/aws_resource_made_public.py, aws_cloudtrail_rules/aws_resource_made_public.yml
Add check for null requestParameters in CloudTrail resource made public rule
* check for null value
* added test case
* `make ci`
=>  resource made public rule error

Makefile, requirements.txt
Update requirements file and make file test stanza so that data models are supported and strict analysisID is enforced. 
* `make deps-update`
* minor change to make test stanza in makefile
* `make test`
=> update to panther analysis tool to enable data models

aws_cloudtrail_rules/aws_resource_made_public.py, aws_cloudtrail_rules/aws_security_configuration_change.py, aws_cloudtrail_rules/aws_unauthorized_api_call.yml, okta_rules/okta_admin_role_assigned.py, okta_rules/okta_geo_improbable_access.py, okta_rules/okta_geo_improbable_access.yml, onelogin_rules/onelogin_unusual_login.py, onelogin_rules/onelogin_unusual_login.yml
Several older rules don't have helpful `title` functions defined, so I've defined some here.
* Added or updated title function for the following rules:
* `aws_resource_made_public`
* `aws_security_configuration_changed`
* `okta_geo_improbable_access`
* `one_login_unusual_login`
* Added threshold to `aws_unauthorized_api_calls`
* Unit testing
Some of the new titles:
```
panther_analysis_tool test --path example
[INFO]: Testing analysis packs in example
AWS.CloudTrail.ResourceMadePublic
[PASS] S3 Made Publicly Accessible
[PASS] [title] s3.amazonaws.com resource made public by example-role
[PASS] S3 Not Made Publicly Accessible
[PASS] Null Request Parameters
[PASS] S3 Failed to make Publicly Accessible
[PASS] Empty Policy Payload
AWS.CloudTrail.SecurityConfigurationChange
[PASS] Security …
```
=> Title updates

data_models/gcp_data_model.yml, data_models/gsuite_data_model.py, data_models/gsuite_data_model.yml, data_models/onelogin_data_model.yml, standard_rules/admin_assigned.py
In the list of comments, I missed one within the "hidden conversations". This address that [comment](https://github.com/panther-labs/panther-analysis/pull/156#discussion_r545183014).
* Field rename in datamodels and the standard rule that uses them.
* `make ci`
=> feedback on field name

standard_rules/admin_assigned.yml, standard_rules/brute_force_by_ip.yml
Fixed typo in id. -_-
* typo fix
* `make ci`
=> data model typo

gcp_audit_rules/gcp_iam_admin_role_assigned.py, requirements-top-level.txt
Found some bugs.
* Fixed bad import
* Fixed requirements missing
* make test
=> Fix some issues

Makefile, osquery_rules/osquery_linux_aws_commands.yml, requirements.txt
Remove tech debt and ensure test failures cause overall `unit_tests` ci to fail.
* removed copying of files out to a tmp dir in the test stanza
* `circleci local execute -c .circleci/config.yml  --job unit_tests`
=> update makefile - remove tech debt

test_scenarios/jsonl_to_testfile.py, test_scenarios/send_data.py
More Cedar x Panther webinar assets
* Update the send_data script to support GSuite Logs
* Write a script to convert JSONL logs to test_data YAML logs
* YOLO (jk, we tested it for the webinar)
=> GSuite Scenario Testing Support

LICENSE.txt, README.md
=> Update license to AGPLv3

aws_cloudtrail_rules/aws_resource_made_public.py
> This is a temporary patch.
`policyuniverse` performs its own type-checking for `list` types, which does not conform with [Panther's custom `Sequence` sub-class](https://github.com/panther-labs/panther/blob/d1d816a2e16b4795d4ac28f9668039ae70b8ee1e/internal/log_analysis/rules_engine/src/immutable.py#L81).
For details see https://github.com/panther-labs/panther/issues/2550.
* Optionally import Panther's custom JSON encoder in order to provide `policyuniverse` with the correct input.
* JSON Serialize/deserialize the S3 Bucket Policy object in order to convert it to Python builtins.
* `panther_analysis_tool test --filter Filename=aws_resource_made_public.py`
* `/detections/rules/AWS.CloudTrail.ResourceMadePublic/edit/?section=functions` execute tests with `Run All` on Panther Enterprise …
=> Avoid errors from policyuniverse when passing PantherEvent instance

aws_config_policies/aws_config_global_resources.yml, standard_rules/unusual_login.yml
Fix logtype in standard rule; fix resourcetype in a policy
* change gsuite.events to gsuite.reports
* change AWS.Config.Meta to AWS.Config.Recorder.Meta
* `make ci`
* uploaded zip file to latest version of panther
=> logtype typos

aws_cloudtrail_rules/aws_resource_made_public.py, aws_s3_policies/aws_s3_bucket_secure_access.py, global_helpers/panther_audit.py, gsuite_reports_rules/gsuite_drive_overly_visible.py, gsuite_reports_rules/gsuite_drive_overly_visible.yml, gsuite_reports_rules/gsuite_drive_visibility_change.py, gsuite_reports_rules/gsuite_drive_visibility_change.yml
Add document info to the alert title to make it more useful.
* add `doc_title` to alert title
* linter did some things
* `make ci`
=> update gsuite title

requirements.txt
Upgrade `policyuniverse` Python package version.
For the corresponding change in Panther see also https://github.com/panther-labs/panther/pull/2705.
* Modify `requirements.txt` to include the latest version. 
* CI
=> Upgrade policyuniverse version

schemas/logs/aws/tests/cloud_trail_digest_tests.yml, schemas/logs/aws/tests/cloud_trail_insight_tests.yml, schemas/logs/aws/tests/cloud_trail_tests.yml, schemas/logs/aws/tests/vpc_dns_tests.yml, schemas/logs/aws/tests/waf_web_acl_tests.yml, schemas/logs/cloudflare/tests/firewall_tests.yml, schemas/logs/cloudflare/tests/http_request_tests.yml, schemas/logs/cloudflare/tests/spectrum_tests.yml, schemas/logs/g_suite/tests/reports_tests.yml, schemas/logs/gcp/audit_log.yml, schemas/logs/git_lab/api.yml, schemas/logs/git_lab/tests/api_tests.yml, schemas/logs/git_lab/tests/audit_tests.yml, schemas/logs/git_lab/tests/git_tests.yml, schemas/logs/git_lab/tests/integrations_tests.yml, schemas/logs/git_lab/tests/production_tests.yml, schemas/logs/gravitational/tests/teleport_audit_tests.yml, schemas/logs/juniper/security.yml, schemas/logs/one_login/tests/events_tests.yml, schemas/logs/slack/access_logs.yml, schemas/logs/sophos/tests/central_tests.yml
- This is the first PR for automated _sync_ of `mage schemas:push`
* Updates comments and descriptions on some fields
* N/A
=> [Sync] Native schema updates

schemas/logs/salesforce/insecure-external-assets.yml, schemas/logs/salesforce/login-as.yml, schemas/logs/salesforce/login.yml, schemas/logs/salesforce/logout.yml, schemas/logs/salesforce/uri.yml
Asana URL: Closes https://app.asana.com/0/1199958360112212/1199962428146516
Define parsers for select [Event Types](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_supportedeventtypes.htm) of [Salesforce Event Monitoring](https://trailhead.salesforce.com/en/content/learn/v/modules/event_monitoring/event_monitoring_intro).
* Add YAML specifications for each Event Log file type, see [documentation](https://docs.runpanther.io/data-onboarding/custom-log-types/example-csv).
All schemas [tested](https://docs.runpanther.io/data-onboarding/custom-log-types#testing-a-log-schema) with real samples, except for `InsecureExternalAssets` where a synthetic sample was used.
=> Define Salesforce Event Log file parsers

.github/workflows/main.yml, build/actions/README.md, build/actions/pr_sync/action.yml, build/actions/pr_sync/dist/index.js, build/actions/pr_sync/index.js, build/actions/pr_sync/package-lock.json, build/actions/pr_sync/package.json
* Added GitHub workflow and `pr_sync` build actions
=> GitHub Sync Workflow

Makefile, aws_account_policies/aws_password_policy_complexity_guidelines.py
Testing sync 
* Replaced direct key access with .get
=> PAD - Sync Test

.github/workflows/main.yml
Test fix for automation workflow
=> Test fix for git cli auth - dogfood automation worklow

.github/workflows/main.yml
Test - suspect the issue might be because the reference does not have a `.git` appended
=> Weyland automation test debug

schemas/logs/aws/vpc_flow.yml, schemas/logs/salesforce/login-as.yml, schemas/logs/salesforce/login.yml, schemas/logs/salesforce/logout.yml, schemas/logs/salesforce/uri.yml
Part of https://app.asana.com/0/1200054825984736/1200016362201342
https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-vpc-flow-logs-now-reflects-aws-service-name-traffic-path-and-flow-direction/
* Update VPC Flow Logs schema.
=> Add new VPC Flow Log fields

schemas/logs/microsoft_365/audit.azure_active_directory.yml, schemas/logs/microsoft_365/audit.exchange.yml, schemas/logs/microsoft_365/audit.general.yml, schemas/logs/microsoft_365/audit.share_point.yml, schemas/logs/microsoft_365/dlp.all.yml, schemas/logs/microsoft_365/tests/audit.azure_active_directory_tests.yml, schemas/logs/microsoft_365/tests/audit.exchange_tests.yml, schemas/logs/microsoft_365/tests/audit.general_tests.yml, schemas/logs/microsoft_365/tests/audit.share_point_tests.yml
- Microsoft365.Audit.AzureActiveDirectory
- Microsoft365.Audit.Exchange
- Microsoft365.Audit.General
- Microsoft365.Audit.SharePoint
- Microsoft365.DLP.All
Adding Microsoft365 log types
=> Adds Microsoft365 schemas

schemas/logs/slack/access_logs.yml, schemas/logs/slack/audit_logs.yml, schemas/logs/slack/integration_logs.yml, schemas/logs/slack/tests/slacklogs_tests.yml
Closes https://app.asana.com/0/0/1200129853533107/f
* Remove native parser from slack schemas
* Add test file
* pantherlog test ./schemas
=> Migrate Slack schemas and add tests

aws_account_policies/aws_resource_required_tags.yml
Add `ResourceType` field to ensure tests are covering branches in code.
* added field to test cases
* `make test`
=> [quickfix] add required field to test cases

schemas/logs/crowdstrike/activity_audit.yml, schemas/logs/crowdstrike/detection_summary.yml, schemas/logs/crowdstrike/dns_request.yml, schemas/logs/crowdstrike/group_identity.yml, schemas/logs/crowdstrike/network_connect.yml, schemas/logs/crowdstrike/network_listen.yml, schemas/logs/crowdstrike/process_rollup_2.yml, schemas/logs/crowdstrike/synthetic_process_rollup_2.yml, schemas/logs/crowdstrike/unknown.yml, schemas/logs/crowdstrike/user_identity.yml
Syncs latest changes to Crowdstrike logs
* Adds Crowdstrike.ActivityAudit
* Adds missing trace_id indicators
* pantherlog test ./schemas
=> Sync changes in crowdstrike logs

templates/example_rule.py, templates/example_rule.yml
Customer requested a rule template to refer to like the policy template already in PA.
* example_rule.py
* example_rule.yml
* Nothing to test, just a generic template
=> Example Rule Template

Makefile, aws_acm_policies/aws_acm_certificate_expiration.py, aws_iam_policies/aws_access_key_rotation.py, aws_iam_policies/aws_access_key_unused.py, aws_iam_policies/aws_password_unused.py, global_helpers/panther_oss_helpers.py, templates/example_rule.py
Fix some formatting issues.
* Ran `make fmt test`
* Updated make file to apply formatting & linting to  templates
* `make test`
=> Fix some formatting

aws_account_policies/aws_resource_required_tags.yml, gsuite_reports_rules/gsuite_drive_visibility_change.py, requirements.txt, templates/example_rule.py
Add missing resourcetype in test spec.
* add missing field
* `make deps-update`
* `make ci`
=> add missing resourcetype

requirements.txt
Cleaned venv and reran deps-update
* `make deps-update`
* `make ci`
=> deps-update with clean venv

aws_config_policies/aws_config_global_resources.py, aws_config_policies/aws_config_global_resources.yml
The tests were commented out pending mocking support. This PR adds support for unit test mocking for these uncommented tests.
* Replaced commented out tests with mocking to provide examples
* `panther_analysis_tool test --path=./`
=> Config Global Resources - Mocking Support

global_helpers/panther_box_helpers.py, requirements.txt, test_scenarios/gsuite-sensitive-files/shared_files.yml, test_scenarios/jsonl_to_testfile.py, test_scenarios/okta-add-administrator/README.md, test_scenarios/okta-add-administrator/admin_privs_assigned.yml, test_scenarios/okta-add-administrator/brute_force_logins.yml, test_scenarios/okta-add-administrator/legit_login.yml, test_scenarios/okta-add-administrator/new-user.yml, test_scenarios/okta-add-administrator/run_all.sh, test_scenarios/send_data.py
These scripts can be used to send synthetic test events to Panther and for converting downloaded CSVs into a format that can be replayed. 
* Support CSV to Testfile conversion
* Add some more scenarios
* Add clarity to the send_data script
* Used for multiple demos, already
=> Update Test Scenario Scripts + New Sample Data

github_rules/github_repo_initial_access.yml
Two small fixes found when dogfooding.
* Update copypasta display name
* downgrade sev for initial access
* `make ci`
=> update display name and sev level

build/actions/README.md
Discovered minor typos while reviewing codebase
Readme Typo fixes only
* None, No functional code changes made
=> Fix a couple README typos

gsuite_reports_rules/gsuite_drive_visibility_change.py
Rule was not processing all `change_user_access` events
* Added logic to account for multiple users
* Added `alert_context` to show list of users to whom doc was shared
* `make fmt lint`
* `panther_analysis_tool test --path gsuite_reports_rules`
* live system
=> Fix logic error for multiple users

gsuite_reports_rules/gsuite_drive_visibility_change.py
Inefficient looping structure.
* Modified loop for user domain checking
* `make fmt lint`
* `panther_analysis_tool test --path gsuite_reports_rules`
=> Loop efficiency

aws_iam_policies/aws_iam_policy_does_not_grant_network_admin_access.yml, aws_iam_policies/aws_iam_resource_does_not_have_inline_policy.yml, aws_queries/cloudtrail_password_spraying.yml, aws_queries/vpc_dns_tunneling.yml, aws_vpc_policies/aws_network_acl_restricts_inbound_traffic.yml, aws_vpc_policies/aws_network_acl_restricts_outbound_traffic.yml, aws_vpc_policies/aws_only_dmz_security_groups_publicly_accessible.yml, aws_vpc_policies/aws_security_group_restricts_access_to_cde.yml, aws_vpc_policies/aws_security_group_restricts_inbound_traffic.yml, aws_vpc_policies/aws_security_group_restricts_inter_security_group_traffic.yml, aws_vpc_policies/aws_security_group_restricts_outbound_traffic.yml, aws_vpc_policies/aws_security_group_restricts_traffic_leaving_cde.yml, aws_vpc_policies/aws_security_group_tightly_restricts_inbound_traffic.yml, aws_vpc_policies/aws_security_group_tightly_restricts_outbound_traffic.yml, aws_vpc_policies/aws_security_group_unused_security_group.yml
Some detections were missing `DisplayName`.
* Added `DisplayName` attribute to several detections
* n/a
=> Add missing display names

aws_cloudtrail_rules/aws_console_login_without_mfa.py, aws_cloudtrail_rules/aws_console_login_without_mfa.yml, global_helpers/panther_oss_helpers.py
Reverts panther-labs/panther-analysis#315
Experiencing errors:
`ClientError('An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema')`
=> Revert "Add new user check"

gsuite_activityevent_rules/gsuite_external_forwarding.yml
Bug fix, extra space is causing uploads to blow up
Removed a space from the MITRE description
CI/CD and Unit tests
=> Remove Spurious Space

Pipfile.lock, data_models/zendesk_data_model.yml, packs/zendesk.yml, standard_rules/admin_assigned.yml, standard_rules/mfa_disabled.yml, standard_rules/unusual_login.yml, zendesk_rules/zendesk_mobile_app_access.yml, zendesk_rules/zendesk_new_api_token.yml, zendesk_rules/zendesk_new_owner.yml, zendesk_rules/zendesk_sensitive_data_redaction.yml, zendesk_rules/zendesk_user_assumption.yml, zendesk_rules/zendesk_user_role.yml, zendesk_rules/zendesk_user_suspension.yml
Incorrect log type / schema name in the zendesk detections.  This fixes them!
* `1,$s/Zendesk.AuditLog/Zendesk.Audit/`
* `make test`
=> fix logtype name

aws_s3_policies/aws_s3_bucket_secure_access.py
Correct wrong case on `Name` key
* n => N
* CI/ Unit tests
=> Correct case on Name key

aws_s3_policies/aws_s3_bucket_principal_restrictions.yml
Corrected grammatically confusing description.
* Updated `Description`
* n/a
=> Clarify runbook

packs/standard_ruleset.yml, packs/zoom.yml
Creating a Pack for Zoom and modifying Standard Pack to include Zoom detections
* See above
* CI/Unit testing
=> Create Zoom Pack and Add Zoom to Standard Pack

global_helpers/panther_iocs.py
=> Log4j: Upper

panther_ioc_rules/log4j_exploit_iocs.py, panther_ioc_rules/log4j_exploit_iocs.yml
HaCkErS tYpE lIkE tHiS
* Normalize data to lowercase before check
* New Unit test
=> Make check case-insensitive

Pipfile.lock
Routine dependency update
* Update Pipfile
* n/a
=> Deps update

Pipfile.lock, data_models/atlassian_data_model.py, data_models/atlassian_data_model.yml, global_helpers/panther_iocs.py, standard_rules/admin_assigned.yml, standard_rules/brute_force_by_ip.yml, standard_rules/mfa_disabled.yml, standard_rules/unusual_login.yml
New Log type Added
Created Datamodel for Atlassian, added to standard detections
* Unit tests
=> Created Atlassian Datamodel and Add to Standard Detections

data_models/asana_data_model.py, packs/log4j.yml
Creates Log4J detection Pack
Create pack definition yaml
* unit tests
=> Create Log4J pack

panther_ioc_rules/log4j_exploit_iocs.yml
Mis-typed a field
* Un-Mis-Typed
* Unit tests
=> Fix a Typo

aws_cloudtrail_rules/aws_iam_anything_changed.yml
Customer discovered a non-valid reference link in this config
Added a link to Cloudtrail docs
*Unit Tests
=> Put valid reference link in rule metadata

packs/standard_ruleset.yml
Add forgotten DataModels to Standard Detections Pack
See above
Unit tests
=> Add missing DataModels

.github/CODEOWNERS, Pipfile.lock
Updating PAT, remove departed user from CODEOWNERS.
Updates to Package version for PAT, CODEOWNERS cleanup
Ensured all required functionality of PAT worked. Upload, test, etc
=> Update PAT version/ Remove Glerb from Codeowners

okta_queries/okta_activity_audit.yml, okta_queries/okta_mfa_password_reset_audit.yml, okta_queries/okta_session_id_audit.yml, okta_queries/okta_support_access.yml
Making comments in saved queries a bit more clear
Just comment changes, no logic changes
Unit Tests
=> Update language on queries

crowdstrike_rules/crowdstrike_detection_passthrough.py, crowdstrike_rules/crowdstrike_detection_passthrough.yml, crowdstrike_rules/crowdstrike_dns_request.py, crowdstrike_rules/crowdstrike_dns_request.yml, global_helpers/panther_base_helpers.py, okta_rules/okta_api_key_created.yml, okta_rules/okta_api_key_revoked.py, okta_rules/okta_api_key_revoked.yml
Port Detections we've been testing internally for Crowdstrike to public repo
Add new Detections
Add Context Helper
Some minor repo cleanup
Unit tests / linter and format
=> Initial Crowdstrike Detections 

global_helpers/panther_greynoise_helpers.py
This Method did not properly return a boolean.
Add "Is None" check
Unit / Manual tests
=> Fix 'is_riot' method to correctly return a boolean

Pipfile.lock, global_helpers/panther_greynoise_helpers.py, lookup_tables/greynoise/advanced/noise_advanced.yml, lookup_tables/greynoise/advanced/riot_advanced.yml, lookup_tables/greynoise/basic/noise_basic.yml, lookup_tables/greynoise/basic/riot_basic.yml, packs/greynoise_advanced.yml, packs/greynoise_basic.yml
Add Apache log sources to GreyNoise Lookup Tables
Add Context function to GreyNoise Helpers
Fix bug with generating a URL in the RIOT Classes 
See Above
Unit Tests, Manual testing in Internal Security Panther
=> Add Apache logs to GreyNoise Schemas, add Context theme

packs/greynoise_advanced.yml, packs/greynoise_basic.yml
Missing helper dependency
Add Helper
Unit
=> add helper dependancy to GreyNoise pack

Pipfile, Pipfile.lock, aws_cloudtrail_rules/aws_s3_activity_greynoise.py, data_models/gcp_data_model.py, data_models/gcp_data_model.yml, github_rules/github_team_modified.py, standard_rules/admin_assigned.yml
Closes https://app.asana.com/0/1202002271043343/1202058632039542/f
Add Support for multiple IAM adds to GCP data model
Pin Click dependency of  Black to remediate this bug https://github.com/psf/black/issues/2964. (updating Black when we update to Python 3.9 shortly)
Make fmt on some files that didnt get it pre-merge
Unit testing
=> Support Multiple IAM adds for GCP data model

Makefile, Pipfile, Pipfile.lock, aws_cloudtrail_rules/aws_codebuild_made_public.py, data_models/gcp_data_model.py, data_models/zendesk_data_model.py, global_helpers/panther_oss_helpers.py, standard_rules/unusual_login.py
With the recent update to Python 3.9 it seems like a good time to update dev deps
Update deps, pin to minor release instead of patch versions
Minor changes to satisfy Pylints new version
Unit testing
=> Dependency Update 

data_models/gcp_data_model.py, global_helpers/panther_greynoise_helpers.py
Couple small changes to GreyNoise Helpers to improve usability
Added a Severity helper  function to provide a simple dynamic severity
Made Context function more verbose for Advanced subscribers
Tested internally with Greynoise test rules + Unit tests
=> GreyNoise Enhancements

Pipfile, Pipfile.lock, data_models/gcp_data_model.py, data_models/panther_audit_data_model.py, data_models/panther_audit_data_model.yml, packs/panther.yml, panther_audit_rules/panther_detection_deleted.py, panther_audit_rules/panther_detection_deleted.yml, panther_audit_rules/panther_saml_modified.py, panther_audit_rules/panther_saml_modified.yml, panther_audit_rules/panther_sensitive_role_created.py, panther_audit_rules/panther_sensitive_role_created.yml
Detections for initial Panther audit logs
Create new detections
Unit tests
=> Create Panther Audit Detections

packs/aws.yml
Default Panther Helpers missing from Packs
Added helpers
Unit Testing
=> Add missing helper to AWS pack

Pipfile, Pipfile.lock, data_models/gcp_data_model.py, global_helpers/panther_oss_helpers.py
Relates to https://app.asana.com/0/1200821831799747/1202272138102935/f
We recently decoupled the shared components in PAT to a separate library `panther-core`. This PR updates references to PAT in detections and adds `panther-core` as a dependency
* Updated two detections that import PAT
* Updated Pipfile
* `make ci`
=> Update References PAT=>PAC

standard_rules/brute_force_by_ip.py
The comment for the brute force by IP is confusing and misleading.
* Removed comment
* N/A
=> Confusing Comment in Brute Force by IP

data_models/slack_accesslogs_data_model.yml, data_models/slack_auditlogs_data_model.yml, data_models/slack_integrationlogs_data_model.yml, global_helpers/panther_base_helpers.py, onepassword_rules/onepassword_unusual_client.yml
This PR adds Data Models for `Slack.AccessLogs` `Slack.AuditLogs` and `Slack.IntegrationLogs` as well as a new helper for slack alert contexts
=> Slack Data Models & Alert Context Helper

slack_rules/slack_private_channel_made_public.py, slack_rules/slack_private_channel_made_public.yml, slack_rules/slack_service_owner_transferred.py, slack_rules/slack_service_owner_transferred.yml
This PR includes new detections for the Slack Channel logs.
* Service Owner Transferred
* Private Channel Made Public
=> Slack Detections - Channel

slack_rules/slack_potentially_malicious_file_shared.py, slack_rules/slack_potentially_malicious_file_shared.yml
This PR includes new detections for the File logs.
* Potentially Malicious File Shared
=> Slack Detections - File

slack_rules/slack_app_access_expanded.py, slack_rules/slack_app_access_expanded.yml, slack_rules/slack_app_added.py, slack_rules/slack_app_added.yml, slack_rules/slack_app_removed.py, slack_rules/slack_app_removed.yml
This PR includes new detections for the App logs.
* App Access Expanded
* App Added
* App Removed
=> Slack Detections - App

slack_rules/slack_ekm_config_changed.py, slack_rules/slack_ekm_config_changed.yml, slack_rules/slack_ekm_slackbot_unenrolled.py, slack_rules/slack_ekm_slackbot_unenrolled.yml, slack_rules/slack_ekm_unenrolled.py, slack_rules/slack_ekm_unenrolled.yml
This PR includes new detections for the EKM logs.
* EKM Config Changed
* EKM Slackbot Unenrolled
* EKM Unenrolled
=> Slack Detections - EKM

slack_rules/slack_passthrough_anomaly.py, slack_rules/slack_passthrough_anomaly.yml, slack_rules/slack_user_privilege_escalation.py, slack_rules/slack_user_privilege_escalation.yml
This PR includes new detections for the User logs.
* Passthrough Anomaly Detection 
* User Privilege Escalation
=> Slack Detections - User

packs/snowflake.yml
Created a pack for the snowflake detections
packs/snowflake.yml
=> create pack for snowflake detections

packs/onepassword.yml, packs/snowflake.yml
Snowflake pack was missing the queries it needed. 
* 
*
=> fix: Packs based on scheduled queries also need the scheduled queries to be defined in the pack.

lookup_tables/greynoise/advanced/noise_advanced.yml, lookup_tables/greynoise/advanced/riot_advanced.yml, lookup_tables/greynoise/basic/noise_basic.yml, lookup_tables/greynoise/basic/riot_basic.yml, lookup_tables/ipinfo/asn.yml, lookup_tables/ipinfo/location.yml
Fix copy paste issue with primary key
* change `ip_cidr` to `ip`
=> Fix primary key issue

rules/standard_rules/unusual_login.py, rules/standard_rules/unusual_login.yml
Unusual Login detection was alerting on first logins.
* Added check to not alert on first instance of login
* Added unit test with no login history
=> check not first login, test case

global_helpers/panther_oss_helpers.py, policies/aws_iam_policies/aws_iam_policy_administrative_privileges.yml
listify should return a list for dicts too. Currently it does not, which can cause an AttributeError in some cases.
=> listify should also return [maybe_list] for dicts

README.md, rules/aws_cloudtrail_rules/aws_rds_master_pass_updated.py, rules/aws_cloudtrail_rules/aws_rds_master_pass_updated.yml, templates/example_rule.py, templates/example_rule.yml
* New Rule: AWS RDS Master Pass Changed
* Updated README with latest marketing language + fixed small errors + removed old directory listing
* Developed and live-tested in Console
* Validated via local rule testing
=> Updated README + RDS Pass Updated Rule

rules/aws_cloudtrail_rules/aws_ec2_startup_script_change.yml, rules/aws_cloudtrail_rules/aws_ipset_modified.yml, rules/aws_cloudtrail_rules/aws_rds_publicrestore.yml, rules/aws_cloudtrail_rules/aws_securityhub_finding_evasion.yml, rules/aws_cloudtrail_rules/aws_user_login_profile_modified.yml
Enabled rules from sigma high detections
enabled rules
n/a
=> enable new rules

queries/aws_queries/ec2_crud_activity_by_role_query.yml, queries/aws_queries/ec2_crud_activity_by_useragent_query.yml
Query to get ec2 crud activity by user agent.
query added
=> ec2 crud activity queries

global_helpers/panther_base_helpers.py, rules/aws_cloudtrail_rules/aws_unused_region.py, rules/aws_cloudtrail_rules/aws_unused_region.yml
Background
[MITRE IaaS Gap] - T1535 Unused/Unsupported Cloud Regions
Changes
New detection
Added fields to `aws_rule_context()`
=> CP - 1 new AWS Odin detection

Makefile, Pipfile, Pipfile.lock, rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.py
remove print statement from rule
=> remove print statements

Pipfile.lock, global_helpers/panther_base_helpers.py, rules/microsoft_graph/microsoft_graph_passthrough.py, rules/microsoft_graph/microsoft_graph_passthrough.yml
Passthrough detection for microsoft graph
=> microsoft graph passthrough

rules/aws_cloudtrail_rules/aws_iam_user_key_created.py, rules/aws_cloudtrail_rules/aws_iam_user_key_created.yml
needed a default value in deep_get
=> add default

Pipfile, Pipfile.lock, packs/crowdstrike.yml
Crowdstrike detections weren't bundled into a pack. 
* create pack for crowdstrike detections
* update the required version of `panther_analysis_tool` 
*
=> feat: Crowdstrike pack

rules/gsuite_reports_rules/gsuite_drive_visibility_change.py
Bug in title of gsuite drive visibility detection
bugfix
make test
=> gsuite drive visibility title bug

global_helpers/panther_base_helpers.py, rules/aws_guardduty_rules/aws_guardduty_high_sev_findings.py, rules/aws_guardduty_rules/aws_guardduty_low_sev_findings.py, rules/aws_guardduty_rules/aws_guardduty_med_sev_findings.py, rules/microsoft_graph/microsoft_graph_passthrough.py
Guardduty detections were using cloud trail context helper. Changed to use guardduty fields and added guardduty helper.
* guard duty detections
*ci
=> guardduty context

packs/gsuite_reports.yml
Add missing data model to the gsuite pack.
* add the data model id 
* `make test`
=> update gsuite pack to include data model

rules/gsuite_reports_rules/gsuite_drive_external_share.py
Remove Athena query from GWS External Share
* See above
* Repo has no automated tests
=> remove outdated sample query

packs/aws.yml, packs/zoom.yml
* Added rules to aws pack and data model referenced in zoom pack. Dependency checks completed for both packs in their current states.
=> shipping QA'ed pack updates

packs/panther.yml, rules/panther_audit_rules/panther_user_modified.py, rules/panther_audit_rules/panther_user_modified.yml
This changeset creates a detection that fires when a Panther user is modified. 
* 
*
=> feat: a detection that alerts when a panther user is modified

queries/aws_queries/anomalous_access_denied.yml, queries/aws_queries/anomalous_role_assume.yml, queries/aws_queries/anomalous_vpc_port_activity.yml
AWS Queries 
Anomalous RoleAssume
Anomalous AccessDenied
Anomalous VPC Flow Activity
3 Queries
make test
=> aws queries

queries/aws_queries/anomalous_access_denied_query.yml, queries/aws_queries/anomalous_role_assume_query.yml, queries/aws_queries/anomalous_vpc_port_activity.yml, queries/aws_queries/anomalous_vpc_port_activity_query.yml
Tuned VPC Flow scanning query and added rule to add mitre tags
make test
=> scheduled query vpc scanning

packs/aws.yml
* Added the following (already existing) rules to pack and qa'ed, ready to ship to customers.
- AWS.EC2.EBS.Encryption.Disabled
- AWS.EC2.GatewayModified
- AWS.EC2.Monitoring
- AWS.EC2.NetworkACLModified
- AWS.EC2.RouteTableModified
- AWS.EC2.VPCModified
- AWS.Console.RootLogin
- AWS.EC2.SecurityGroupModified
- AWS.CloudTrail.IAMAnythingChanged
- AWS.CloudTrail.Created
- AWS.CloudTrail.Stopped
- AWS.CloudTrail.CodebuildProjectMadePublic
- AWS.ConfigService.Created
- AWS.ConfigService.DisabledDeleted
- AWS.EC2.Startup.Script.Change
=> shipping qa'ed additions to pack (already exsisting rules only)

rules/microsoft_graph/microsoft_graph_passthrough.yml
=> MS Graph Pack: Better description

packs/aws.yml
adds the new EKS detections into the AWS pack and updates the AWS pack description
*  
*
=> fix: add new EKS detections to the AWS pack. update AWS pack description

Pipfile, Pipfile.lock, packs/sentinelone.yml, rules/sentinelone_rules/sentinelone_alert_passthrough.py, rules/sentinelone_rules/sentinelone_alert_passthrough.yml, rules/sentinelone_rules/sentinelone_threats.py, rules/sentinelone_rules/sentinelone_threats.yml
SentinelOne passthroughs
* passthrough alerts and threats
* add to pack
* update PAT to use s1 schemas
* make ci
=> sentinelone passthrough

packs/aws.yml
removed unnecessary whitespace and added the following two existing s3 rules to pack after QA.
- AWS.S3.ServerAccess.Error
- AWS.S3.ServerAccess.Insecure
=> adding existing enabled s3 rules to prod after QA

packs/aws.yml
- AWS.DNS.Crypto.Domain
- AWS.VPC.HealthyLogStatus
=> adding qa'ed vpc flow rules to aws pack to make available to our customers

rules/github_rules/github_organization_app_integration_installed.yml
Change enabled Key in rule to true so it's on out of the box for customers
=> Key fix in yml for newly merged Github App Installation for Organization Rule

rules/gsuite_activityevent_rules/gsuite_workspace_data_export_created.py, rules/gsuite_activityevent_rules/gsuite_workspace_data_export_created.yml, rules/gsuite_activityevent_rules/gsuite_workspace_trusted_domains_allowlist.py, rules/gsuite_activityevent_rules/gsuite_workspace_trusted_domains_allowlist.yml
GSuite Workspace admins can modify the list of trusted domains
* 
* `make test` 
```shell
user@computer:panther-analysis $ pipenv run panther_analysis_tool test --filter RuleID=GSuite.Workspace.DataExportCreated
GSuite.Workspace.DataExportCreated
[PASS] Workspace Admin Data Export Created
[PASS] [title] GSuite Workspace Data Export [CUSTOMER_TAKEOUT_CREATED] performed by [admin@example.io]
[PASS] [dedup] GSuite Workspace Data Export [CUSTOMER_TAKEOUT_CREATED] performed by [admin@example.io]
[PASS] Workspace Admin Data Export Succeeded
[PASS] [title] GSuite Workspace Data Export [CUSTOMER_TAKEOUT_SUCCEEDED] performed by [admin@example.io]
[PASS] [dedup] GSuite Workspace Data Export [CUSTOMER_TAKEOUT_SUCCEEDED] …
```
=> feat: GSuite detections for admins modifying the trusted domains list and for admins executing a data export

rules/gsuite_activityevent_rules/gsuite_workspace_gmail_security_sandbox_disabled.py, rules/gsuite_activityevent_rules/gsuite_workspace_gmail_security_sandbox_disabled.yml, rules/gsuite_activityevent_rules/gsuite_workspace_password_enforce_strong_disabled.py, rules/gsuite_activityevent_rules/gsuite_workspace_password_enforce_strong_disabled.yml, rules/gsuite_activityevent_rules/gsuite_workspace_password_reuse_enabled.py, rules/gsuite_activityevent_rules/gsuite_workspace_password_reuse_enabled.yml
Gsuite detections, three
1. GMail's Security Sandbox feature has been disabled
2. GSuite Workspace Strong Password Enforcement has been disabled
3. GSuite Workspace Password Reuse has been enabled
```shell
user@computer:~/Sources/PAN/panther-analysis $ pipenv run panther_analysis_tool test --filter RuleID=GSuite.Workspace.GmailSecuritySandboxDisabled,GSuite.Workspace.PasswordEnforceStrongDisabled,GSuite.Workspace.PasswordReuseEnabled
GSuite.Workspace.GmailSecuritySandboxDisabled
[PASS] Workspace Admin Disables Security Sandbox
[PASS] [title] GSuite Gmail Security Sandbox was disabled for [Example IO] by [example@example.io]
[PASS] [dedup] GSuite Gmail Security Sandbox was disabled for [Example IO] by [example@example.io]
[PASS] Admin …
```
=> feat: gsuite detections around securitysandbox and password settings

packs/gsuite_reports.yml, rules/gsuite_activityevent_rules/google_workspace_admin_custom_role.py, rules/gsuite_activityevent_rules/google_workspace_admin_custom_role.yml
adding newly created rule to monitor when google workspace admin provisions a custom role
*
=> New Google Workspace Rule to Monitor When Admin Provisions Custom Role

rules/okta_rules/okta_threatinsight_security_threat_detected.py, rules/okta_rules/okta_threatinsight_security_threat_detected.yml, rules/okta_rules/okta_user_account_locked.py, rules/okta_rules/okta_user_account_locked.yml, rules/okta_rules/okta_user_mfa_factor_suspend.py, rules/okta_rules/okta_user_mfa_factor_suspend.yml, rules/okta_rules/okta_user_mfa_reset_all.py, rules/okta_rules/okta_user_mfa_reset_all.yml, rules/okta_rules/okta_user_reported_suspicious_activity.py, rules/okta_rules/okta_user_reported_suspicious_activity.yml
* okta_threatinsight_security_threat_detected
* okta_user_account_locked
* okta_user_mfa_factor_suspend
* okta_user_mfa_reset_all
* okta_user_reported_suspicious_activity
=> Okta detections pt2

packs/gsuite_reports.yml, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_allowlist.py, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_allowlist.yml
* Added newly written rule that monitors and alerts on events related to Google Workspace Apps Marketplace Allowlist changes.
*
=> Newly Written Rule: Google Workspace Apps Marketplace Allowlist

packs/gsuite_reports.yml, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_new_domain_application.py, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_new_domain_application.yml
* adding newly written rule to monitor and alert on new domain applications from the google workspace apps marketplace being enabled
*
=> Newly Written Rule to monitor and alert on new domain applications being enabled from the google workspace apps marketplace

packs/gsuite_reports.yml, rules/gsuite_activityevent_rules/google_workspace_advanced_protection_program.py, rules/gsuite_activityevent_rules/google_workspace_advanced_protection_program.yml
adding newly written detection to monitor and alert on google workspace advanced protection program changes
*
=> Newly Written Detection - Google Workspace Advanced Protection Program

packs/gsuite_reports.yml, rules/gsuite_activityevent_rules/google_workspace_apps_new_mobile_app_installed.py, rules/gsuite_activityevent_rules/google_workspace_apps_new_mobile_app_installed.yml
* added newly written rule to monitor when a new mobile app is installed in the google workspace apps directory
*
=> New Rule to monitor and alert on new mobile apps added to an org's mobile app whitelist in google workspace apps

packs/duo.yml, rules/duo_rules/duo_admin_app_integration_secret_key_viewed.py, rules/duo_rules/duo_admin_app_integration_secret_key_viewed.yml
* adding new duo rule to monitor and alert when admin views secret key for an application
*
=> New rule: Duo Admin App Integration Secret Key Viewed

packs/duo.yml, rules/duo_rules/duo_admin_bypass_code_created.py, rules/duo_rules/duo_admin_bypass_code_created.yml
* Newly added duo rule monitoring and alerting on duo admin's creating mfa bypass codes for an application.
*
=> New Duo Rule: Admin created a MFA bypass token for an application

global_helpers/panther_duo_helpers.py, global_helpers/panther_duo_helpers.yml, packs/duo.yml, rules/duo_rules/duo_admin_marked_push_fraudulent.py, rules/duo_rules/duo_admin_marked_push_fraudulent.yml, rules/duo_rules/duo_user_bypass_code_used.py, rules/duo_rules/duo_user_bypass_code_used.yml, rules/duo_rules/duo_user_endpoint_failure_multi.py, rules/duo_rules/duo_user_endpoint_failure_multi.yml
- duo_admin_marked_push_fraudulent
- duo_user_bypass_code_used
- duo_user_endpoint_failure_multi
```
[INFO]: Testing analysis items in rules/duo_rules/
DUO.Admin.Action.MarkedFraudulent
[PASS] marked_fraud
[PASS] [title] Duo Admin [John P. Admin] denied due to an anomalous 2FA push for [example@example.io]
[PASS] [dedup] Duo Admin [John P. Admin] denied due to an anomalous 2FA push for [example@example.io]
[PASS] [alertContext] {"reason": "Login request reported as fraudulent.", "reporting_admin": "John P. Admin", "user": "example@example.io", "ip_address": "12.12.12.12"}
[PASS] different_admin_action
DUO.User.Action.Fraudulent
[PASS] user_marked_fraud
[PASS] [title] A Duo action was marked as fraudulent by [example@example.io] …
```
=> New Duo Rules - Authentication and Administration

packs/duo.yml, rules/duo_rules/duo_admin_bypass_code_viewed.py, rules/duo_rules/duo_admin_bypass_code_viewed.yml
* adding new duo rule to monitor and alert on when an admin views a user's mfa bypass code
*
=> New Duo Rule: Duo Admin Bypass Code Viewed

packs/duo.yml, rules/duo_rules/duo_admin_lockout.py, rules/duo_rules/duo_admin_lockout.yml
* newly written duo rule to alert on admin lockout
* updated test results:
=> New Rule: Duo Admin Lockout

global_helpers/panther_duo_helpers.py, rules/duo_rules/duo_admin_create_admin.py, rules/duo_rules/duo_admin_create_admin.yml, rules/duo_rules/duo_admin_mfa_restrictions_updated.py, rules/duo_rules/duo_admin_mfa_restrictions_updated.yml, rules/duo_rules/duo_admin_new_admin_api_app_integration.py, rules/duo_rules/duo_admin_new_admin_api_app_integration.yml, rules/duo_rules/duo_admin_policy_updated.py, rules/duo_rules/duo_admin_policy_updated.yml, rules/duo_rules/duo_admin_sso_saml_requirement_disabled.py, rules/duo_rules/duo_admin_sso_saml_requirement_disabled.yml, rules/duo_rules/duo_admin_user_mfa_bypass_enabled.py, rules/duo_rules/duo_admin_user_mfa_bypass_enabled.yml
New detections:
- Admin Create
- MFA restrictions Updated
- new admin api integration
- admin policy updated
- sso saml requirement disabled
- admin user mfa bypass 
```Duo.Admin.Create.Admin
[PASS] Admin Create
[PASS] [title] Duo: [Bart Simpson] created a new admin account for [Homer Simpson] [homer.simpson@simpsons.com].
[PASS] [dedup] Duo: [Bart Simpson] created a new admin account for [Homer Simpson] [homer.simpson@simpsons.com].
[PASS] [alertContext] {"action": "admin_create", "description": "{\"name\": \"Homer Simpson\", \"phone\": null, \"is_temporary_password\": false, \"email\": \"homer.simpson@simpsons.com\", \"hardtoken\": null, \"role\": \"Owner\", \"status\": \"Pending Activation\", \"restricted_by_admin_units\": false, \"administrative_units\": \"\"}", …
```
=> Calkim duo detections

rules/aws_cloudtrail_rules/aws_software_discovery.py, rules/aws_cloudtrail_rules/aws_software_discovery.yml
Created odin aws discovery rule
=> AWS discovery Rules

templates/example_cidr_lookup_table.yml
=> Fix example lookup table yml

global_helpers/global_helpers_test.py, global_helpers/panther_cloudflare_helpers.py, rules/cloudflare_rules/cloudflare_firewall_ddos.py, rules/cloudflare_rules/cloudflare_firewall_ddos.yml, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked.py, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked.yml, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.py, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.yml, rules/cloudflare_rules/cloudflare_firewall_suspicious_event_greynoise.py, rules/cloudflare_rules/cloudflare_firewall_suspicious_event_greynoise.yml, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.py, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.yml, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume_greynoise.py, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume_greynoise.yml
🚨   🚨   This PR changes the `alert_context` output for all of the CloudFlare rules 🚨   🚨   
**Updates to existing CloudFlare rules**
1. Titles have been expanded to transfer more information
2. Thresholds have generally been upped. _I think we should consider adding another zero on the httpreq bot Thresholds_
3. Dedups have been updated to align with how the detections work
4. Added two global helpers for alert_contexts
5. ...with unit tests 😃
6. There was some casing mismatch between the current firewall log contents and the existing cloudflare helper called `map_source_to_name`
7. I updated `map_source_to_name()` to take `event` as an argument in a backwards compatible way so current callers do will need to change their behavior
* 
```shell
Cloudflare.Firewall.L7DDoS
[PASS] Traffic …
```
=> feat: CloudFlare rules needed tweaking to their dedup and titles.

policies/aws_vpc_policies/aws_security_group_restricts_access_to_cde.yml, policies/aws_vpc_policies/aws_security_group_restricts_traffic_leaving_cde.yml
=> fix: minor misspelling in tag

rules/asana_rules/asana_team_privacy_public.py, rules/asana_rules/asana_team_privacy_public.yml, rules/asana_rules/asana_workspace_default_session_duration_never.py, rules/asana_rules/asana_workspace_default_session_duration_never.yml, rules/asana_rules/asana_workspace_form_link_auth_requirement_disabled.py, rules/asana_rules/asana_workspace_form_link_auth_requirement_disabled.yml, rules/asana_rules/asana_workspace_guest_invite_permissions_anyone.py, rules/asana_rules/asana_workspace_guest_invite_permissions_anyone.yml
rules/asana_rules/asana_team_privacy_public.py
rules/asana_rules/asana_workspace_default_session_duration_never.py
rules/asana_rules/asana_workspace_form_link_auth_requirement_disabled.py
rules/asana_rules/asana_workspace_guest_invite_permissions_anyone.py
=> Calkim asana rules

queries/aws_queries/cloudtrail_2_minute_count_query.yml, queries/gsuite_queries/GSuite_Many_Docs_Deleted_Query.yml, queries/gsuite_queries/GSuite_Many_Docs_Downloaded_Query.yml
Disable scheduled queries by default.
=> disabled by default

packs/zoom.yml, rules/zoom_operation_rules/zoom_automatic_sign_out_disabled.py, rules/zoom_operation_rules/zoom_automatic_sign_out_disabled.yml
* new zoom rule extends zoom pack
*
=> new rule: alerts when zoom user toggles off org setting to automatically sign out users after a specified period of time

packs/zoom.yml, rules/zoom_operation_rules/zoom_sign_in_method_modified.py, rules/zoom_operation_rules/zoom_sign_in_method_modified.yml
* new detection that extends the zoom pack
*
=> new detection: zoom rule to alert when user modifies an organization's sign in methods

policies/aws_cloudtrail_policies/aws_cloudtrail_enabled.py, policies/aws_cloudtrail_policies/aws_cloudtrail_enabled.yml
Modify cloudtrail enabled policy to support advanced selectors
=> modify cloudtrail policy for advanced selectors

lookup_tables/ipinfo/ipinfo_asn.yml, lookup_tables/ipinfo/ipinfo_asn_datalake.yml, lookup_tables/ipinfo/ipinfo_location.yml, lookup_tables/ipinfo/ipinfo_location_datalake.yml
Change the refresh frequency for IPInfo to once per day. They are only updated daily, and the load on the Snowflake cluster is causing problems. 
https://app.asana.com/0/1202406151216690/1203922345039254/f
=> Change IPInfo refresh frequency to daily

rules/asana_rules/asana_workspace_email_domain_added.py, rules/asana_rules/asana_workspace_email_domain_added.yml, rules/aws_cloudtrail_rules/abnormally_high_event_volume.py, rules/aws_cloudtrail_rules/aws_software_discovery.py
Asana email domain added detection
also some fmt fixes on other detections from `make fmt`
=> asana workspace email domain detection

packs/zoom.yml, rules/zoom_operation_rules/zoom_two_factor_authentication_disabled.py, rules/zoom_operation_rules/zoom_two_factor_authentication_disabled.yml
* new detection that extends the zoom pack
*
=> new detection: alerts when a zoom user disables an org's setting to sign in with 2fa

packs/asana.yml
=> asana pack

packs/asana.yml, rules/asana_rules/asana_service_account_created.py, rules/asana_rules/asana_service_account_created.yml
* new detection that extends the asana pack
=> New detection: alert when a new asana service account is created

packs/asana.yml, rules/asana_rules/asana_workspace_password_requirements_simple.py, rules/asana_rules/asana_workspace_password_requirements_simple.yml
* new detection that extends the asana pack
*
=> new detection: alerts when an asana user changes an organization's password requirements to 'simple'

packs/asana.yml, rules/asana_rules/asana_workspace_saml_optional.py, rules/asana_rules/asana_workspace_saml_optional.yml
* new detection that extends the asana pack
=> New detection: alert when an asana user makes saml optional for an organization

packs/asana.yml, rules/asana_rules/asana_workspace_require_app_approvals_disabled.py, rules/asana_rules/asana_workspace_require_app_approvals_disabled.yml
* new detection that extends the asana pack
=> New detection: alerts when asana user disables app approval requirements for an organization

policies/aws_cloudtrail_policies/aws_cloudtrail_enabled.py, policies/aws_cloudtrail_policies/aws_cloudtrail_enabled.yml
Bugfix for cloudtrial enabled policy.
Null values are present but not shown so .get() returned None.
=> cloudtrail enabled bugfix

packs/zoom.yml, rules/zoom_operation_rules/zoom_sign_in_requirements_changed.py, rules/zoom_operation_rules/zoom_sign_in_requirements_changed.yml
* new detection that extends the zoom pack 
*
=> new detection: alert when a zoom user changes an organization's sign in requirements

rules/okta_rules/okta_threatinsight_security_threat_detected.py, rules/okta_rules/okta_threatinsight_security_threat_detected.yml
* drop severity to "INFO" if outcome is "DENY"
* ![Screenshot 2023-03-13 at 1 37 53 PM](https://user-images.githubusercontent.com/117778222/224817632-e04936ae-8490-43e3-95e2-ef31e6c30295.png)
=> adding additional logic to drop alert severity to low if outcome is DENY

packs/dropbox.yml
* Crafting dropbox pack so we can reference detection content and load rules for our customers 
=> Creating Dropbox Pack to reference new and existing detection content

queries/aws_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device_FDREvent.yml, queries/crowdstrike_queries/AWS_Authentication_from_CrowdStrike_Unmanaged_Device.yml, queries/crowdstrike_queries/CrowdStrike_Large_Zip_Creation_FDREvent.yml, queries/crowdstrike_queries/MacOS_Browser_Credential_Access_FDREvent.yml, queries/crowdstrike_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device.yml, queries/crowdstrike_queries/onepass_login_from_crowdstrike_unmanaged_device.yml, queries/gsuite_queries/GSuite_Many_Docs_Deleted_Query.yml, queries/gsuite_queries/GSuite_Many_Docs_Downloaded_Query.yml, queries/okta_queries/Okta_Login_From_CrowdStrike_Unmanaged_Device_FDREvent.yml, queries/onepassword_queries/onepass_login_from_crowdstrike_unmanaged_device_FDREvent.yml
(https://app.asana.com/0/1200908948600035/1204323874535604/f)
* changing query logic to use fully qualified table names instead of table abbreviations 
* passing lint and test
=> Query Fix: Making sure queries use fqtn 

packs/gcp_audit.yml, rules/gcp_audit_rules/gcp_cloud_storage_buckets_modified_or_deleted.py, rules/gcp_audit_rules/gcp_cloud_storage_buckets_modified_or_deleted.yml
gcp cloud storage buckets modified or deleted
=> gcp cloud storage buckets modified or deleted

queries/snowflake_queries/snowflake_public_role_grant_query.yml, queries/snowflake_queries/snowflake_user_created_query.yml, queries/snowflake_queries/snowflake_user_enabled_query.yml
As part of the snowflake initiative, we are working to update current snowflake queries in an effort to strengthen query logic and ensure compatibility with our backend and customer environments, as well as add functionality in areas where logic has yet to cover. This PR is the third to be put out for this initiative, and focuses on fixing time statements for the remaining existing queries.
* Fixed:
queries/snowflake_queries/snowflake_public_role_grant_query.yml
queries/snowflake_queries/snowflake_user_created_query.yml
queries/snowflake_queries/snowflake_user_enabled_query.yml
* The queries have been run both in king of spades and within our backend snowflake instance and have been confirmed to return the same results. (additional evidence of this may be provided if requested)
=> Snowflake queries minor fixes

rules/atlassian_rules/user_logged_in_as_user.yml
* Updates the Atlassian impersonation detection display name to match the clarity of its description
=> Atlassian impersonation detection display name

queries/snowflake_queries/snowflake_external_shares.py, queries/snowflake_queries/snowflake_external_shares.yml, queries/snowflake_queries/snowflake_external_shares_query.yml, queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success.py, queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success.yml, queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success_query.yml
As part of the snowflake initiative, we are working to create two new snowflake queries in an effort to bring new customer visibility to their snowflake environments. This PR is the fourth to be put out for this initiative, and adds two new queries to our repository. 
New:
* queries/snowflake_queries/snowflake_external_shares_query.yml
* queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success_query.yml
* The queries have been run both in king of spades and within our backend snowflake instance and have been confirmed to return the same results. (additional evidence of this may be provided if requested)
Test Cases:
=> New Snowflake Queries

queries/snowflake_queries/snowflake_account_admin_assigned_query.yml, queries/snowflake_queries/snowflake_brute_force_ip_query.yml, queries/snowflake_queries/snowflake_brute_force_username_query.yml, queries/snowflake_queries/snowflake_external_shares_query.yml, queries/snowflake_queries/snowflake_key_user_password_login_query.yml, queries/snowflake_queries/snowflake_login_without_mfa_query.yml, queries/snowflake_queries/snowflake_multiple_failed_logins_followed_by_success_query.yml, queries/snowflake_queries/snowflake_public_role_grant_query.yml, queries/snowflake_queries/snowflake_user_created_query.yml, queries/snowflake_queries/snowflake_user_enabled_query.yml
* Simple scheduling changes to ensure queries run only once in a 24 hour window and have reasonable timeouts with respect to theoretically shared resources
=> Snowflake Scheduled Queries

Pipfile, Pipfile.lock
Bump `panther_analysis_tool` to the latest version.
* Upgrade `panther_analysis_tool` from version `0.19.8` to version `0.20.1`
* `make ci`
=> pat version update

.github/workflows/asana.yml
internal github asana action version bump, not much exciting here
* bomp
=> chore: update github asana action

packs/snyk.yml, rules/snyk_rules/snyk_misc_settings.py, rules/snyk_rules/snyk_misc_settings.yml, rules/snyk_rules/snyk_org_settings.py, rules/snyk_rules/snyk_org_settings.yml, rules/snyk_rules/snyk_project_settings.py, rules/snyk_rules/snyk_project_settings.yml, rules/snyk_rules/snyk_role_change.py, rules/snyk_rules/snyk_user_mgmt.py, rules/snyk_rules/snyk_user_mgmt.yml
Here's the last round of Snyk detections, and an extension of the Snyk pack to include them.
* 
```shell
Snyk.Misc.Settings
[PASS] Snyk Feature Flags changed
[PASS] [title] Snyk: [Group] Setting [Feature_Flags.Edit] performed by [05555555-3333-4ddd-8ccc-755555555555]
[PASS] [dedup] 05555555-3333-4ddd-8ccc-75555555555521111111-a222-4eee-8ddd-a999999999998fffffff-1555-4444-b000-b55555555555group.feature_flags.edit
[PASS] [alertContext] {"actor": "05555555-3333-4ddd-8ccc-755555555555", "action": "group.feature_flags.edit", "orgId": "21111111-a222-4eee-8ddd-a99999999999", "groupId": "8fffffff-1555-4444-b000-b55555555555"}
[PASS] Snyk User Invite Revoke
Snyk.Org.Settings
[PASS] placeholder
[PASS] [title] Snyk: [Org] Setting …
```
=> feat: More Snyk Detections

data_models/crowdstrike_fdr_data_model.py, data_models/crowdstrike_fdr_data_model.yml, global_helpers/panther_base_helpers.py, rules/crowdstrike_rules/crowdstrike_connection_to_embargoed_country.py, rules/crowdstrike_rules/crowdstrike_connection_to_embargoed_country.yml
Added global helper for common Crowdstrike network alert context
Added Crowdstrike UDM
Added Crowdstrike embargoed country detection
=> Crowdstrike embargoed

packs/crowdstrike.yml, rules/crowdstrike_rules/crowdstrike_credential_dumping_tool.py, rules/crowdstrike_rules/crowdstrike_credential_dumping_tool.yml, rules/crowdstrike_rules/crowdstrike_cryptomining_tools.py, rules/crowdstrike_rules/crowdstrike_cryptomining_tools.yml, rules/crowdstrike_rules/crowdstrike_systemlog_tampering.py, rules/crowdstrike_rules/crowdstrike_systemlog_tampering.yml, rules/crowdstrike_rules/crowdstrike_unusual_parent_child_processes.py, rules/crowdstrike_rules/crowdstrike_unusual_parent_child_processes.yml
unusual parent child detection
system log tampering
credential dumping tool
cryptomining detection
=> crowdstrike pt 1

packs/salesforce.yml, rules/salesforce_rules/salesforce_admin_login_as_user.py, rules/salesforce_rules/salesforce_admin_login_as_user.yml
* Salesforce loginas detection: Alerts when an admin logs in as another user 
* new detection that extends new salesforce pack
*
=> Salesforce loginas detection: Alerts when an admin logs in as another user 

packs/tines.yml, rules/tines_rules/tines_custom_ca.py, rules/tines_rules/tines_custom_ca.yml, rules/tines_rules/tines_tenant_authtoken.py, rules/tines_rules/tines_tenant_authtoken.yml
Two additional `Credential Security` Tines detections
1. Detects the creation of Tenant scoped API Tokens
2. Detects changes to the Custom Certificate Authority settings for your Tines tenant. 
```text
Tines.Custom.CertificateAuthority
[PASS] Tines Login
[PASS] Tines Custom CA set
[PASS] [title] Tines: [CustomCertificateAuthoritySet] by [user@company.com]
[PASS] [dedup] 17171_CustomCertificateAuthoritySet
[PASS] [alertContext] {"actor": "user@company.com", "action": "CustomCertificateAuthoritySet", "tenant_id": "8888", "user_email": "user@company.com", "user_id": "17171", "operation_name": "CustomCertificateAuthoritySet", "request_ip": "12.12.12.12"}
Tines.Tenant.AuthToken
[PASS] Tines Login
[PASS] Tines Personal API Token Created …
```
=> feat: Tines detections for API Tokens and CustomCA

Pipfile, Pipfile.lock
Bump `panther_analysis_tool` to the latest version.
* Upgrade `panther_analysis_tool` from version `0.20.1` to version `0.22.1`
* `make ci`
=> bump PAT version to 0.22.1

packs/crowdstrike.yml
Add detections from https://github.com/panther-labs/panther-analysis/pull/745 to the crowdstrike pack
=> add fdr detections to pack

global_helpers/gcp_base_helpers.py
=> gcp_alert_context

packs/crowdstrike.yml
Adds Crowdstrike data model to crowdstrike pack
=> add crowdstrike data model to pack

Pipfile, Pipfile.lock, packs/notion.yml, rules/notion_rules/notion_many_pages_exported.py, rules/notion_rules/notion_many_pages_exported.yml, rules/notion_rules/notion_workspace_exported.py, rules/notion_rules/notion_workspace_exported.yml
* pat version upgrade to support notion log type (pipfile changes)
* two new notion detections 
* a notion pack for those detections 
```
Notion.Workspace.Exported
[PASS] Workspace Exported
[PASS] [title] Notion User [homer.simpson@yourcompany.io] exported a workspace with workspace id [..].
[PASS] [dedup] Notion User [homer.simpson@yourcompany.io] exported a workspace with workspace id [..].
[PASS] [alertContext] {"actor": {"id": "..", "object": "user", "type": "person", "person": {"email": "homer.simpson@yourcompany.io"}}, "action": "workspace.content_exported"}
Path: .
Passed: 1
Failed: 0
Invalid: 0
```
```
Notion.Many.Pages.Exported …
```
=> New: Notion Detections, Pack, Pat Version Upgrade

rules/standard_rules/impossible_travel_login.py, rules/standard_rules/impossible_travel_login.yml
We noticed `Standard.ImpossibleTravel.Login` was alerting when people were using ApplePrivateRelay and when users were using commercial VPN services.
We have added conditionals to modify the severity of the alert to `INFO` if a commercial VPN service or ApplePrivateRelay is detected. 
Here's the updated `alert_context` if VPN or Apple Private Relay is detected 
```javascript
{
"actor_user": "Homer Simpson",
"current": {
"NOTE": "APPLE PRIVATE RELAY AND VPN LOGINS ARE NOT CACHED FOR COMPARISON",
"city": "Los Angeles",
"country": "US",
"is_apple_priv_relay": "True",
"is_vpn": "False",
"lat": "34.05223",
"lng": "-118.24368",
"p_event_time": "2023-05-26T20:18:51",
"postal_code": "90009",
"region": "California",
"region_code": "CA",
"service_name": "Apple Private Relay",
"source_ip": …
```
=> fix: Standard.ImpossibleTravel.Login should not alert on VPN or ApplePrivateRelay

rules/crowdstrike_rules/crowdstrike_connection_to_embargoed_country.yml
Tune embargoed country detection to low.
=> tune embargo country detection to low

rules/tines_rules/tines_actions_disabled_changes.py
=> fix: tines_actions_disabled should use the global filter

packs/github.yml
=> add: github org moderators add rule to pack

queries/aws_queries/anomalous_access_denied_query.yml, queries/aws_queries/anomalous_role_assume_query.yml, queries/aws_queries/anomalous_vpc_port_activity_query.yml, queries/aws_queries/ec2_crud_activity_by_role_query.yml, queries/aws_queries/ec2_crud_activity_by_useragent_query.yml, queries/aws_queries/vpc_dns_tunneling_query.yml, queries/snowflake_queries/snowflake_key_user_password_login_query.yml
We have a check for the invalid characters `: . , - " ( )` (and spaces) in fields selected by enabled queries because we use them elsewhere. Removed those characters from selected fields in existing disabled queries in panther-analysis for consistency
* Enabled all queries in panther-analysis
* Ensured that bulk uploading them didn't fail due to invalid characters
=> Alias column names with invalid characters

packs/notion.yml, rules/notion_rules/notion_workspace_settings_enforce_saml_sso_config_updated.py, rules/notion_rules/notion_workspace_settings_enforce_saml_sso_config_updated.yml
Detection for SAML SSO configuration changes. 
Fires an `HIGH` severity alert in case the configuration is disabled, otherwise `INFO`
* Adds `notion_workspace_settings_enforce_saml_sso_config_updated.py` `notion_workspace_settings_enforce_saml_sso_config_updated.yaml` and udpates the Notion pack.
```
Notion.SAML.SSO.Configuration.Changed
[PASS] SAML SSO Enabled
[PASS] [title] Notion User [homer.simpson@yourcompany.io] updated settings to enable SAML SSO config for workspace id ..
[PASS] [dedup] Notion User [homer.simpson@yourcompany.io] updated settings to enable SAML SSO config for workspace id ..
[PASS] [alertContext] {"actor": {"id": "..", "object": "user", "type": "person", "person": {"email": "homer.simpson@yourcompany.io"}}, …
```
=> feat: Add detection for Notion SAML SSO configuration change

packs/auth0.yml, rules/auth0_rules/auth0_mfa_factor_setting_enabled.py, rules/auth0_rules/auth0_mfa_factor_setting_enabled.yml
Adding New Detection for Auth0 mfa enabled 
Extends Auth0 pack with a new detection
Updated Tests all green
```
Auth0.MFA.Factor.Setting.Enabled
[PASS] MFA Enabled
[PASS] [title] Auth0 User [user.name@yourcompany.io] enabled mfa factor settings for [/api/v2/risk-assessment/config] in your organization’s tenant [Org Tenant Label].
[PASS] [dedup] Auth0 User [user.name@yourcompany.io] enabled mfa factor settings for [/api/v2/risk-assessment/config] in your organization’s tenant [Org Tenant Label].
[PASS] [alertContext] {"actor": {"email": "user.name@yourcompany.io", "name": "User Name", "user_id": "google-oauth2|105261262156475850461"}, "action": "Update a Multi-factor Authentication Factor"}
[PASS] MFA disabled
```
=> auth0 mfa enabled detection

packs/cloudflare.yml, packs/ipinfo.yml
* cloudflare detections load GreyNoise helpers
*  GreyNoise helpers load LookupTable helpers
* LookupTable helpers load panther_base_helpers
=> fix: cloudflare pack also needed panther_base_helpers for deep_get

rules/auth0_rules/auth0_post_login_action_flow.yml
* fixed misrepresented fields in yaml file 
=> fixing display name and runbook of auth0 rule

packs/tines.yml, rules/tines_rules/tines_story_items_destruction.py, rules/tines_rules/tines_story_items_destruction.yml
https://www.tines.com/api/audit-logs#:~:text=StoryItemsDestruction
* Tines - StoryItemsDestruction rule
```
Tines.Story.Items.Destruction
[PASS] Detection Trigger
[PASS] [title] Tines [StoryItemsDestruction] performed by [user@email.com] on [tines-log-source-name].
[PASS] [dedup] Tines [StoryItemsDestruction] performed by [user@email.com] on [tines-log-source-name].
[PASS] [alertContext] {"actor": "user@email.com", "action": "StoryItemsDestruction", "tenant_id": "1337", "user_email": "user@email.com", "user_id": "7331", "operation_name": "StoryItemsDestruction", "request_ip": "98.224.225.84"}
[PASS] Tines Login
```
=> Tines Rule - Story Items Destruction

Pipfile, Pipfile.lock
Upgrading to newest version of pat in the pipfile 
=> Upgrading to pat 0.23.0

rules/slack_rules/slack_potentially_malicious_file_shared.yml
Description was wrong
[Slack message](https://panther-labs.slack.com/archives/C012SGW857D/p1687965641810719)
* Updates description for slack_potentially_malicious_file_shared
=> Update slack_potentially_malicious_file_shared description

global_helpers/global_filter_tailscale.py, global_helpers/global_helpers_test.py, global_helpers/panther_tailscale_helpers.py, packs/tailscale.yml, rules/tailscale_rules/tailscale_https_disabled.py, rules/tailscale_rules/tailscale_https_disabled.yml, rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.py, rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.yml, rules/tailscale_rules/tailscale_magicdns_disabled.py, rules/tailscale_rules/tailscale_magicdns_disabled.yml
New Tailscale Detections requested for new integration
* added 3 new tailscale detections and tests:
* tailscale_magicdns_disabled
* tailscale_https_disabled
* tailscale_machine_approval_requirements_disabled
* added tailscale pack as well 
```
Tailscale.Magic.DNS.Disabled
[PASS] Magic DNS Disabled
[PASS] [title] Tailscale user [homer.simpson@yourcompany.io] disabled Magic DNS for [yoururl.com] in your organization's tenant.
[PASS] [dedup] Tailscale user [homer.simpson@yourcompany.io] disabled Magic DNS for [yoururl.com] in your organization's tenant.
[PASS] [alertContext] {"actor": {"displayName": "Homer Simpson", "id": "uodc9f3CNTRL", "loginName": "homer.simpson@yourcompany.io", "type": "USER"}, "action": "DISABLE"} …
```
=> New: Tailscale Detections and Pack

global_helpers/global_helpers_test.py, global_helpers/panther_azuresignin_helpers.py, packs/azure_signin.yml, rules/azure_signin_rules/azure_failed_signins.py, rules/azure_signin_rules/azure_failed_signins.yml, rules/azure_signin_rules/azure_legacyauth.py, rules/azure_signin_rules/azure_legacyauth.yml
This establishes a Pack for Azure.SignIn LogType detections and packages two detection for those logs.
1. A High Number of Failed Logins ( 10 ) in a short amount of time ( 10 minutes )
2. Users that authenticate with Legacy authentication protocols ( these users are high-risk as they aren't subject to complex authentication rules ). 
```text
Azure.SignIn.ManyFailedSignIns
[PASS] Failed Sign-In
[PASS] [title] AzureSignIn: Multiple Failed LogIns for Principal [some-service-principal]
[PASS] [dedup] some-service-principal
[PASS] [alertContext] {"tenantId": "a2aa49aa-2c0c-49d2-af87-f402c421df0b", "source_ip": "12.12.12.12", "actor_user": "some-service-principal", "resourceDisplayName": "Azure Storage", "resourceId": "037694de-8c7d-498d-917d-edb650090fa5"}
[PASS] Successful …
```
=> feat: some detections for Azure.SignIn log type

Pipfile, Pipfile.lock
=> Feat: panther_analysis_tool update 0.24.4

Pipfile, Pipfile.lock
=> feat: p_a_t update to 0.25.0

rules/asana_rules/asana_team_privacy_public.yml, rules/asana_rules/asana_workspace_new_admin.yml, rules/asana_rules/asana_workspace_org_export.yml, rules/asana_rules/asana_workspace_require_app_approvals_disabled.yml, rules/github_rules/github_repo_collaborator_change.py, rules/okta_rules/okta_user_mfa_factor_suspend.py, rules/okta_rules/okta_user_mfa_factor_suspend.yml
Small QoL and correctness fixes.
* Changing the Okta suspend factor to be more accurate. Before, it appeared as if Okta had detected a suspicious alert, but it was just a disabled second factor.
* Removing unnecessary quotes.
* Local unit tests
=> Small fixes to Asana, GitHub, and Okta rule

.gitignore
`make vscode-config` is adveritsed in the README.md but the generated files are not ignored
* Add files to gitignore
* No tests
=> Add .vscode gen files to .gitignore

policies/aws_iam_policies/aws_iam_role_restricts_usage.yml, rules/github_rules/github_user_role_updated.yml
Duplicate test names can potentially cause issues
* Removes duplicated test
* Updates test name to be more accurate
=> removes duplicated test and updates a test name to be more accurate

.gitignore
We advise customers to add sensitive information to this file. It should not be committed.
=> Add .panther_settings.yml to .gitignore

rules/standard_rules/impossible_travel_login.py
First pass of tuning noisy impossible travel rule.  Further iterations to follow https://www.notion.so/pantherlabs/Impossible-Travel-bff7c493e9314c6283be945491603c18?pvs=4
fixed a bug where previous logins were cached
even when a VPN or private relay was used
also extended private relays to Google
* PAT tests pass
=> fixed caching bug

rules/panther_audit_rules/panther_user_modified.py, rules/panther_audit_rules/panther_user_modified.yml
Users modified by system account logs have slightly different format which breaks the title
* Added logic for user modified by system in title function
* Added test case for user modified by system
* PAT tests pass
=> added test case for user modified by System

rules/okta_rules/okta_new_behavior_accessing_admin_console.py, rules/okta_rules/okta_org2org_creation_modification.py, rules/okta_rules/okta_password_extraction_via_scim.py
* added default strings to deep_walks where lists are expected
=> added default strings to deep_walks

.gitattributes
=> fix path to CODEOWNERS

.github/workflows/sync-from-upstream.yml
=> removing `shallow_since`

lookup_tables/greynoise/basic/riot_basic.yml
I missed 1 file in #930, this fixes that.
Fix zeek mappings for greynoise riot basic lut
=> Fix zeek mappings for greynoise riot basic lut

README.md
Updates license reference in README.
=> Update License in README

.github/workflows/sync-from-upstream.yml
I think this will hit if there are no new commits
=> Adds a check for messages in the response

lookup_tables/greynoise/basic/riot_basic.yml
missing a . in the selectors. causing uploads to fail for this file
=> fix selector syntax

rules/azure_signin_rules/azure_failed_signins.yml, rules/azure_signin_rules/azure_failed_signins_deprecated.yml, rules/azure_signin_rules/azure_legacyauth.yml, rules/azure_signin_rules/azure_legacyauth_deprecated.yml, rules/azure_signin_rules/azure_risklevel_passthrough.yml, rules/azure_signin_rules/azure_risklevel_passthrough_deprecated.yml
These deprecated files were causing issues on upload, removing them since they are deprecated anyway.
=> remove deprecated azure.signin related detections

packs/gsuite_reports.yml
Updates GSuite pack with all GSuite.Reports and GSuite.ActivityEvent rules, data models, and globals
* There were some missing rules, also added new global config helper
* `make test`
=> gsuite pack refresh

rules/microsoft_rules/microsoft_graph_passthrough.yml
* Moved URL from Description to Reference (microsoft_rules)
=> Moved URL from Description to Reference (microsoft_rules)

rules/okta_rules/okta_app_refresh_access_token_reuse.yml, rules/okta_rules/okta_threatinsight_security_threat_detected.yml, rules/okta_rules/okta_user_reported_suspicious_activity.yml
* Moved URL from Description to Reference (okta_rules)
=> Moved URL from Description to Reference (okta_rules)

lookup_tables/greynoise/advanced/noise_advanced.yml, lookup_tables/greynoise/advanced/riot_advanced.yml, lookup_tables/greynoise/basic/noise_basic.yml, lookup_tables/greynoise/basic/riot_basic.yml, lookup_tables/ipinfo/ipinfo_asn.yml, lookup_tables/ipinfo/ipinfo_asn_datalake.yml, lookup_tables/ipinfo/ipinfo_location.yml, lookup_tables/ipinfo/ipinfo_location_datalake.yml, lookup_tables/ipinfo/ipinfo_privacy.yml, lookup_tables/ipinfo/ipinfo_privacy_datalake.yml, lookup_tables/tor/tor_exit_nodes.yml
This change is intended to:
* set the same list of log sources in all lookup tables (to enrich each log containing ip with all available enrichments)
* add new log sources to lookup tables
* Created the full list of log sources that are used in lookup tables and used this list in all lookup tables
* Added new log sources
=> Update lookup tables with new log sources

test_scenarios/send_data.py
This PR allows executing `send_data` util without typing `python`. `python send_data.py ...` -> `./send_data.py ...`
=> Added shebang line to test_scenarios tool

rules/azure_signin_rules/azure_failed_signins.py, rules/azure_signin_rules/azure_legacyauth.py, rules/azure_signin_rules/azure_risklevel_passthrough.py, rules/crowdstrike_rules/crowdstrike_detection_passthrough.py, rules/crowdstrike_rules/crowdstrike_dns_request.py, rules/duo_rules/duo_admin_create_admin.py, rules/duo_rules/duo_admin_new_admin_api_app_integration.py, rules/duo_rules/duo_admin_sso_saml_requirement_disabled.py, rules/duo_rules/duo_admin_user_mfa_bypass_enabled.py, rules/gsuite_reports_rules/gsuite_drive_external_share.py, rules/onelogin_rules/onelogin_active_login_activity.py, rules/onelogin_rules/onelogin_high_risk_login.py, rules/tailscale_rules/tailscale_https_disabled.py, rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.py, rules/tailscale_rules/tailscale_magicdns_disabled.py
After switching to Black formatter, there were some Python files that were slightly changes after running `make fmt`
=> Format Detections

rules/aws_eks_rules/source_ip_multiple_403.yml, rules/aws_eks_rules/system_namespace_public_ip.yml
=> Add references to rules (aws_eks_rules)

rules/aws_vpc_flow_rules/aws_dns_crypto_domain.yml, rules/aws_vpc_flow_rules/aws_vpc_inbound_traffic_port_allowlist.yml, rules/aws_vpc_flow_rules/aws_vpc_inbound_traffic_port_blocklist.yml, rules/aws_vpc_flow_rules/aws_vpc_unapproved_outbound_dns.yml
=> Add references to rules (aws_vpc_flow_rules)

rules/azure_signin_rules/azure_failed_signins.yml
=> Add references to rules (azure_rules)

rules/cloudflare_rules/cloudflare_firewall_ddos.yml, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked.yml, rules/cloudflare_rules/cloudflare_firewall_high_volume_events_blocked_greynoise.yml, rules/cloudflare_rules/cloudflare_firewall_suspicious_event_greynoise.yml, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.yml, rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume_greynoise.yml
=> Add references to rules (cloudflare_rules)

rules/dropbox_rules/dropbox_admin_sign_in_as_session.yml, rules/dropbox_rules/dropbox_external_share.yml, rules/dropbox_rules/dropbox_linked_team_application_added.yml, rules/dropbox_rules/dropbox_many_deletes.yml, rules/dropbox_rules/dropbox_many_downloads.yml, rules/dropbox_rules/dropbox_ownership_transfer.yml, rules/dropbox_rules/dropbox_user_disabled_2fa.yml
=> Add references to rules (dropbox_rules)

rules/duo_rules/duo_admin_bypass_code_created.yml, rules/duo_rules/duo_admin_create_admin.yml, rules/duo_rules/duo_admin_mfa_restrictions_updated.yml, rules/duo_rules/duo_admin_new_admin_api_app_integration.yml, rules/duo_rules/duo_admin_policy_updated.yml, rules/duo_rules/duo_admin_sso_saml_requirement_disabled.yml, rules/duo_rules/duo_admin_user_mfa_bypass_enabled.yml
=> Add references to rules (duo_rules)

rules/gcp_http_lb_rules/gcp_access_attempts_violating_iap_access_controls.yml
=> Add references to rules (gcp_http_lb_rules)

rules/gcp_k8s_rules/gcp_k8s_exec_into_pod.yml
=> Add references to rules (gcp_k8s_rules)

rules/github_rules/github_action_failed.yml, rules/github_rules/github_advanced_security_change.yml, rules/github_rules/github_branch_policy_override.yml, rules/github_rules/github_branch_protection_disabled.yml, rules/github_rules/github_org_auth_modified.yml, rules/github_rules/github_org_ip_allowlist.yml, rules/github_rules/github_org_moderators_add.yml, rules/github_rules/github_org_modified.yml, rules/github_rules/github_public_repository_created.yml, rules/github_rules/github_repo_collaborator_change.yml, rules/github_rules/github_repo_created.yml, rules/github_rules/github_repo_hook_modified.yml, rules/github_rules/github_repo_initial_access.yml, rules/github_rules/github_repo_visibility_change.yml, rules/github_rules/github_secret_scanning_alert_created.yml, rules/github_rules/github_team_modified.yml, rules/github_rules/github_user_access_key_created.yml, rules/github_rules/github_user_role_updated.yml
=> Add references to rules (github_rules)

rules/gsuite_activityevent_rules/google_workspace_admin_custom_role.yml, rules/gsuite_activityevent_rules/google_workspace_advanced_protection_program.yml, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_allowlist.yml, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_new_domain_application.yml, rules/gsuite_activityevent_rules/google_workspace_apps_new_mobile_app_installed.yml, rules/gsuite_activityevent_rules/gsuite_drive_many_docs_deleted.yml, rules/gsuite_activityevent_rules/gsuite_drive_many_docs_downloaded.yml
=> Add references to rules (gsuite_activityevent_rules)

rules/gsuite_reports_rules/gsuite_drive_external_share.yml
=> Add references to rules (gsuite_reports_rules)

rules/indicator_creation_rules/new_aws_account_logging.yml, rules/indicator_creation_rules/new_user_account_logging.yml
=> Add references to rules (indicator_creation_rules)

rules/microsoft_rules/microsoft365_brute_force_login_by_user.yml, rules/microsoft_rules/microsoft365_external_sharing.yml, rules/microsoft_rules/microsoft365_mfa_disabled.yml, rules/microsoft_rules/microsoft_exchange_external_forwarding.yml
=> Add references to rules (microsoft_rules)

rules/mongodb_rules/mongodb_atlas_api_key_created.yml, rules/mongodb_rules/mongodb_external_user_invited.yml
=> Add references to rules (mongodb_rules)

rules/netskope_rules/netskope_admin_logged_out.yml, rules/netskope_rules/netskope_admin_user_change.yml, rules/netskope_rules/netskope_many_deletes.yml, rules/netskope_rules/netskope_personnel_action.yml, rules/netskope_rules/netskope_unauthorized_api_calls.yml
=> Add references to rules (netskope_rules)

rules/onelogin_rules/onelogin_admin_role_assigned.yml, rules/onelogin_rules/onelogin_unusual_login.yml
=> Add references to rules (onelogin_rules)

rules/panther_audit_rules/panther_detection_deleted.yml, rules/panther_audit_rules/panther_saml_modified.yml, rules/panther_audit_rules/panther_sensitive_role_created.yml, rules/panther_audit_rules/panther_user_modified.yml
=> Add references to rules (panther_audit_rules)

rules/salesforce_rules/salesforce_admin_login_as_user.yml
=> Add references to rules (salesforce_rules)

rules/sentinelone_rules/sentinelone_alert_passthrough.yml, rules/sentinelone_rules/sentinelone_threats.yml
=> Add references to rules (sentinelone_rules)

rules/snyk_rules/snyk_misc_settings.yml, rules/snyk_rules/snyk_org_settings.yml, rules/snyk_rules/snyk_project_settings.yml
=> Add references to rules (snyk_rules)

rules/tailscale_rules/tailscale_https_disabled.yml, rules/tailscale_rules/tailscale_machine_approval_requirements_disabled.yml, rules/tailscale_rules/tailscale_magicdns_disabled.yml
=> Add references to rules (tailscale_rules)

rules/osquery_rules/osquery_mac_enable_auto_update.yml, rules/osquery_rules/osquery_mac_unwanted_chrome_extensions.yml, rules/osquery_rules/osquery_ossec.yml, rules/osquery_rules/osquery_outdated.py, rules/osquery_rules/osquery_outdated.yml, rules/osquery_rules/osquery_outdated_macos.yml, rules/osquery_rules/osquery_ssh_listener.yml
=> Add references to rules (osquery_rules)

rules/standard_rules/admin_assigned.yml, rules/standard_rules/brute_force_by_ip.yml, rules/standard_rules/impossible_travel_login.yml, rules/standard_rules/malicious_sso_dns_lookup.yml, rules/standard_rules/mfa_disabled.yml, rules/standard_rules/standard_dns_base64.yml, rules/standard_rules/unusual_login_deprecated.yml
=> Add references to rules (standard_rules)

rules/zendesk_rules/zendesk_mobile_app_access.yml, rules/zendesk_rules/zendesk_new_api_token.yml, rules/zendesk_rules/zendesk_new_owner.yml, rules/zendesk_rules/zendesk_sensitive_data_redaction.yml, rules/zendesk_rules/zendesk_user_assumption.yml, rules/zendesk_rules/zendesk_user_role.yml, rules/zendesk_rules/zendesk_user_suspension.yml
=> Add references to rules (zendesk_rules)

rules/aws_cloudtrail_rules/aws_cloudtrail_password_policy_discovery.yml
=> Add references to rules (aws_cloudtrail_rules)

.github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/upload.yml, .github/workflows/validate.yml
Syncing changes from our new staging repository.
* Adds validation/upload Workflows that will only run if the correct secrets are specified
* Breaks out the lint and test Workflow into their own Workflows
* New Checks pass as expected
=> Sync changes from staging repository

rules/aws_cloudtrail_rules/aws_cloudtrail_created.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_stopped.yml, rules/aws_cloudtrail_rules/aws_iam_user_recon_denied.yml, rules/aws_cloudtrail_rules/aws_s3_bucket_deleted.yml
=> [sync] Update rules' references (aws_cloudtrail) (#5)

rules/onepassword_rules/onepassword_unusual_client.yml
=> [sync] Update rules' references (onepassword) (#6)

rules/onelogin_rules/onelogin_active_login_activity.yml, rules/onelogin_rules/onelogin_brute_force_by_ip.yml, rules/onelogin_rules/onelogin_brute_force_by_username.yml, rules/onelogin_rules/onelogin_high_risk_failed_login.yml, rules/onelogin_rules/onelogin_high_risk_login.yml, rules/onelogin_rules/onelogin_password_accessed.yml, rules/onelogin_rules/onelogin_password_changed.yml, rules/onelogin_rules/onelogin_remove_authentication_factor.yml, rules/onelogin_rules/onelogin_threshold_accounts_deleted.yml, rules/onelogin_rules/onelogin_threshold_accounts_modified.yml, rules/onelogin_rules/onelogin_unauthorized_access.yml, rules/onelogin_rules/onelogin_user_account_locked.yml, rules/onelogin_rules/onelogin_user_assumed.yml
=> [sync] Update rules' references (onelogin) (#7)

rules/okta_rules/okta_admin_disabled_mfa.yml, rules/okta_rules/okta_brute_force_logins.yml, rules/okta_rules/okta_password_accessed.yml, rules/okta_rules/okta_rate_limits.yml
=> [sync] Update rules' references (okta) (#8)

rules/gsuite_reports_rules/gsuite_drive_external_share.yml, rules/gsuite_reports_rules/gsuite_drive_overly_visible.yml, rules/gsuite_reports_rules/gsuite_drive_visibility_change.yml
=> [sync] Update rules' references (gsuite_reports) (#9)

rules/box_rules/box_access_granted.yml, rules/box_rules/box_brute_force_login.yml, rules/box_rules/box_event_triggered_externally.yml, rules/box_rules/box_item_shared_externally.yml, rules/box_rules/box_malicious_content.yml, rules/box_rules/box_new_login.yml, rules/box_rules/box_policy_violation.yml, rules/box_rules/box_untrusted_device.yml, rules/box_rules/box_user_downloads.yml, rules/box_rules/box_user_permission_updates.yml
=> [sync] Update rules' references (box) (#10)

rules/slack_rules/slack_app_access_expanded.yml, rules/slack_rules/slack_app_added.yml, rules/slack_rules/slack_app_removed.yml, rules/slack_rules/slack_application_dos.yml, rules/slack_rules/slack_dlp_modified.yml, rules/slack_rules/slack_ekm_config_changed.yml, rules/slack_rules/slack_ekm_slackbot_unenrolled.yml, rules/slack_rules/slack_ekm_unenrolled.yml, rules/slack_rules/slack_idp_configuration_change.yml, rules/slack_rules/slack_information_barrier_modified.yml, rules/slack_rules/slack_intune_mdm_disabled.yml, rules/slack_rules/slack_legal_hold_policy_modified.yml, rules/slack_rules/slack_mfa_settings_changed.yml, rules/slack_rules/slack_org_created.yml, rules/slack_rules/slack_org_deleted.yml, rules/slack_rules/slack_passthrough_anomaly.yml, rules/slack_rules/slack_potentially_malicious_file_shared.yml, rules/slack_rules/slack_private_channel_made_public.yml, rules/slack_rules/slack_privilege_changed_to_user.yml, rules/slack_rules/slack_service_owner_transferred.yml, rules/slack_rules/slack_sso_settings_changed.yml, rules/slack_rules/slack_user_privilege_escalation.yml
=> [sync] Update rules' references (slack) (#11)

rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create.yml
Detect privilege escalation in GCP by taking over the deploymentsmanager.deployments.create permission.
TA0004:T1548
Strategy Abstract
This single permission lets you launch new deployments of resources into GCP as the <project number>@cloudservices.gserviceaccount.com Service Account, which, by default, is granted the Editor role on the project. The kicker is that the iam.serviceAccounts.actAs permission (touched on in more detail below) is not required, even though you are essentially acting as that Service Account.
Deployment Manager allows you to specify resources to create and configure in your projects in YAML or Jinja format. It basically can be viewed as an infrastructure-as-code service, similar to CloudFormation in AWS. The resources we specify use the permissions granted to …
=> [sync] Add privilege escalation detection in GCP (#47)

.github/workflows/check-packs.yml, packs/aws.yml, packs/notion.yml
Updated aws and notion packs content to match PAT check-packs
=> [sync] Updated aws and notion packs content (#56)

.vscode/rule_jsonschema.json
The following adds "Detection" as an additional key and move either Filename or Detection as a required key. 
Basic testing in VSCode, however there is no real test coverage added and Detection accepts any array of objects and keys.
=> Update VSCode JSON rule schema

rules/okta_rules/okta_rate_limits.py, rules/okta_rules/okta_rate_limits.yml
High volume alerts were not correctly reflecting the severity of the rate limit events.  Changes should reduce volume and average severity of alerts.
* Enhanced severity function to dynamically match severity level of rate limit events
* Increased dedup period
* make test
=> [sync] updated severity to match eventtype (#71)

rules/aws_cloudtrail_rules/aws_ecr_crud.yml, rules/aws_cloudtrail_rules/aws_ecr_events.py, rules/aws_cloudtrail_rules/aws_ecr_events.yml
High volume of alerts for rules which require configuration to function properly
* Added configuration required tags
* Make test
=> [sync] added configuration required tags (#73)

rules/gcp_audit_rules/gcp_gcs_public.py
Fixes broken bitly link in python comment
* Updated comment with new link
* n/a
=> [sync] updated broken link (#78)

packs/gcp_audit.yml, rules/gcp_audit_rules/gcp_storage_hmac_keys_create.yml
Detect storage.hmacKeys.create method for privilege escalation in GCP
TA0004:T1548
This part of the blog focuses on non-IAM service privilege escalation methods. For example, none of these permissions belong to the “IAM” family, like most of the methods in Part 1, such as iam.serviceAccounts.update. Since we’ve already touched on all the background information, let’s dive into it.
There is a feature of Cloud Storage, “interoperability”, that provides a way for Cloud Storage to interact with storage offerings from other cloud providers, like AWS S3. As part of that, there are HMAC keys that can be created for both Service Accounts and regular users. We can escalate Cloud Storage permissions by creating an HMAC key for a higher-privileged Service Account. 
HMAC keys belonging to your user …
=> [sync] Add GCP.Storage.Hmac.Keys.Create detection rule (#64)

packs/gcp_audit.yml, rules/gcp_k8s_rules/gcp_kubernetes_new_daemonset_deployed.yml
- Adds a new `GCP.K8s.New.Daemonset.Deployed` rule
=> [sync] Add GCP.Kubernetes.New.Daemonset.Deployed rule (#76)

packs/gcp_audit.yml, rules/gcp_audit_rules/gcp_gke_kubernetes_cron_job_created_or_modified.yml, simple_rules/gcp_audit_rules/gcp_gke_kubernetes_cron_job_created_or_modified_simple.yml
Add GCP GKE Kubernetes Cron Job Created Or Modified rule to mirror https://github.com/panther-labs/panther-analysis-internal/blob/main/queries/kubernetes_queries/kubernetes_cron_job_created_or_modified.yml in GCP
=> [sync] Add GCP GKE Kubernetes Cron Job Created Or Modified rule (#68)

simple_rules/gcp_k8s_rules/gcp_k8s_service_type_node_port_deployed_simple.yml
* Added rule to detect when GKE k8s service with NodePort type is created
=> [sync] GCP K8S Service Type NodePort Deployed - rule (#86)

packs/gcp_audit.yml, packs/netskope.yml, rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.py, rules/gcp_k8s_rules/gcp_k8s_pod_create_or_modify_host_path_vol_mount.yml, simple_rules/gcp_audit_rules/gcp_cloudbuild_potential_privilege_escalation_simple.yml, simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_create_simple.yml, simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_update_simple.yml, simple_rules/gcp_audit_rules/gcp_gke_kubernetes_cron_job_created_or_modified_simple.yml, simple_rules/gcp_audit_rules/gcp_iam_roles_update_privilege_escalation_simple.yml, simple_rules/gcp_audit_rules/gcp_iam_service_account_key_create_simple.yml, simple_rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create_simple.yml, simple_rules/gcp_audit_rules/gcp_serviceusage_apikeys_create_privilege_escalation_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_ioc_activity_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_pod_using_host_pid_namespace_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_service_type_node_port_deployed_simple.yml, simple_rules/gcp_k8s_rules/gcp_kubernetes_new_daemonset_deployed_simple.yml, simple_rules/netskope_rules/netskope_admin_logged_out_simple.yml, simple_rules/netskope_rules/netskope_admin_user_change_simple.yml, simple_rules/netskope_rules/netskope_many_deletes_simple.yml, simple_rules/netskope_rules/netskope_personnel_action_simple.yml, simple_rules/netskope_rules/netskope_unauthorized_api_calls_simple.yml
This PR follows our new `release` -> `main` process and will merge all of the PRs to be included in this week's release of `panther-analysis`.
=> Prepare for `3.42.0`

rules/netskope_rules/netskope_admin_logged_out.py, rules/netskope_rules/netskope_admin_logged_out.yml, rules/netskope_rules/netskope_admin_user_change.py, rules/netskope_rules/netskope_admin_user_change.yml, rules/netskope_rules/netskope_many_deletes.py, rules/netskope_rules/netskope_many_deletes.yml, rules/netskope_rules/netskope_personnel_action.py, rules/netskope_rules/netskope_personnel_action.yml, rules/netskope_rules/netskope_unauthorized_api_calls.py, rules/netskope_rules/netskope_unauthorized_api_calls.yml
* Convert Netskope rules from SDYAML to python ([JIRA](https://panther-labs.atlassian.net/browse/TR-231))
=> Convert Netskope rules from SDYAML to python

rules/gcp_audit_rules/gcp_cloudfunctions_functions_create.py, rules/gcp_audit_rules/gcp_cloudfunctions_functions_create.yml, rules/gcp_audit_rules/gcp_cloudfunctions_functions_update.py, rules/gcp_audit_rules/gcp_cloudfunctions_functions_update.yml, rules/gcp_audit_rules/gcp_iam_roles_update_privilege_escalation.py, rules/gcp_audit_rules/gcp_iam_roles_update_privilege_escalation.yml, rules/gcp_audit_rules/gcp_iam_service_account_key_create.py, rules/gcp_audit_rules/gcp_iam_service_account_key_create.yml, rules/gcp_audit_rules/gcp_privilege_escalation_by_deploymants_create.py, rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create.yml, rules/gcp_k8s_rules/gcp_k8s_ioc_activity.py, rules/gcp_k8s_rules/gcp_k8s_ioc_activity.yml, rules/gcp_k8s_rules/gcp_k8s_new_daemonset_deployed.py, rules/gcp_k8s_rules/gcp_k8s_new_daemonset_deployed.yml, rules/gcp_k8s_rules/gcp_k8s_pod_using_host_pid_namespace.py, rules/gcp_k8s_rules/gcp_k8s_pod_using_host_pid_namespace.yml, simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_create_simple.yml, simple_rules/gcp_audit_rules/gcp_cloudfunctions_functions_update_simple.yml, simple_rules/gcp_audit_rules/gcp_iam_roles_update_privilege_escalation_simple.yml, simple_rules/gcp_audit_rules/gcp_iam_service_account_key_create_simple.yml, simple_rules/gcp_audit_rules/gcp_privilege_escalation_by_deployments_create_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_cron_job_created_or_modified_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_ioc_activity_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_new_daemonset_deployed_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network_simple.yml, simple_rules/gcp_k8s_rules/gcp_k8s_pod_using_host_pid_namespace_simple.yml
* Added some descriptive parts to GCP rules ([Jira](https://panther-labs.atlassian.net/browse/THREAT-39))
=> GCP rule consistency check

rules/gcp_k8s_rules/gcp_k8s_cron_job_created_or_modified.py, rules/gcp_k8s_rules/gcp_k8s_cron_job_created_or_modified.yml, rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network.py, rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network.yml
* Converted two k8s rules from SDYAML to python
=> Convert k8s rules from SDYAML to python

rules/gcp_audit_rules/gcp_computeinstances_create_privilege_escalation.py
* fixed `AttributeError` in `GCP.compute.instances.create.Privilege.Escalation` rule ([Jira](https://panther-labs.atlassian.net/browse/THREAT-240))
=> fix - GCP compute.instance.create AttributeError

Pipfile, rules/osquery_rules/osquery_linux_mac_vulnerable_xz_liblzma.yml
Bumps black to address CVE-2024-21503
- CI
=> Bump black

global_helpers/global_helpers_test.py, global_helpers/panther_base_helpers.py, global_helpers/panther_iocs.py, global_helpers/panther_ipinfo_helpers.py, global_helpers/panther_oss_helpers.py, global_helpers/panther_snyk_helpers.py, rules/github_rules/github_secret_scanning_alert_created.py, rules/onepassword_rules/onepassword_lut_sensitive_item_access.py, rules/onepassword_rules/onepassword_unusual_client.py
Formatter was upgraded [here](https://github.com/panther-labs/panther-analysis/pull/1184), need to apply formatting changes.
- make install, make fmt
- make fmt
=> apply make fmt using upgraded black version

packs/mongodb.yml, rules/mongodb_rules/mongodb_external_user_invited_no_config.py, rules/mongodb_rules/mongodb_external_user_invited_no_config.yml
Add MongoDB.External.UserInvited.NoConfig rule
=> Add MongoDB.External.UserInvited.NoConfig rule

rules/notion_rules/notion_login_from_new_location.py, rules/notion_rules/notion_login_from_new_location.yml
- fixed NoneType error in Notion Login From New Location rule ([Jira](https://panther-labs.atlassian.net/browse/THREAT-285))
=> fix - Notion Login From New Location - NoneType error

rules/gcp_audit_rules/gcp_cloudbuild_potential_privilege_escalation.py, rules/gcp_audit_rules/gcp_serviceusage_apikeys_create_privilege_escalation.py
- fixed AttributeError in some GCP rules
=> fix - GCP rules - AttributeError

Pipfile.lock
This PR updates PAT to `0.46.1.`
- Updates PAT to PR `0.46.1`
- `make test`
=> Update PAT to 0.46.1

packs/traildiscover.yml
Adds a pack for the new TrailDiscover LUT
- New pack added
- make test
=> pack for traildiscover LUT

test_scenarios/send_data.py
Fix [CWE-502](https://cwe.mitre.org/data/definitions/502.html) Insecure deserialization
=> Fix Snyk yaml load error

Pipfile.lock, global_helpers/panther_base_helpers.py, packs/traildiscover.yml, test_scenarios/send_data.py
PR to prepare this week's release.
* Aggregates the PRs that will be included in this week's release
* N/A
=> Prepare for `3.51.0`

.github/CODEOWNERS, Pipfile.lock
Adds @panther-labs/threat-research as codeowner.
=> Add threat-research as codeowners

.github/CODEOWNERS, Pipfile.lock
Adds @panther-labs/threat-research as codeowner.
=> Add threat-research as codeowners (#1213)

.github/workflows/check-packs.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/sync-from-upstream.yml, .github/workflows/test.yml, .github/workflows/upload.yml, Pipfile, Pipfile.lock, dependabot.yml, global_helpers/global_helpers_test.py
PR to prepare this week's release.
* Aggregates the PRs that will be included in this week's release
* N/A
=> Prepare for `3.53.0`

packs/push_security.yml, rules/push_security_rules/push_security_app_banner_acknowledged.py, rules/push_security_rules/push_security_mfa_method_changed.py, rules/push_security_rules/push_security_new_app_detected.py, rules/push_security_rules/push_security_new_saas_account_created.py, rules/push_security_rules/push_security_open_security_finding.py, rules/push_security_rules/push_security_phishable_mfa_method.py, rules/push_security_rules/push_security_phishing_attack.py, rules/push_security_rules/push_security_unauthorized_idp_login.py, rules/push_security_rules/push_security_unauthorized_idp_login.yml
Added pack for Push Security rules
- new pack
- event.deep_get syntax
- fmt, lint, test
=> Push Security pack

.github/workflows/lint.yml, .github/workflows/upload.yml
This PR makes two small, aesthetic changes to the `lint.yml` and `upload.yml` Workflows.
- Removes unnecessary ref checkout from `lint.yml`
- Adds `Upload` name to `upload.yml`
N/A
=> Small Workflow tweaks

rules/push_security_rules/push_security_phishing_attack.yml
PushSecurity.AttackDetection has been renamed to PushSecurity.Controls.
- PushSecurity.AttackDetection has been renamed to PushSecurity.Controls.
- make test, pending PAT regex update
=> Push Security schema rename

rules/appomni_rules/appomni_alert_passthrough.py, rules/auth0_rules/auth0_mfa_policy_enabled.py, rules/auth0_rules/auth0_user_invitation_created.py, rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.py, rules/aws_cloudtrail_rules/aws_s3_bucket_deleted.py, rules/aws_cloudtrail_rules/aws_software_discovery.py, rules/gcp_audit_rules/gcp_workforce_pool_created_or_updated.py, rules/gcp_k8s_rules/gcp_k8s_privileged_pod_created.py, rules/gsuite_activityevent_rules/google_workspace_advanced_protection_program.py, rules/gsuite_activityevent_rules/google_workspace_apps_marketplace_allowlist.py, rules/gsuite_reports_rules/gsuite_drive_external_share.py, rules/okta_rules/okta_idp_create_modify.py, rules/okta_rules/okta_org2org_creation_modification.py, rules/panther_audit_rules/panther_detection_deleted.py, rules/standard_rules/brute_force_by_ip.py, rules/standard_rules/impossible_travel_login.py, rules/standard_rules/malicious_sso_dns_lookup.py
pypanther will run all dynamic functions over all unit tests
- fixes unit test errors that were previously skipped by PAT
- 
- make test
=> improve error handling for dynamic functions

.husky/pre-commit
=> Remove .husky directory

rules/aws_guardduty_rules/aws_guardduty_high_sev_findings.yml, rules/aws_guardduty_rules/aws_guardduty_low_sev_findings.yml, rules/aws_guardduty_rules/aws_guardduty_med_sev_findings.yml
Providing additional guidance thru AWS guardduty reference in the runbook.
=> Aws gd ref links

correlation_rules/aws_potentially_compromised_service_role.yml
On the PR I just merged I missed a comment from Doug, wanted to address that here.
- Further increase rate minutes for hefty rule
- None
=> Bump rate minutes more

correlation_rules/aws_potentially_compromised_service_role.yml, correlation_rules/aws_privilege_escalation_via_user_compromise.yml, correlation_rules/aws_user_takeover_via_password_reset.yml, correlation_rules/github_advanced_security_change_not_followed_by_repo_archived.yml, correlation_rules/okta_login_without_push.yml, correlation_rules/potential_compromised_okta_credentials.yml, correlation_rules/secret_exposed_and_not_quarantined.yml, rules/slack_rules/slack_user_privilege_escalation.yml
Pushing a few CR configuration tweaks for performance considerations.
- See included PRs
- `pat test`
=> Releasing performance improvements

rules/aws_cloudtrail_rules/aws_iam_user_key_created.py, rules/crowdstrike_rules/crowdstrike_base64_encoded_args.py, rules/standard_rules/standard_dns_base64.py
pypanther testing revealed additional default value errors
- Added default return values to get and deep_get
- make test
=> added default values to get/deep_get

rules/gcp_k8s_rules/gcp_k8s_cron_job_created_or_modified.yml
As an improvement of this PR: https://github.com/panther-labs/panther-analysis/pull/1316
Changed T1053.003 to TA0003:T1053.003
=> Update again gcp_k8s_cron_job_created_or_modified.yml

rules/snyk_rules/snyk_misc_settings.py, rules/snyk_rules/snyk_org_settings.py, rules/snyk_rules/snyk_ou_change.py, rules/snyk_rules/snyk_project_settings.py, rules/snyk_rules/snyk_project_settings.yml, rules/snyk_rules/snyk_role_change.py, rules/snyk_rules/snyk_svcacct_change.py, rules/snyk_rules/snyk_system_externalaccess.py, rules/snyk_rules/snyk_system_policysetting.py, rules/snyk_rules/snyk_system_sso.py, rules/snyk_rules/snyk_user_mgmt.py, test_scenarios/jsonl_to_testfile.py
Tuning improvements for Snyk ruleset.
- Uses built-in event.deep_get function
- Snyk Project Settings - don't alert on org.project.edit since these logs are not actionable
- Snyk Project Settings - don' alert on "No new Code Analysis issues found"
- new tests
- pat test
=> Tuning Snyk Rules

packs/aws.yml, packs/github.yml, packs/gsuite_reports.yml, packs/kubernetes.yml, packs/okta.yml, packs/onepassword.yml, packs/snowflake.yml
Some of our packs were missing items, mainly subrules that are used in correlation rules, and queries attached to scheduled rules. This PR should fix any that weren't present before!
[The issue was originally raised here.](https://panther-labs.slack.com/archives/C0719AH18SV/p1725635583099309?thread_ts=1725633540.527299&cid=C0719AH18SV)
- Added missing items to pack manifests
- I updated my pack checking script to look for queries and correlation sub-rules. I spot checked about half the results and confirmed they are correct.
=> Add Missing Pack Items

CONTRIBUTING.md, STYLE_GUIDE.md
Refreshes contribution guidelines in preparation for panther-analysis seasonal newsletter.
- Refresh CONTRIBUTING.md
- Add STYLE_GUIDE.md
=> Refreshing Contributing Guidelines

.github/workflows/upload.yml
Run pat validate and upload on PRs to main, for additional pre-release testing.
- Run upload workflow on PR instead of push to main
=> validate and upload on PRs

.github/workflows/check-packs.yml, .github/workflows/test.yml
Updates pat test GHA to use Panther API for Correlation Rule testing
=> test with api

global_helpers/default_test.py, policies/aws_cloudformation_policies/aws_cloudformation_stack_drifted.yml, policies/aws_cloudformation_policies/aws_cloudformation_stack_uses_iam_role.yml, policies/aws_cloudformation_policies/aws_cloudformation_termination_protection.yml, policies/aws_cloudwatch_policies/aws_cloudwatch_loggroup_data_retention.yml, policies/aws_cloudwatch_policies/aws_cloudwatch_loggroup_encrypted.yml, policies/aws_cloudwatch_policies/aws_cloudwatch_loggroup_sensitive_encrypted.yml, policies/aws_ec2_policies/aws_ec2_volume_encryption.yml, policies/aws_ec2_policies/aws_ec2_volume_snapshot_encrypted.yml, policies/aws_guardduty_policies/aws_guardduty_enabled.py, policies/aws_vpc_policies/aws_network_acl_restricted_ssh.yml, policies/aws_vpc_policies/aws_network_acl_restricts_insecure_protocols.yml
Fixes https://github.com/panther-labs/panther-analysis/issues/439
- Change `AccountID` to `AccountId` in AWS test logs
- make test
=> Fix issue 439: AccountId case

rules/zendesk_rules/zendesk_user_suspension.py
Fixes https://github.com/panther-labs/panther-analysis/issues/468
- Return DEFAULT severity
=> Fix issue 468: Zendesk severity override

rules/sublime_rules/sublime_mailboxes_deactivated.yml, rules/sublime_rules/sublime_message_flagged.yml, rules/sublime_rules/sublime_message_source_deleted_or_deactivated.yml, rules/sublime_rules/sublime_rules_deleted_or_deactivated.yml
Formats Sublime YAML files using prettier.
=> Format Sublime YAML files

CONTRIBUTING.md
Commit f64ef48102952382e386d6498eeebd809abd3699 moved the location of `STYLE_GUIDE.md`.
This PR adjusts sources to changes.
=> Update style guide reference

.github/workflows/pre-release-upload.yml, .github/workflows/test.yml
Continuing to iterate on our GHA test suite.
- Don't run authenticated tasks (test, validate) on PRs from external forks
- Add unauthenticated test step for PRs from external forks
- Add pre-release upload to GA Panther version
=> Gha improvements

packs/aws.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_event_selectors_disabled.py, rules/aws_cloudtrail_rules/aws_cloudtrail_event_selectors_disabled.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_short_lifecycle.py, rules/aws_cloudtrail_rules/aws_cloudtrail_short_lifecycle.yml, rules/aws_cloudtrail_rules/aws_dns_logs_deleted.py, rules/aws_cloudtrail_rules/aws_dns_logs_deleted.yml, rules/aws_cloudtrail_rules/aws_vpc_flow_logs_deleted.py, rules/aws_cloudtrail_rules/aws_vpc_flow_logs_deleted.yml
Here's some rules for modifying cloudtrail logs. We can test the with Stratus.
- added new rules
- the new rules have tests!
=> THREAT-420: Stratus AWS Logging Detections

global_helpers/panther_base_helpers.py
Refactors PantherFlow datetime -> time.parse_timestamp in advance of upcoming changes.
- datetime -> time.parse_timestamp
- tested in latest PantherFlow
=> datetime -> time.parse_timestamp

.github/workflows/check-deprecated.yml, .github/workflows/check-mitre.yml, .github/workflows/check-packs.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/pre-release-upload.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/upload.yml, .github/workflows/validate.yml
Removes step-security from GHAs
=> remove step security

.github/workflows/check-deprecated.yml, .github/workflows/check-mitre.yml, .github/workflows/check-packs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Enables the lint and test actions to run in the merge queue.
=> Run lint and test in merge queue

rules/crowdstrike_rules/event_stream_rules/crowdstrike_detection_summary.py
Customer requested that we add these fields to alert context
Added 4 new fields
Ran unit tests and confirmed alert context has desired fields
=> Crowdstrike.EppDetectionSummary: Added extra fields to alert context

Pipfile, Pipfile.lock
- Updated pat version to 0.56.0
=> Update pat to 0.56.0 version

correlation_rules/wiz_issue_followed_by_ssh.yml, packs/multisource_correlations.yml, rules/aws_vpc_flow_rules/aws_vpc_ssh_allowed_signal.py, rules/aws_vpc_flow_rules/aws_vpc_ssh_allowed_signal.yml
Consider this scenario: A developer accidentally modifies a security group rule, exposing an EC2 instance to the internet. Within minutes, attackers begin SSH brute force attempts against the newly exposed host. Here's how Panther's detection-as-code approach combines Wiz asset exposure findings with VPC Flow Logs to detect potential compromises:
This detection identifies when a Wiz finding about a newly internet-exposed EC2 instance is followed by successful SSH connections to that same instance. The [correlation](https://panther.com/blog/unraveling-siem-correlation-techniques/) leverages Wiz's continuous asset monitoring to detect security group changes and combines it with real-time VPC Flow Log analysis.
- unit tests
=> Wiz Issue Followed by SSH

rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_multiregion.py, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_multiregion.yml
Unit tests failed after conversion to pypanther.
- Added unit test mock
- Fixed filename
- pat test
=> Fix Unit Tests for Secrets Manager Multi-Region

.github/workflows/validate.yml
Reverts panther-labs/panther-analysis#1487
See ASK-1454
=> Revert "Validate on PR merge"

rules/snowflake_rules/snowflake_stream_file_downloaded.py, rules/snowflake_rules/snowflake_stream_file_downloaded.yml, rules/snowflake_rules/snowflake_stream_table_copied_into_stage.py, rules/snowflake_rules/snowflake_stream_table_copied_into_stage.yml, rules/snowflake_rules/snowflake_stream_temp_stage_created.py, rules/snowflake_rules/snowflake_stream_temp_stage_created.yml
Signals for Snowflake Data Exfiltration CR were not properly extracting stage name for correlation.
- properly ported regex from scheduled queries
- updated unit tests to more accurately reflect real commands
=> Fix Snowflake data exfiltration signals

Pipfile, Pipfile.lock
PAT v0.57.0 was released this week.
=> Update PAT to v0.57.0

rules/standard_rules/admin_assigned.py
https://github.com/panther-labs/panther-analysis/issues/1535
- Added team name to the title of the detection
=> THREAT-478 Fix standard admin created for github

rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.py, rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.yml
- Tuned `AWS.Modify.Cloud.Compute.Infrastructure` rule
=> THREAT-479 AWS.Modify.Cloud.Compute.Infrastructure tuning

SECURITY.md
Introduces vulnerability reporting.
=> Introduce SECURITY.md

rules/azure_signin_rules/azure_risklevel_passthrough.yml
- Increased dedup period
- Updated reference
=> THREAT-482 Azure Risk passthrough tuning

rules/gcp_audit_rules/gcp_logging_settings_modified.py, rules/gcp_k8s_rules/gcp_k8s_pod_attached_to_node_host_network.py
- tuned dedup in two GCP rules
=> THREAT-481 GCP K8s tuning

correlation_rules/aws_create_admin_iam_user.yml, queries/aws_queries/aws_ssm_multiple_sessions.yml, queries/aws_queries/ec2_discovery_commands.yml, rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml, rules/aws_cloudtrail_rules/aws_backdoor_lambda_function.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_attempt_to_leave_org.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_identity_verifications.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_send_quota.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_ses_sending_enabled.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_list_identities.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_short_lifecycle.yml, rules/aws_cloudtrail_rules/aws_dns_logs_deleted.yml, rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.yml, rules/aws_cloudtrail_rules/aws_ec2_many_passwors_read_attempts.yml, rules/aws_cloudtrail_rules/aws_ec2_multi_instance_connect.yml, rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml, rules/aws_cloudtrail_rules/aws_s3_delete_object.yml, rules/aws_cloudtrail_rules/aws_s3_delete_objects.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_batch.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_catchall.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_multiregion.yml, rules/aws_cloudtrail_rules/aws_ssm_decrypt_ssm_params.yml, rules/aws_cloudtrail_rules/aws_ssm_distributed_command.yml, rules/aws_cloudtrail_rules/aws_vpc_flow_logs_deleted.yml
Adds `Beta` tag to several recently released rules, and converts severity of those rules to Info for further monitoring.
=> Beta rules

correlation_rules/aws_create_admin_iam_user.yml, queries/aws_queries/aws_ssm_multiple_sessions.yml, queries/aws_queries/ec2_discovery_commands.yml, rules/aws_cloudtrail_rules/aws_add_malicious_lambda_extension.yml, rules/aws_cloudtrail_rules/aws_backdoor_lambda_function.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_attempt_to_leave_org.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_identity_verifications.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_send_quota.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_check_ses_sending_enabled.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_ses_list_identities.yml, rules/aws_cloudtrail_rules/aws_cloudtrail_short_lifecycle.yml, rules/aws_cloudtrail_rules/aws_dns_logs_deleted.yml, rules/aws_cloudtrail_rules/aws_ec2_launch_unusual_ec2_instances.yml, rules/aws_cloudtrail_rules/aws_ec2_many_passwors_read_attempts.yml, rules/aws_cloudtrail_rules/aws_ec2_multi_instance_connect.yml, rules/aws_cloudtrail_rules/aws_overwrite_lambda_code.yml, rules/aws_cloudtrail_rules/aws_s3_delete_object.yml, rules/aws_cloudtrail_rules/aws_s3_delete_objects.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_batch.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_catchall.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets_multiregion.yml, rules/aws_cloudtrail_rules/aws_ssm_decrypt_ssm_params.yml, rules/aws_cloudtrail_rules/aws_ssm_distributed_command.yml, rules/aws_cloudtrail_rules/aws_vpc_flow_logs_deleted.yml, rules/cloudflare_rules/cloudflare_firewall_ddos.py, rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.py, rules/gsuite_activityevent_rules/google_workspace_many_docs_downloaded.yml
- fix dedup issues with cloudflare ddos7
- fix typos in google docs downloaded rule
- move several noisy new rules to a "beta" state
=> Patch Release v3.76.0

.github/workflows/airflow-update.yml
Action needed to further automate PA release process
- Added `Airflow Update` workflow
Tested activating action on push. Result: https://github.com/panther-labs/airflow/pull/478
=> THREAT-496 Automate Airflow update process

packs/aws.yml, packs/aws_cis.yml, policies/aws_account_policies/aws_password_policy_complexity_guidelines.py, policies/aws_account_policies/aws_password_policy_complexity_guidelines.yml, policies/aws_dynamodb_policies/aws_dynamodb_table_ttl_enabled.py, policies/aws_dynamodb_policies/aws_dynamodb_table_ttl_enabled.yml, policies/aws_ec2_policies/aws_ami_private.py, policies/aws_ec2_policies/aws_ec2_cde_volume_encrypted.py, policies/aws_guardduty_policies/aws_guardduty_enabled.py, policies/aws_guardduty_policies/aws_guardduty_enabled.yml, policies/aws_iam_policies/aws_iam_role_github_actions_trust.py, policies/aws_iam_policies/aws_iam_role_github_actions_trust.yml, policies/aws_load_balancer_policies/aws_elbv2_load_balancer_has_ssl_policy.py, policies/aws_rds_policies/aws_rds_instance_backup_retention_acceptable.py, policies/aws_redshift_policies/aws_redshift_cluster_snapshot_retention_acceptable.py, policies/aws_s3_policies/aws_s3_bucket_object_lock_configured.py, policies/aws_vpc_policies/aws_network_acl_restricts_inbound_traffic.py, policies/aws_vpc_policies/aws_network_acl_restricts_insecure_protocols.py, policies/aws_vpc_policies/aws_network_acl_restricts_outbound_traffic.py, policies/aws_vpc_policies/aws_only_dmz_security_groups_publicly_accessible.py, policies/aws_vpc_policies/aws_security_group_restricts_access_to_cde.py, policies/aws_vpc_policies/aws_security_group_restricts_inbound_traffic.py, policies/aws_vpc_policies/aws_security_group_restricts_inter_security_group_traffic.py, policies/aws_vpc_policies/aws_security_group_restricts_outbound_traffic.py, policies/aws_vpc_policies/aws_security_group_restricts_traffic_leaving_cde.py, policies/aws_vpc_policies/aws_vpc_default_network_acl_restricts_all_traffic.py, policies/aws_waf_policies/aws_waf_has_xss_predicate.py
Several policies required configuration to be useful, but were not tagged as "Configuration Required" and/or did not include instructions on how to configure them.
[See ASK-1871 for more context.](https://panther-labs.atlassian.net/browse/ASK-1871)
- Adding tags and comments
- N/A
=> THREAT 498: Mark Policies as Configuration Required

rules/cloudflare_rules/cloudflare_httpreq_bot_high_volume.py, rules/snowflake_rules/snowflake_stream_login_without_mfa.yml
Following a review of alert volume, two tuning opportunities were apparent.
- `Snowflake.Stream.LoginWithoutMFA`: Change dedup period from 1 hour to 1 day
- `Cloudflare.HttpRequest.BotHighVolume`: Group alerts by just requested host, not client IP
- Titles raised by unit test still look good
=> THREAT-500: Tuning Adjustments

indexes/alpha-index.md, indexes/detection-coverage.json, indexes/snowflake.md, rules/gsuite_activityevent_rules/gsuite_suspicious_logins.py
Pypanther sync action is failing because of duplicate code
- removed duplicate code
=> Remove duplicate code

rules/crowdstrike_rules/crowdstrike_macos_plutil_usage.py
Because of deduping on the device `aid` sometimes the rule could become noisy
Changed the title/dedup string
=> `Crowdstrike.Macos.Plutil.Usage` tuning

README.md
=> Fix latest changes link in Readme

README.md, indexes/alpha-index.md, indexes/aws.md, indexes/detection-coverage.json, indexes/gworkspace.md, indexes/saas.md, packs/aws.yml, packs/gsuite_reports.yml, rules/aws_bedrockmodelinvocation_rules/aws_bedrockmodelinvocation_abnormaltokenusage.py, rules/aws_bedrockmodelinvocation_rules/aws_bedrockmodelinvocation_abnormaltokenusage.yml, rules/aws_bedrockmodelinvocation_rules/aws_bedrockmodelinvocation_guardrailintervened.py, rules/aws_bedrockmodelinvocation_rules/aws_bedrockmodelinvocation_guardrailintervened.yml, rules/aws_cloudtrail_rules/aws_secretsmanager_retrieve_secrets.py, rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.py, rules/gsuite_activityevent_rules/gsuite_is_suspicious_tag.yml, rules/gsuite_activityevent_rules/gsuite_suspicious_logins.py, rules/gsuite_activityevent_rules/gsuite_suspicious_logins.yml, rules/microsoft_rules/microsoft_exchange_external_forwarding.py, rules/microsoft_rules/microsoft_exchange_external_forwarding.yml
=> Prepare for v3.82.0

global_helpers/panther_config_defaults.py
I could not find these config values and functions used anywhere. 
=> remove unused config settings

lookup_tables/misp/misp_lut.yml, lookup_tables/traildiscover/traildiscover_lut.yml
**Background**
Introducing new combined puller for TrailDiscover and MISP data
**Changes**
- Changed role and path for TrailDiscover LUT from separate to combined
- Added MISP Warning Lists LUT
=> THREAT-352 MISP Warning Lists enrichment

Pipfile, Pipfile.lock, indexes/alpha-index.md, indexes/detection-coverage.json
Bump PAT version after PAT release
=> Bump PAT version

indexes/alpha-index.md, indexes/detection-coverage.json, packs/axonius.yml, rules/axonius_rules/axonius_add_external_user.py, rules/axonius_rules/axonius_add_external_user.yml, rules/axonius_rules/axonius_resetapikey.py, rules/axonius_rules/axonius_resetapikey.yml, rules/axonius_rules/axonius_too_many_failed_logins.py, rules/axonius_rules/axonius_too_many_failed_logins.yml, rules/axonius_rules/axonius_tor_login.py, rules/axonius_rules/axonius_tor_login.yml, rules/axonius_rules/axonius_webhook_created.py, rules/axonius_rules/axonius_webhook_created.yml
Rules and pack for new Axonius integration
=> Axonius rules and pack
